### ISSUE TITLE
Feature reuqest: Use configuration folder

### ISSUE THREAD

**Issue by Fale** [slackhq/nebula#1052]
It would be beneficial to be able to specify a folder in the config.yaml file that contains the configuration. The expected behavior would be that Nebula imports and combines all files present in the configuration folder to compose the configuration.
The benefit of this feature is to allow simpler automation of the configuration

**Comment by wadey** [comment]
Lucky for you, this has been supported since Nebula v1.0.0! Just point `nebula -config` at a folder and it will load every .yaml and .yml file in there in alphabetical order. Lists are combined, so you can spread firewall rules across multiple files.

**Comment by wadey** [comment]
You can also see this documented with `nebula -help`

**Comment by Fale** [comment]
very interesting, thanks a lot :), I was not aware of it!
