### ISSUE TITLE
🐛 BUG: Node(windows 10 laptop not lighthouse) continuously receiving the following information

### ISSUE THREAD

**Issue by daiwei-china** [slackhq/nebula#1056]
### What version of `nebula` are you using?

1.8.1

### What operating system are you using?

windows 10 ,11

### Describe the Bug

evertime i start nebula(windows 10 ,11)
it will continuously receiving:
-------------------------
 level=info msg="Handshake timed out" durationNs=6615***700 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=171**8 localIndex=17***8 remoteIndex=0 udpAddrs="[]" vpnIp=10.**.**.255
-------------------------
 i didnt sign the node 10.**.**.255  ,  and also i didnt ping 10.**.**.255 ,
every node(not lighthouse) has the sam wrong msg
(But it did not affect normal use, and communication between true nodes could also be normal)

### Logs from affected hosts

no important

### Config files from affected hosts

pki:
  ca:  /ca.crt
  cert:  /host.crt
  key:  /host.key

static_host_map:
 

lighthouse:
  am_lighthouse: false 
  interval: 60
  hosts:
   

listen:
  host: "::"
  port: 0

punchy:  
  punch: true
cipher: aes

relay:
  am_relay: false
  use_relays: false

tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:

logging:
  level: info
  format: text

firewall:
  outbound_action: drop
  inbound_action: drop

  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: any
      proto: any
      host: any

**Comment by nbrownus** [comment]
This is likely some service discovery mechanism that is probing the nebula mesh. You can make this change to your config and it should stop.

```
tun:
  drop_local_broadcast: true
  drop_multicast: true
```

**Comment by daiwei-china** [comment]
Thank you! After modifying the node config according to your suggestion, I did not receive any more msg from 10... 255.
Should i modify then lighthouse's confi ? 
and can you tell me what these two modifications represent and whether they will affect Nebula's own functionality?
