### ISSUE TITLE
🐛 ignore not applicable

### ISSUE THREAD

**Issue by jamiegau** [slackhq/nebula#1070]
### What version of `nebula` are you using?

1.2.3

### What operating system are you using?

windows server 2022

### Describe the Bug

In the past I have had small periods where I could not connect to a remote host, I would try a little later and ok.  But a few days ago ALL 6 locations I connect to that run Windows Server 2022.  I have been trying for 2-3 days now.  And none will not connect..  Takes about 2 seconds, then cums up with "Connection ERROR" remote is offline...
Hit reconnect over and over for minutes (As they sometimes helped) and nothing.  Will not connect.sometimes

This is where they need to implement the suggested syntax number@private-server-ip so I can rely on my own private-server if the public servers are behaving badly...  I still need the systems on public servers so I can have other people come in for support.

### Config files from affected hosts

Default config, apart from running my own server and selecting it as a Relay Server.

**Comment by IanVS** [comment]
Thanks for the report.  What version of nebula are you using?  I assume it's not 1.2.3 as posted above.

**Comment by jamiegau** [comment]
sorry, false alarm.  I entered this into the wrong project github page.

**Comment by IanVS** [comment]
Thanks for posting back!
