### ISSUE TITLE
🐛 BUG: Runtime Panic

### ISSUE THREAD

**Issue by chirayu-patel** [slackhq/nebula#1107]
### What version of `nebula` are you using? (`nebula -version`)

1.8.2

### What operating system are you using?

Linux

### Describe the Bug

Getting this Runtime bug all of a suden : 

Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]: panic: runtime error: index out of range [33] with length 22
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]:
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]: goroutine 28 [running, locked to thread]:
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]: github.com/slackhq/nebula.setTCPRTTTracking(0x10600000000?, {0x40000aa500?, 0xbdf240?, 0x29e8d60800?})
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]:        github.com/slackhq/nebula/firewall.go:969 +0xfc
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]: github.com/slackhq/nebula.(*Firewall).addConn(0x400020cf70, {0x40000aa500, 0x16, 0x2329}, {0xa1212fa, 0xc0a86603, 0x0, 0x0, 0x6, 0x1}, ...)
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]:        github.com/slackhq/nebula/firewall.go:556 +0x84
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]: github.com/slackhq/nebula.(*Firewall).Drop(0x400020cf70, {0x40000aa500, 0x16, 0x2329}, {0xa1212fa, 0xc0a86603, 0x0, 0x0, 0x6, 0x1}, ...)
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]:        github.com/slackhq/nebula/firewall.go:439 +0x264
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]: github.com/slackhq/nebula.(*Interface).consumeInsidePacket(0x40001c0500, {0x40000aa500, 0x16, 0x2329}, 0x40000a6010, {0x40000a6020, 0xc, 0xc}, {0x40000aca00, 0x2329, ...}, ...)
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]:        github.com/slackhq/nebula/inside.go:65 +0x21c
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]: github.com/slackhq/nebula.(*Interface).listenIn(0x40001c0500, {0x7f6b956dd8, 0x4000131100}, 0x0?)
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]:        github.com/slackhq/nebula/interface.go:288 +0xe8
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]: created by github.com/slackhq/nebula.(*Interface).run
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]:        github.com/slackhq/nebula/interface.go:246 +0xa0

### Logs from affected hosts

```
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]: panic: runtime error: index out of range [33] with length 22
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]:
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]: goroutine 28 [running, locked to thread]:
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]: github.com/slackhq/nebula.setTCPRTTTracking(0x10600000000?, {0x40000aa500?, 0xbdf240?, 0x29e8d60800?})
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]:        github.com/slackhq/nebula/firewall.go:969 +0xfc
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]: github.com/slackhq/nebula.(*Firewall).addConn(0x400020cf70, {0x40000aa500, 0x16, 0x2329}, {0xa1212fa, 0xc0a86603, 0x0, 0x0, 0x6, 0x1}, ...)
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]:        github.com/slackhq/nebula/firewall.go:556 +0x84
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]: github.com/slackhq/nebula.(*Firewall).Drop(0x400020cf70, {0x40000aa500, 0x16, 0x2329}, {0xa1212fa, 0xc0a86603, 0x0, 0x0, 0x6, 0x1}, ...)
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]:        github.com/slackhq/nebula/firewall.go:439 +0x264
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]: github.com/slackhq/nebula.(*Interface).consumeInsidePacket(0x40001c0500, {0x40000aa500, 0x16, 0x2329}, 0x40000a6010, {0x40000a6020, 0xc, 0xc}, {0x40000aca00, 0x2329, ...}, ...)
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]:        github.com/slackhq/nebula/inside.go:65 +0x21c
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]: github.com/slackhq/nebula.(*Interface).listenIn(0x40001c0500, {0x7f6b956dd8, 0x4000131100}, 0x0?)
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]:        github.com/slackhq/nebula/interface.go:288 +0xe8
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]: created by github.com/slackhq/nebula.(*Interface).run
Sun Mar 31 13:03:26 2024 daemon.err sdwan[3133]:        github.com/slackhq/nebula/interface.go:246 +0xa0
```

### Config files from affected hosts

```

```

**Comment by nbrownus** [comment]
Thanks for the report! Not sure what this packet actually is but its internet header length appears to be incorrect or there is a new bug in the rtt tracking. I have submitted a PR #1114 to fix the issue.
