### ISSUE TITLE
Restricted linux container permission problem 

### ISSUE THREAD

**Issue by jum** [slackhq/nebula#112]
On some restricted linux containers you can not set the TX queue length for tap devices. I had to comment out the following:

`--- a/tun_linux.go
+++ b/tun_linux.go
@@ -193,7 +193,7 @@ func (c Tun) Activate() error {
        // Set the transmit queue length
        ifrq := ifreqQLEN{Name: devName, Value: int32(c.TXQueueLen)}
        if err = ioctl(fd, unix.SIOCSIFTXQLEN, uintptr(unsafe.Pointer(&ifrq))); err != nil {
-               return fmt.Errorf("failed to set tun tx queue length: %s", err)
+               //return fmt.Errorf("failed to set tun tx queue length: %s", err)
        }

        // Bring up the interface
%`

In general I would believe that this situation should not be an error but just a warning.

**Comment by nbrownus** [comment]
Can you speak more to the restrictive nature of this environment? I'm curious how the rest of nebula works but setting MTU fails.

I think the real solution here would be to not attempt to set the MTU if one wasn't provided in config. We'd need to noodle on edge cases there, but in general if the intent in config is to set a specific MTU and the kernel rejects that intent, it is an error worth noticing. A warning is easily ignored, a fatal demands your attention.

**Comment by jum** [comment]
My lighthouse happens to be a cheap vserver from Hosteurope, which is now subsidiary of Godaddy. But googling the error message brought up a discussion from some OpenVPN discussion, where it is a notice message only. 

I agree with issuing the message only if the value is specified by the user.

**Comment by jum** [comment]
This does not fix my problem, as my server does bail out at line 197, the result of SIOCSIFTXQLEN. The setting of the MTU was no problem for me.

**Comment by nbrownus** [comment]
I'm very sorry! I have no idea how I got it in my head this was MTU.
