### ISSUE TITLE
example config: commented punchy.respond value should be false

### ISSUE THREAD

**Issue by kazzmir** [slackhq/nebula#1122]
https://github.com/slackhq/nebula/blob/a5a07cc7603187a75b116f26601882a93c371170/examples/config.yml#L156

The default value for punchy.respond is false, but in the sample config file the commented part shows `true`. Many of the other commented out fields show their default value in the comment, such as
```
#routines: 1
```
or
```
#cipher: aes
```
This led me to believe that punchy.response would default to true, leading to a very long debugging session in my network. Simply flipping punchy.respond to true solved my issue. I realize the english text above punchy.respond says 'default value is false', but I had missed that due to assuming the commented value was the default.

Can the sample config show `false` for punchy.respond?

**Comment by johnmaguire** [comment]
Hi @kazzmir - I apologize for the confusion, but the commented out values in this file are not defaults. You'll see in many cases they are simply examples (e.g. `static_host_map` and nearly the entirety of the `lighthouse` section.) Additionally, we already have a comment on the line above that the default is false: https://github.com/slackhq/nebula/blob/a5a07cc7603187a75b116f26601882a93c371170/examples/config.yml#L155-L156

For future reference, the defaults can be found on the hosted config reference found here: https://nebula.defined.net/docs/config/punchy/
