### ISSUE TITLE
🐛 BUG: wintun failed

### ISSUE THREAD

**Issue by coccigelus** [slackhq/nebula#1145]
### What version of `nebula` are you using? (`nebula -version`)

1.19

### What operating system are you using?

win

### Describe the Bug

2024/05/11 04:39:16 Using existing driver 0.14
2024/05/11 04:39:16 Creating adapter
2024/05/11 04:39:16 Failed to set adapter name ""
saw this issue already being discussed but no solution provided.  using tailscale and works. 2024/05/11 04:39:17 Using existing driver 0.14
2024/05/11 04:39:17 Creating adapter
2024/05/11 04:39:17 Failed to set adapter name ""
time="2024-05-11T04:39:17-05:00" level=error msg="Failed to get a tun/tap device" error="create Wintun interface failed, create TUN device failed: Error creating interface: The parameter is incorrect."

### Logs from affected hosts

```

```

### Config files from affected hosts

```

```

**Comment by johnmaguire** [comment]
@coccigelus Please finish filling out the issue template so we can assist. Thanks.

**Comment by coccigelus** [comment]
Hello,

 

I thought to give an update; Been able to solve the issue which was caused by the missing interface as pointed out by Hamish. After that I had some other  issue that have been polished related to certificate.  Given that I am in Asia and I rdp to a server I have in Canada with an ~300ms latency I am happy to report that Nebula is by far the best in term of reactivity compared to tailscale, netbird and zerotier.  Unfortunately I’ve got timed out when I try to ping the server and unless there is some command I am unaware I can’t provide any stats.  I am using fiber in Asia to an ovh server, any advice on the mtu setting?  (currently set up at 1300)

 

Have a great day!

Paolo

**Comment by johnmaguire** [comment]
> Unfortunately I’ve got timed out when I try to ping the server and unless there is some command I am unaware I can’t provide any stats.

I'm not sure what server you're pinging, or from what server, and still without logs and config, I'm unable to provide further assistance. Can you please [provide logs](https://nebula.defined.net/docs/guides/viewing-nebula-logs/) and configs for the hosts in question?

**Comment by coccigelus** [comment]
[conf.txt](https://github.com/slackhq/nebula/files/15299856/conf.txt)
[config-lighthouse.txt](https://github.com/slackhq/nebula/files/15299865/config-lighthouse.txt)

For some reason I can't upload in the first post.

**Comment by johnmaguire** [comment]
> time="2024-05-13T15:36:00-05:00" level=debug msg="dropping outbound packet, vpnIp not in our CIDR or in unsafe routes" fwPacket="&{192.168.100.1 239.255.255.250 51360 1900 17 false}" vpnIp=239.255.255.250

This is a multicast IP address. This message is generated by Windows. Nebula doesn't support multicast messages. You can safely ignore this.

Happy to hear you were able to get your network working!
