### ISSUE TITLE
🐛 BUG:  after dns changed, connection lost forever

### ISSUE THREAD

**Issue by yylt** [slackhq/nebula#1183]
### What version of `nebula` are you using? (`nebula -version`)

1.9.3

### What operating system are you using?

linux

### Describe the Bug

After the DNS change, the connection was not successful, and the log is as follows:

```
Jul 16 08:20:31 bpf nebula[762]: level=info msg="DNS results changed for host list" newSet="map[112.193.70.10:11010:{}]" origSet="&map[112.193.74.11:11010:{}]"
Jul 16 08:20:31 bpf nebula[762]: level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=4237819112 localIndex=4237819112 remoteIndex=0 udpAddrs=
"[112.193.74.11:11010 112.193.70.10:11010]" vpnIp=10.99.99.1
Jul 16 08:20:38 bpf nebula[762]: level=info msg="Handshake timed out" durationNs=6689486915 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=4237819112 localIndex=4237819112 remo
teIndex=0 udpAddrs="[112.193.74.11:11010 112.193.70.10:11010]" vpnIp=10.99.99.1
Jul 16 08:20:41 bpf nebula[762]: level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1848068562 localIndex=1848068562 remoteIndex=0 udpAddrs=
"[112.193.74.11:11010 112.193.70.10:11010]" vpnIp=10.99.99.1
Jul 16 08:20:48 bpf nebula[762]: level=info msg="Handshake timed out" durationNs=6589887970 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1848068562 localIndex=1848068562 remo
teIndex=0 udpAddrs="[112.193.74.11:11010 112.193.70.10:11010]" vpnIp=10.99.99.1
Jul 16 08:20:51 bpf nebula[762]: level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=860811292 localIndex=860811292 remoteIndex=0 udpAddrs="[
112.193.74.11:11010 112.193.70.10:11010]" vpnIp=10.99.99.1

```

The available address is `112.193.70.10`, It seems that only the first address is being used, which is the previous one and is currently unavailable.

### Logs from affected hosts

```

```

### Config files from affected hosts

```
static_host_map:
  "10.99.99.1": ["x.x.x:11010"]
lighthouse:
  am_lighthouse: false
  interval: 10
  hosts: 
    - "10.99.99.1"
listen:
  host: "::"
  port: 0
  read_buffer: 10485760
  write_buffer: 10485760
punchy:
  punch: true
  respond: true
cipher: chachapoly
relay:
  relays:
    - 10.99.99.1
  am_relay: false
tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:
    - route: 172.16.0.0/12
      via: 10.99.99.50
logging:
  level: info
  format: text
  disable_timestamp: true

```

**Comment by cg31** [comment]
I often have situation when connection lost, maybe sue to other reasons. Then I have to restart sever and clients.

I think Nebula needs a way to reconnect if there isn't one.

**Comment by johnmaguire** [comment]
@cg31 This is off-topic, please file a separate issue with logs if you're having problems. Nebula does of course attempt to re-establish tunnels when traffic is flowing.

@yylt I'm reading your logs and a bit confused about the issue. For example, this line:

```
Jul 16 08:20:31 bpf nebula[762]: level=info msg="DNS results changed for host list" newSet="map[112.193.70.10:11010:{}]" origSet="&map[112.193.74.11:11010:{}]"
```

This says that the _old_ IP address resolved was 112.193.74.11 and the _new_ IP address resolved was 112.193.70.10.

We then see the following handshake attempts:

```
Jul 16 08:20:31 bpf nebula[762]: level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=4237819112 localIndex=4237819112 remoteIndex=0 udpAddrs="[112.193.74.11:11010 112.193.70.10:11010]" vpnIp=10.99.99.1
...
Jul 16 08:20:41 bpf nebula[762]: level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1848068562 localIndex=1848068562 remoteIndex=0 udpAddrs="[112.193.74.11:11010 112.193.70.10:11010]" vpnIp=10.99.99.1
...
Jul 16 08:20:51 bpf nebula[762]: level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=860811292 localIndex=860811292 remoteIndex=0 udpAddrs="[112.193.74.11:11010 112.193.70.10:11010]" vpnIp=10.99.99.1
```

In each case, both addresses are being attempted: 112.193.74.11 and 112.193.70.10. DNS resolution doesn't appear to be at fault here. It seems you have another issue establishing connectivity. Providing logs from both sides may help in finding a resolution.

**Comment by yylt** [comment]
> @cg31 This is off-topic, please file a separate issue with logs if you're having problems. Nebula does of course attempt to re-establish tunnels when traffic is flowing.
> 
> @yylt I'm reading your logs and a bit confused about the issue. For example, this line:
> 
> ```
> Jul 16 08:20:31 bpf nebula[762]: level=info msg="DNS results changed for host list" newSet="map[112.193.70.10:11010:{}]" origSet="&map[112.193.74.11:11010:{}]"
> ```
> 
> This says that the _old_ IP address resolved was 112.193.74.11 and the _new_ IP address resolved was 112.193.70.10.
> 
> We then see the following handshake attempts:
> 
> ```
> Jul 16 08:20:31 bpf nebula[762]: level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=4237819112 localIndex=4237819112 remoteIndex=0 udpAddrs="[112.193.74.11:11010 112.193.70.10:11010]" vpnIp=10.99.99.1
> ...
> Jul 16 08:20:41 bpf nebula[762]: level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1848068562 localIndex=1848068562 remoteIndex=0 udpAddrs="[112.193.74.11:11010 112.193.70.10:11010]" vpnIp=10.99.99.1
> ...
> Jul 16 08:20:51 bpf nebula[762]: level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=860811292 localIndex=860811292 remoteIndex=0 udpAddrs="[112.193.74.11:11010 112.193.70.10:11010]" vpnIp=10.99.99.1
> ```
> 
> In each case, both addresses are being attempted: 112.193.74.11 and 112.193.70.10. DNS resolution doesn't appear to be at fault here. It seems you have another issue establishing connectivity. Providing logs from both sides may help in finding a resolution.

Since it is using DDNS (Dynamic DNS) method, there is actually only one IP address available, although the logs show two IP addresses, only the latter one `112.193.70.10` is usable. It look like that there is no attempt to connect to `112.193.70.10`, but only the first address `112.193.74.11`, which is obviously failed forever.

**Comment by johnmaguire** [comment]
@yylt the logs indicate the node is trying both IPs.

**Comment by johnmaguire** [comment]
> trying, but it always times out, and the logs show these two entries repeating, with many omitted here. And until service restart, it connect lighthouse success.

OK, so we're on the same page now. The original ticket noted that it wasn't trying against the new IP address. I agree from the logs that despite attempting to handshake with the new IP address, we're not seeing return handshake packets.

As mentioned previously, providing correlated logs from both sides may help in finding a resolution.

> In fact, when manually query DNS, only one address 112.193.70.10 is returned, but it's puzzling why two addresses are being used here. I made modifications in https://github.com/slackhq/nebula/pull/1184 to prevent updating the IP upon DNS failure, which has resolved some of the issues.

As far as why both IP addresses are being tried, Nebula keeps a list of possible underlay IP addresses around for a given host. IIRC, we track ~20 addresses. This is an append-only list. Packets will be sent to the previously resolved IP address and the more recently resolved IP address. This is working as designed.
