### ISSUE TITLE
🐛 BUG: Are some external relays being used without any clear notice?

### ISSUE THREAD

**Issue by poige** [slackhq/nebula#1221]
### What version of `nebula` are you using? (`nebula -version`)

1.9.4

### What operating system are you using?

…irrelevant to the issue's matter…

### Describe the Bug

I actually would even consider that a security (or privacy rather) vulnerability. How come when turning "use relays" on I'm seeing traffic from some amazon's EC2 instances which (instances) I don't have any relation to?

### Logs from affected hosts

…irrelevant to the issue's matter…

### Config files from affected hosts

…irrelevant to the issue's matter…

**Comment by johnmaguire** [comment]
> I actually would even consider that a security (or privacy rather) vulnerability. How come when turning "use relays" on I'm seeing traffic from some amazon's EC2 instances which (instances) I don't have any relation to?

I suspect this doesn't have anything to do with enabling `use_relays` - unless of course those EC2s are configured as relays for hosts you're trying to communicate with.

If the concern is that third-party relays are being introduced to your network, this is not the case. We don't run any sort of public infrastructure for Nebula. Nebula handshakes with hosts via "underlay" IPs defined in the `static_host_map` or discovered through the Lighthouse (which uses self-reported IP addresses from your hosts as well as using the IP packet header to learn a NAT IP address - public IP address - of a node.)

So to answer your question: "Are some external relays being used without any clear notice?" No.

Here is some further reading on relays:

- [Relay Support in Nebula 1.6.0](https://www.defined.net/blog/announcing-relay-support-in-nebula/)
- [relay docs](https://nebula.defined.net/docs/config/relay/)
