### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by gerroon** [slackhq/nebula#123]
it looks like a lot has been done, would be nice to get a new release is possible.

`103 commits to master since this release `

**Comment by nbrownus** [comment]
We are marching towards a v1.1.0 release, you can watch the progress with the above link or via [v1.1.0](https://github.com/slackhq/nebula/milestone/1)

**Comment by wadey** [comment]
@gerroon  Just in case you didn't see, v1.1.0 has been released :tada:
