### ISSUE TITLE
🐛 BUG: does nebula work on symmetric NAT

### ISSUE THREAD

**Issue by coralislands** [slackhq/nebula#1235]
### What version of `nebula` are you using? (`nebula -version`)

1.9.4

### What operating system are you using?

Mac

### Describe the Bug

Getting started with nebula and I see that it uses UDP hole punching for peer discovery.
So, does this mean on networks with UDP traffic blocked or symmetric NATS, nebula doesn't work?

Creating this as a bug since I don't see another template for the question 

### Logs from affected hosts

N/A

### Config files from affected hosts

N/A

**Comment by IanVS** [comment]
To account for those situations, please have a look at using relays.  https://nebula.defined.net/docs/config/relay/. They were created to handle symmetric NAT.
