### ISSUE TITLE
Missing \n when testing config:

### ISSUE THREAD

**Issue by asarubbo** [slackhq/nebula#1248]
On 1.9.4:

`./nebula -config config.yml -test` results in:

```
INFO[2024-10-11T10:54:06+02:00] lighthouse:
  am_lighthouse: false
  interval: 60
<snip>
```

So there is a missing \n between `INFO[2024-10-11T10:54:06+02:00]` and `lighthouse:`

**Comment by johnmaguire** [comment]
This is working as designed. The config YAML is output as a `log.Info()`, which doesn't add a newline by default. In other modes (such as JSON formatter), this would appear as `"message": "lighthouse:\n am_lighthouse: false\n  interval: 60\n<snip>",` which is how we want it.
