### ISSUE TITLE
nebula-cert code coupling is severe

### ISSUE THREAD

**Issue by QZAiXH** [slackhq/nebula#1254]
When integrating Nebula in my project, I ran into a problem: nebula-cert writes the generated certificate and key to a file by default. This prevents me from conveniently accessing them via function calls, and I have to deal with them by reading the file. Therefore, I think the logic for generating certificates should be separated from the logic for writing them to a file to increase flexibility.

**Comment by nbrownus** [comment]
You can generate the certificates without using the `nebula-cert` package.

Here are some examples:
https://github.com/slackhq/nebula/blob/v1.9.4/e2e/helpers.go#L16
https://github.com/slackhq/nebula/blob/v1.9.4/e2e/helpers.go#L69

We have recently changed this as well in preparation for the next release so the process should be a little bit easier in future versions:
https://github.com/slackhq/nebula/blob/08ac65362e344a1ac1905802b36fd1b5cb5b034b/e2e/helpers.go#L15
https://github.com/slackhq/nebula/blob/08ac65362e344a1ac1905802b36fd1b5cb5b034b/e2e/helpers.go#L51

**Comment by QZAiXH** [comment]
Thanks, I will try to generate the certificate via that method
