### ISSUE TITLE
FATA[0000] error while unmarshaling pki.key /etc/nebula/ca.crt: bytes did not contain a proper nebula X25519 private key banner 

### ISSUE THREAD

**Issue by ghstwhl** [slackhq/nebula#126]
In building a multi-node VPN, I encountered a problem when adding an Ubuntu 18.04 LTS node, after having already connected  MacOS 10.13.6 and Ubuntu 16.04 nodes.  The Ubuntu 16.04 host was configured as a lighthouse, and when attempting to add the Ubuntu 18.04 host it was being added as a second lighthouse.

All certs and keys were generated on MacOS.  No issues.  

I generated a new CA and host pair, and tried spinning up the Ubuntu 18.04 host as an independent lighthouse, but got the same error as in the title.

Is there an known issue with Ubuntu 18.04?  Are there any logs I could provide that would be useful?

**Comment by rawdigits** [comment]
Based on the error, it appears your configuration is incorrect. You probably have pki: -> key: pointed at the wrong file (in this case ca.crt). If you want to verify configuration, you can attach the pki config section to this issue.

**Comment by ghstwhl** [comment]
And this is why I shouldn't be writing puppet module past 11pm when I've been sick.  Thanks. :)
