### ISSUE TITLE
Documentation Question: Unsafe_Routes vs. nebula-cert

### ISSUE THREAD

**Issue by JonTheNiceGuy** [slackhq/nebula#127]
In [the example config file, in the section on "unsafe routes"](https://github.com/slackhq/nebula/blob/8e6b72516b4028d8533930b2f5a7014031b369ba/examples/config.yml#L103-L109) it's mentioned that the nebula certificate of the via node must have the route defined as a subnet.

Please can someone note how to do this with `nebula-cert`?

Thanks!

**Comment by nfam** [comment]
By providing `-subnets`
> nebula-cert sign -name "homelab"  -ip "192.168.100.2/24"  -subnets "192.168.16.1/24"

**Comment by rawdigits** [comment]
@nfam is correct! going to close this one for now.
