### ISSUE TITLE
TCP default timeout: firewall.go shows 12 minutes, config shows 120h

### ISSUE THREAD

**Issue by JonTheNiceGuy** [slackhq/nebula#128]
According to [firewall.go](https://github.com/slackhq/nebula/blob/e465b130451164a8c62aeba250d241a496904b7e/firewall.go#L189) the tcp_timeout is set to time.Minute*12. The [config.yml](https://github.com/slackhq/nebula/blob/e465b130451164a8c62aeba250d241a496904b7e/examples/config.yml#L137) for the same commit suggests a tcp_timeout of 120h.

Which of these is "better"? Or... is one of these a typo? :grin:

**Comment by rawdigits** [comment]
The default in firewall.go is 12 minutes and the example is 120 hours. It all depends on your individual network and configuration.

120 hours is pretty ridiculously long, and was probably put there so we could avoid edge cases where people with long lived tcp (but a proto without keepalives) doesn't get unexpectedly disconnected from things.

A good default for documentation purposes may be something like a day or so. We should probably just copy whatever linux/iptables use as a default.

**Comment by rawdigits** [comment]
(closing for now, but lmk if we need to reopen)

**Comment by JonTheNiceGuy** [comment]
@rawdigits, no need to re-open, but most commercial FW products (Check Point and FortiGate) are set to 10m

**Comment by rawdigits** [comment]
Good to know! IIRC AWS used to default to 12 minutes on their SDN too. It makes sense, given the amount of state you need to keep in large networks, and the memory that can consume. I don't recall what we use internally at slack, but I have my personal network using the default 12 minutes and everything seems to work fine.

**Comment by wadey** [comment]
We fixed this in #236
