### ISSUE TITLE
Question: can't connect to lighthouse behind corporate firewall

### ISSUE THREAD

**Issue by Tennyleaz** [slackhq/nebula#129]
Hi,
I have a lighthouse and 2 clients set up. My home client can connect to the lighthouse, but my workplace client can't.
All I get is the following message:

    INFO[0000] Handshake message sent  handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1233308108 remoteIndex=0 udpAddr="lighthouse_ip:4242" vpnIp=192.168.100.1

My lighthouse config is:

```yaml
    pki:
      ca: /home/ubuntu/nebula/ca.crt
      cert: /home/ubuntu/nebula/lighthouse1.crt
      key: /home/ubuntu/nebula/lighthouse1.key
    
    static_host_map:
      "192.168.100.1": ["lighthouse_ip:4242"]
    
    lighthouse:
      am_lighthouse: true
      interval: 60
      hosts:
    
    listen:
      host: 0.0.0.0
      port: 4242
    
    punchy: true
    
    tun:
      dev: nebula1
      drop_local_broadcast: false
      drop_multicast: false
      tx_queue: 500
      mtu: 1300
      routes:
      unsafe_routes:
    
    logging:
      level: info
      format: text
    
    firewall:
      conntrack:
        tcp_timeout: 120h
        udp_timeout: 3m
        default_timeout: 10m
        max_connections: 100000    
      outbound:
        - port: any
          proto: any
          host: any
      inbound:
        - port: any
          proto: icmp
          host: any
        - port: 443
          proto: tcp
          groups:
            - laptop
            - home
```
I guess my workplace firewall is blocking me from lighthouse. What should I do now?

**Comment by bodleytunes** [comment]
Change lighthouse to listen on 443/tcp if its possible.
Or on the lighthouse, provision an iptables rule to **redirect** traffic from the source of corp public IP address from port 443 to port 4242 when it arrives.

There is a chance 443 is the least likely port to be blocked unless they are running L7 inspection (fortigate/palo alto) firewalls.

I always use 443 for overzelous firewalls.

**Comment by Tennyleaz** [comment]
I modified config.yml like:

```yaml
    static_host_map:
      "192.168.100.1": ["lighthouse_ip:443"]

    listen:
      port: 443

    stats:
      protocol: tcp
```
On both lighthouse and the client. 

Lighthouse message shows:

```
INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:outgoing endPort:0 groups:[] host:any ip:<nil> proto:0 startPort:0]"
INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host:any ip:<nil> proto:1 startPort:0]"
INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:incoming endPort:443 groups:[laptop home] host: ip:<nil> proto:6 startPort:443]"
INFO[0000] Firewall started                              firewallHash=853d3005de969aa0cb1100731e983a740ab4218f89c78189edd389ff5e05ae99
INFO[0000] Main HostMap created                          network=192.168.100.1/24 preferredRanges="[]"
INFO[0000] UDP hole punching enabled
INFO[0000] Nebula interface is active                    build=1.0.0 interface=nebula1 network=192.168.100.1/24
```

And I still get this message on the workspace client:

    INFO[0012] Handshake message sent  handshake="map[stage:1 style:ix_psk0]" initiatorIndex=520205444 remoteIndex=0 udpAddr="lighthouse_ip:443" vpnIp=192.168.100.1

**Comment by rawdigits** [comment]
Nebula doesn't support using TCP as a transport. If you want to debug udp connectivity in general, `ncat` or `nc` are handy ways to determine whether traffic is allowed out at all.

**Comment by onyn** [comment]
For those who interested. In environments with restricted UDP, nebula won't work. But there's workaround using socat.

1. Install and run socat on client machine:

```
onyn@node1:~$ socat UDP-LISTEN:1234,fork,reuseaddr TCP4:1.2.3.4:1234
```

Replace 1.2.3.4 with public IP or FQDN of your lighthouse server. Also you may choose any port of your choice instead of 1234.

Modify nebula config:

```yaml
static_host_map:
  "192.168.100.1": ["127.0.0.1:1234"]
```

Replace 192.168.100.1 with nebula IP of your lighthouse installation.

2. Install and run socat on lighthouse server machine:

```
onyn@lighthouse-server:~$ socat TCP-LISTEN:1234,fork,reuseaddr UDP:127.0.0.1:4242
```


Illustration how this works:

```
+----------------------------------------------------+
| node1                                              |
|                                                    |
| +---------------+  UDP (127.0.0.1:1234)  +-------+ |
| | nebula client | ---------------------> | socat | |
| +---------------+                        +-------+ |
+--------------------------------------------- | ----+
                                               |
                            TCP (1.2.3.4:1234) | 
                                               |
+--------------------------------------------- | ----+
| lighthouse-server                            |     |
|                                              V     |
| +---------------+  UDP (127.0.0.1:4242)  +-------+ |
| | lighthouse    | <--------------------- | socat | |
| +---------------+                        +-------+ |
+----------------------------------------------------+
```

Ofcourse node1 can communicate with other nodes only via lighthouse as relay. However, relay didn't worked for me. May be because experimental status of this feature.
