### ISSUE TITLE
cmd/nebula/main.go:8:2: cannot find package "github.com/slackhq/nebula"

### ISSUE THREAD

**Issue by ttulttul** [slackhq/nebula#13]
During "make all" on a fresh Ubuntu machine on Amazon Lightsail, I get this:

$ make all
make bin-linux
make[1]: Entering directory '/home/ubuntu/nebula'
mkdir -p build/linux
GOARCH=amd64 GOOS=linux go build -o build/linux/nebula -ldflags "-X main.Build=dev+20191120181618" ./cmd/nebula
cmd/nebula/main.go:8:2: cannot find package "github.com/slackhq/nebula" in any of:
	/usr/lib/go-1.6/src/github.com/slackhq/nebula (from $GOROOT)
	/home/ubuntu/nebula/src/github.com/slackhq/nebula (from $GOPATH)
Makefile:51: recipe for target 'bin-linux' failed
make[1]: *** [bin-linux] Error 1
make[1]: Leaving directory '/home/ubuntu/nebula'
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2

I'm probably an idiot, but what am I missing?

**Comment by rawdigits** [comment]
My best guess is an older version of `go` is installed on the system. You can check the currently installed version by running `go version`. I don't recall our required minimum version of go (should document), but @nbrownus probably knows.

**Comment by ttulttul** [comment]
go version go1.6.2 linux/amd64

**Comment by rawdigits** [comment]
Ah yes, unfortunately that version is a bit too old. You have a couple of options:
1) install a newer version of go, which you can download here: https://golang.org/dl/
2) use one of the binary releases for your platform here: https://github.com/slackhq/nebula/releases

(note: I totally appreciate some folks not wanting to use the release binaries and preferring to compile from source, but just wanted to make sure you were aware binaries are available)

**Comment by wadey** [comment]
Or current minimum version is listed in the go.mod file, it is 1.12 (although I would recommend using latest): https://github.com/slackhq/nebula/blob/master/go.mod#L3

**Comment by ttulttul** [comment]
Thank you for such a quick response. Unfortunately golang-1.12 is not available in apt on the version of Ubuntu I'm using on Lightsail. Such is life. I shall upgrade.
