### ISSUE TITLE
need change tun device path when run  in termux

### ISSUE THREAD

**Issue by labulaka521** [slackhq/nebula#131]
change`/dev/net/tun` to `/dev/tun` in tun_linux.go

**Comment by rawdigits** [comment]
Can you provide some more detail on why/how/what/where/when? We can't just change the path for tun_linux.go without affecting linux on everything that isn't termux.

**Comment by labulaka521** [comment]
sorry,I want to install nebula to my andriod plone, so i use termux ,
but i found the tun file path is not `/dev/net/tun`,this file path is` /dev/tun`,so i suggest  set a option in config.yml,if set use tun file path in config, use new tun file path, otherwise use default tun file path[/dev/net/tun]
this is my termux 
```
# uname -a
Linux localhost 4.9.65-perf-g30ff678 #1 SMP PREEMPT Fri Oct 26 13:10:48 CST 2018 armv8l Android
# ls /dev/tun
/dev/tun
# ls /dev/net/tun
ls: cannot access '/dev/net/tun': No such file or directory
```
this is release v1.0
```go
# ./nebula -version
Version: 1.0.0
# ./nebula -config config.yml 
DEBU[0000] Trusted CA fingerprints                       fingerprints="[8fdddc001a0e6c8266707cb8df604ac93938eafbbd0d763983b47c0ba4cb493f]"
DEBU[0000] Client nebula certificate                     cert="NebulaCertificate {\n\tDetails {\n\t\tName: node_13\n\t\tIps: [\n\t\t\t10.0.0.13/24\n\t\t]\n\t\tSubnets: []\n\t\tGroups: []\n\t\tNot before: 2019-12-25 05:59:38 +0000 UTC\n\t\tNot After: 2020-12-19 10:11:44 +0000 UTC\n\t\tIs CA: false\n\t\tIssuer: 8fdddc001a0e6c8266707cb8df604ac93938eafbbd0d763983b47c0ba4cb493f\n\t\tPublic key: 47cba31fa2ff45dd9578b348ccc8580459159b3f832a386c22cb414041734b25\n\t}\n\tFingerprint: 69633d5badab2961dc6eb90ec6222a720b862a8b693bff5b3cdbc8063b4059d4\n\tSignature: 3a3ae8bfe48de52bcc8767b54701036e3a1231621e246945f7a744919f34c43fc2c8f5ded1f343f1ff3ff389c304a096c2676c80320dfaab5a35d63f76507e03\n}"
INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:outgoing endPort:0 groups:[] host:any ip:<nil> proto:0 startPort:0]"
INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host:any ip:<nil> proto:1 startPort:0]"
INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host: ip:10.0.0.0/24 proto:0 startPort:0]"
INFO[0000] Firewall started                              firewallHash=eff5e716a65160ae2587067ad06a35ab4cdd9ac9b29fd6011ff375842d2f6635
FATA[0000] no such file or directory 
```
after i change source code tun file path to `/dev/tun` ,it works 
i suggest could custom the tun file in config

**Comment by rawdigits** [comment]
@labulaka521 fwiw, i ported nebula to android a couple of weeks ago and just doing some initial testing before releasing it to the entire app store.

Feel free to join the slack group nebulaoss.slack.com and I can add you to the alpha test if you'd like.

In the meantime, closing this issue. If you still have a need for nebua in termux once nebula for android is available, let me know and I'll reopen.

**Comment by labulaka521** [comment]
i can not join it ,because this group need invitate

**Comment by orbistertius** [comment]
Hello, I'm also interested in Android app.
Just did as @labulaka521 and this requires a rooted Android device, which is something not everyone is going to do.

@rawdigits: does your port require a rooted device, and in case would be possible to call [Android VPN API](https://developer.android.com/guide/topics/connectivity/vpn) to setup the TUN device without root?

Many thanks in advance.

**Comment by nbrownus** [comment]
This android build would be something you get from the Play store so no rooting required.

**Comment by aa51513** [comment]
> 抱歉，我想将nebula安装到我的andriod plone上，所以我使用termux， 但是我发现tun文件路径不是`/dev/net/tun`，这个文件路径是` /dev/tun`，所以我建议在config.yml中设置一个选项，如果设置使用tun文件路径配置，使用新的 tun 文件路径，否则使用默认的 tun 文件路径[/dev/net/tun] 这是我的 termux
> 
> ```
> # uname -a
> Linux localhost 4.9.65-perf-g30ff678 #1 SMP PREEMPT Fri Oct 26 13:10:48 CST 2018 armv8l Android
> # ls /dev/tun
> /dev/tun
> # ls /dev/net/tun
> ls: cannot access '/dev/net/tun': No such file or directory
> ```
> 
> 这是 v1.0 版本
> 
> ```go
> # ./nebula -version
> Version: 1.0.0
> # ./nebula -config config.yml 
> DEBU[0000] Trusted CA fingerprints                       fingerprints="[8fdddc001a0e6c8266707cb8df604ac93938eafbbd0d763983b47c0ba4cb493f]"
> DEBU[0000] Client nebula certificate                     cert="NebulaCertificate {\n\tDetails {\n\t\tName: node_13\n\t\tIps: [\n\t\t\t10.0.0.13/24\n\t\t]\n\t\tSubnets: []\n\t\tGroups: []\n\t\tNot before: 2019-12-25 05:59:38 +0000 UTC\n\t\tNot After: 2020-12-19 10:11:44 +0000 UTC\n\t\tIs CA: false\n\t\tIssuer: 8fdddc001a0e6c8266707cb8df604ac93938eafbbd0d763983b47c0ba4cb493f\n\t\tPublic key: 47cba31fa2ff45dd9578b348ccc8580459159b3f832a386c22cb414041734b25\n\t}\n\tFingerprint: 69633d5badab2961dc6eb90ec6222a720b862a8b693bff5b3cdbc8063b4059d4\n\tSignature: 3a3ae8bfe48de52bcc8767b54701036e3a1231621e246945f7a744919f34c43fc2c8f5ded1f343f1ff3ff389c304a096c2676c80320dfaab5a35d63f76507e03\n}"
> INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:outgoing endPort:0 groups:[] host:any ip:<nil> proto:0 startPort:0]"
> INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host:any ip:<nil> proto:1 startPort:0]"
> INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host: ip:10.0.0.0/24 proto:0 startPort:0]"
> INFO[0000] Firewall started                              firewallHash=eff5e716a65160ae2587067ad06a35ab4cdd9ac9b29fd6011ff375842d2f6635
> FATA[0000] no such file or directory 
> ```
> 
> 在我将源代码 tun 文件路径更改为之后`/dev/tun`，它可以工作， 我建议可以在配置中自定义 tun 文件

Why the proposal to specify or use the default tun path is not accepted, can I understand the specific reason?
@rawdigits
