### ISSUE TITLE
Add/Remove groups

### ISSUE THREAD

**Issue by daxm** [slackhq/nebula#143]
I'm guessing that in order to add/remove a node from a group that I'd need to revoke and re-issue a new cert for them?  If not, what is the process of changing a node's group settings?

**Comment by rawdigits** [comment]
That is correct. We tend to use very short lived certs for production uses, but even then we rarely change group membership.

**Comment by rawdigits** [comment]
One more note: you can deliver a new cert to a host and HUP the nebula process to signal nebula to load the new certificate without restarting.

Let us know if you need anything further. Closing issue for now as the question is answered.
