### ISSUE TITLE
Question: can a lighthouse be configured as a gateway to allow anonymous web browsing from a node?

### ISSUE THREAD

**Issue by russdirks** [slackhq/nebula#145]
I'm probably in way over my head on this, but am curious just the same.  If it's possible I would like to try to figure it out.  Probably need DNS on the lighthouse for sure.

**Comment by rawdigits** [comment]
It is possible, but not currently well supported. You could set the lighthouse as an iptables masquerade host and route all traffic for 0.0.0.0/0 through it with linux routing. You'll also need 0.0.0.0/0 defined in `subnets` within the nebula certificate for the lighthouse.

Very much "probably works, but not supported" for the moment.

**Comment by russdirks** [comment]
Thanks, I'll give that a try.

**Comment by JohnMaguire** [comment]
Relevant: #280
