### ISSUE TITLE
Node1 LAN to Node2 LAN connectivity problem,  Tunnel is  active

### ISSUE THREAD

**Issue by bmullan** [slackhq/nebula#154]
I have 3 servers

**Node0** is the Nebula **Lighthouse** server _on Hetzner Cloud in Germany_
**Node1** is a KVM Ubuntu VM here at my home. 
**Node2** is a KVM Ubuntu VM here at my home. 

Both Node1 and Node2 are on the same 192.168.122.0 subnet. 

Both Node1 and Node2 have LXD Containers on them behind a 10.x.x.1/24 DNSMASQ bridge

The Nebula Configs for each Node0, Node1 and Node2 are attached.

I created the Certs for Node1 and Node2 and specified for each the Subnet of the LXD containers (see configs).

Starting Nebula on all three nodes and Node1 and Node2 connect to Node0 (Lighthouse)

**Node1 can ping the nebula1 tunnel interface IP of Node2  and Node0** (lighthouse)  
**Node2 can ping the nebula1 tunnel interface IP of Node1  and Node0** (lighthouse)  
  
**Node 0 can ping both Node1 and Node2 nebula1 interface IP address**

Node0 pings

> node0:~$ ping 10.0.1.2
> PING 10.0.1.2 (10.0.1.2) 56(84) bytes of data.
> 64 bytes from 10.0.1.2: icmp_seq=1 ttl=64 time=140 ms
> 64 bytes from 10.0.1.2: icmp_seq=2 ttl=64 time=134 ms

> **node0**:~$ ping 10.0.1.3
> PING 10.0.1.3 (10.0.1.3) 56(84) bytes of data.
> 64 bytes from 10.0.1.3: icmp_seq=1 ttl=64 time=138 ms
> 64 bytes from 10.0.1.3: icmp_seq=2 ttl=64 time=140 ms

**Problem:**  
- Node1 can not ping the LXD 10.12.1.1 Bridge on Node2 or any of the LXD containers behind that bridge (re say (10.12.1.56)  
- Node2 can not ping the LXD 10.11.1.1 Bridge on Node1 or any of the LXD containers behind that bridge (re say 10.11.1.21)  

So with Nebula there is reachablity to every node from every other node _**but only to the Tunnel End Point (TEP) on the other end**_... not beyond to the other-side's LAN

_Port 4242 is open everywhere or the Tunnels and Tunnel interface would not come up._

I'm looking for a reason for this or what I might be missing.   I did try implementing some **iptables**
statements on each node to forward traffic to/from the nebula1 TUN interface to/from LAN but unless I did those wrong... it made no difference.

**NODE0 IPTABLES**

> node0:~$ **sudo iptables -S**
> -P INPUT ACCEPT
> -P FORWARD ACCEPT
> -P OUTPUT ACCEPT
> -A INPUT -i t1-br -p tcp -m tcp --dport 53 -m comment --comment "generated for LXD network t1-br" -j ACCEPT
> -A INPUT -i t1-br -p udp -m udp --dport 53 -m comment --comment "generated for LXD network t1-br" -j ACCEPT
> -A INPUT -i t1-br -p udp -m udp --dport 67 -m comment --comment "generated for LXD network t1-br" -j ACCEPT
> -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
> -A FORWARD -s 10.0.1.0/24 -d 10.10.1.0/24 -i nebula1 -o t1-br -m conntrack --ctstate NEW -j ACCEPT
> -A FORWARD -o t1-br -m comment --comment "generated for LXD network t1-br" -j ACCEPT
> -A FORWARD -i t1-br -m comment --comment "generated for LXD network t1-br" -j ACCEPT
> -A OUTPUT -o t1-br -p tcp -m tcp --sport 53 -m comment --comment "generated for LXD network t1-br" -j ACCEPT
> -A OUTPUT -o t1-br -p udp -m udp --sport 53 -m comment --comment "generated for LXD network t1-br" -j ACCEPT
> -A OUTPUT -o t1-br -p udp -m udp --sport 67 -m comment --comment "generated for LXD network t1-br" -j ACCEPT

**NODE1 IPTABLES**  

> node1:~$ **sudo iptables -S**
> -P INPUT ACCEPT
> -P FORWARD ACCEPT
> -P OUTPUT ACCEPT
> -A INPUT -i t1-br -p tcp -m tcp --dport 53 -m comment --comment "generated for LXD network t1-br" -j ACCEPT
> -A INPUT -i t1-br -p udp -m udp --dport 53 -m comment --comment "generated for LXD network t1-br" -j ACCEPT
> -A INPUT -i t1-br -p udp -m udp --dport 67 -m comment --comment "generated for LXD network t1-br" -j ACCEPT
> -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
> -A FORWARD -s 10.0.1.0/24 -d 10.11.1.0/24 -i nebula1 -o t1-br -m conntrack --ctstate NEW -j ACCEPT
> -A FORWARD -o t1-br -m comment --comment "generated for LXD network t1-br" -j ACCEPT
> -A FORWARD -i t1-br -m comment --comment "generated for LXD network t1-br" -j ACCEPT
> -A OUTPUT -o t1-br -p tcp -m tcp --sport 53 -m comment --comment "generated for LXD network t1-br" -j ACCEPT
> -A OUTPUT -o t1-br -p udp -m udp --sport 53 -m comment --comment "generated for LXD network t1-br" -j ACCEPT
> -A OUTPUT -o t1-br -p udp -m udp --sport 67 -m comment --comment "generated for LXD network t1-br" -j ACCEPT

**NODE2 IPTABLES**

> node2:~$ **sudo iptables -S**
> -P INPUT ACCEPT
> -P FORWARD ACCEPT
> -P OUTPUT ACCEPT
> -A INPUT -i t1-br -p tcp -m tcp --dport 53 -m comment --comment "generated for LXD network t1-br" -j ACCEPT
> -A INPUT -i t1-br -p udp -m udp --dport 53 -m comment --comment "generated for LXD network t1-br" -j ACCEPT
> -A INPUT -i t1-br -p udp -m udp --dport 67 -m comment --comment "generated for LXD network t1-br" -j ACCEPT
> -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
> -A FORWARD -s 10.0.1.0/24 -d 10.12.1.0/24 -i tun0 -o t1-br -m conntrack --ctstate NEW -j ACCEPT
> -A FORWARD -o t1-br -m comment --comment "generated for LXD network t1-br" -j ACCEPT
> -A FORWARD -i t1-br -m comment --comment "generated for LXD network t1-br" -j ACCEPT
> -A OUTPUT -o t1-br -p tcp -m tcp --sport 53 -m comment --comment "generated for LXD network t1-br" -j ACCEPT
> -A OUTPUT -o t1-br -p udp -m udp --sport 53 -m comment --comment "generated for LXD network t1-br" -j ACCEPT
> -A OUTPUT -o t1-br -p udp -m udp --sport 67 -m comment --comment "generated for LXD network t1-br" -j ACCEPT

I am suspecting the routing problem has to do with use of the 2 KVM VMs as Nodes but in today's world where Containers are everywhere ... that would seem to be a common encounter for Nebula.

[node0-config.yml.txt](https://github.com/slackhq/nebula/files/4037327/node0-config.yml.txt)
[node1-config.yml.txt](https://github.com/slackhq/nebula/files/4037329/node1-config.yml.txt)
[node2-config.yml.txt](https://github.com/slackhq/nebula/files/4037330/node2-config.yml.txt)

**Comment by radcool** [comment]
I haven't used routes on Nebula, and I'm not that familiar with LXD, so perhaps I'm shooting in the dark here, but have you confirmed that IPv4 forwarding is enabled in the kernel and that the expected IP routes are configured on the nodes (I assume Nebula does this upon tunnel establishment but as I've said I've never tried this myself).

**Comment by bmullan** [comment]
Thanks
Yes I had made sure that it was... executed the following on all nodes.

$ sudo sysctl -w net.ipv4.ip_foward=1

**Comment by radcool** [comment]
OK then. Well, I guess short of running tcpdump on the interfaces to try to figure out where packets get swallowed up I'm out of ideas!

**Comment by bmullan** [comment]
thats ok... thanks for trying though!

**Comment by Srar** [comment]
Nebula checks every packet to ensure the IP of packet match certificate.

https://github.com/slackhq/nebula/blob/master/firewall.go#L363
