### ISSUE TITLE
nebula -service install failed

### ISSUE THREAD

**Issue by livid** [slackhq/nebula#156]
OS version: Windows 10 Pro 1909

I tried to install the service, and this is what I'm keeping getting:

```
nebula -service install -config D:\Apps\Nebula\config.yml
2020/01/09 23:58:30 Valid actions: ["start" "stop" "restart" "install" "uninstall"]
2020/01/09 23:58:30 Failed to install Nebula Network Service: service Nebula already exists
```

While there is no Nebula service installed before.

I also tried to uninstall, this is what I got.

First try:

```
nebula -service uninstall
2020/01/09 23:57:16 Valid actions: ["start" "stop" "restart" "install" "uninstall"]
2020/01/09 23:57:16 Failed to uninstall Nebula Network Service: RemoveEventLogSource() failed: The system cannot find the file specified.
```

Second try:

```
nebula -service uninstall
2020/01/10 00:01:34 Valid actions: ["start" "stop" "restart" "install" "uninstall"]
2020/01/10 00:01:34 Failed to uninstall Nebula Network Service: The specified service has been marked for deletion.
```

**Comment by jhollowe** [comment]
Try searching in windows for Services and look in that window for "Nebula Network Service".
That should tell you if the service is actually installed. You might try restarting the service if it exists.

**Comment by livid** [comment]
I used `sc queryex nebula` to find that a Logitech Service used the same "nebula" name, it's in `C:\Program Files\Logitech\Collaboration\Services\Video\`. The problem is solved after I removed Logitech related software.
