### ISSUE TITLE
Revert changes to TAP adapter (static IP) when nebula is stopped

### ISSUE THREAD

**Issue by alexvy86** [slackhq/nebula#159]
I successfully set up a LH+2-node Nebula mesh where the 2 nodes are running Windows (with OpenVPN preinstalled, and that's how they had a TAP adapter). In the process, I noticed that Nebula sets up static IPs on the TAP adapters (at least on the Windows machines), which caused me a couple of headaches trying to figure out why my connections to OpenVPN servers were not working anymore after I stopped Nebula. Removing the static IP and setting DNS servers to be obtained automatically, solved the issue.

Is it possible (or are there plans for it) to only apply the static IP to the TAP adapter while Nebula is running, and revert any changes when we stop it? Or what's the recommended usage if our TAP adapter is also used for other purposes?

I initially thought that Nebula would create a new network adapter for its purposes; that would also work if it's doable.

**Comment by alexvy86** [comment]
I took a look at the code and it seems it might be possible to at least specify which of the existing TAP adapters to use, [here](https://github.com/slackhq/nebula/blob/master/tun_windows.go#L35-L40)... The code for `[water](https://github.com/songgao/water/blob/master/params_windows.go)` says that the `InterfaceName` property of `PlatformSpecificParams ` can be used to identify a particular adapter, so maybe in Windows that's where the value of `tun:dev` from the YAML configuration should be used?

IMO creating a new adapter would be ideal, so as not to mess up with any configuration that might already exist. But the option to select a particular adapter to bind to, would be a nice first step.

**Comment by rawdigits** [comment]
See also #116, which would change this entirely, I believe.

**Comment by nbrownus** [comment]
This should no longer be an issue as we have moved to the wintun driver
