### ISSUE TITLE
what does "Prevented a handshake race" mean/imply?

### ISSUE THREAD

**Issue by bmullan** [slackhq/nebula#160]
I have nebula configured on 2 KVM VMs on the same server node1 and node2

My lighthouse is on a cloud server.

I start the lighthouse ok
I start Node1 ok and lighthouse shows it connecting ok

But I start Node2 and on the Lighthouse I see the following:

INFO[0252] **Prevented a handshake race**                    handshake="map[stage:1 style:ix_psk0]" initiatorIndex=2241835118 remoteIndex=0 responderIndex=2441061689 udpAddr="45.37.56.251:4242" vpnIp=10.0.1.2

What does **Prevented a handshake race** mean/imply ??

Is Nebula confused because **VM Node1** and **VM Node2** connection requests are coming from the **same** physical machine that hosts those VMs ?

**Comment by nbrownus** [comment]
It means that both nodes are attempting to handshake with each other, as initiators, at the same time. Usually this occurs on a high latency link, but it can also happen in low latency networks if both nodes try to initiate a handshake at the same moment, or if you restart one side and trigger a handshake. Nebula sorts this out though, the log lines are for informational purposes.
