### ISSUE TITLE
is this all "$ nebula -help" is supposted to display?

### ISSUE THREAD

**Issue by bmullan** [slackhq/nebula#161]
In the help _it seems to indicate_ there might be other command line options?

But is this all its supposed to display?

$ **nebula -help**
Usage of nebula:
  -config string
    	Path to either a file or directory to load configuration from
  **_-help
    	Print command line usage_**
  -test
    	Test the config and print the end result. Non zero exit indicates a faulty config
  -version
    	Print version

**Comment by nbrownus** [comment]
Yep. `-config`, `-test`, `-version`, and `-help` are it.
