### ISSUE TITLE
Anything about this Government alert to VPN vendors affect Nebula?

### ISSUE THREAD

**Issue by bmullan** [slackhq/nebula#164]
The article describes [the Government alert](https://www.forbes.com/sites/daveywinder/2020/01/13/us-government-critical-security-alert-upgrade-vpn-or-expect-continued-cyber-attacks/#16dec99a6f70) and the fact that over 7 vpn vendors were shown vulnerable.

**Comment by rawdigits** [comment]
Nope, entirely unrelated. Btw, I recommend joining the Slack Group we set up for nebula discussions for questions like this: https://join.slack.com/t/nebulaoss/shared_invite/enQtODY1OTg4MDkwMDM0LWI0ZmI5NDMxOTI2OGM5NzVhYjQxOTZlY2U1NWJlMDhkODJkYThhN2VkMTJjMGEzZjM5Y2YxMDhmYWMxNWE3YmY
