### ISSUE TITLE
Nebula "unsafe route" processing fatal error trying to set 1300 MTU on Interface that is already set to 1300 MTU?

### ISSUE THREAD

**Issue by bmullan** [slackhq/nebula#173]
I have configured a lighthouse and 3 nodes (node1, node2, node3)

On each Node I have LXD containers.   I will use Node1 to describe the problem/bug

There is an LXD managed bridge interface I created called **t1-br** that is the interface from the
Host/Server to a Container 
t1-br IP address is:  10.0.2.1
  container CN1 is:  10.0.2.23

In my Node's Nebula config file (/etc/nebula/config.yml) 

> \# NOTE: The nebula certificate of the "via" node *MUST* have the "route" defined as a subnet in its certificate
>   unsafe_routes:
>     - route: 10.0.2.0/24
>       via: 10.0.254.1
> \#      mtu: 1300 

Note1 : I commented out the MTU statement above

Note2: 10.0.254.1 is the IP address for this Node's Nebula interface as configured in its Cert

When I execute:

$ **sudo nebula -config /etc/nebula/config.yml** I see the following (error is highlighted):

> $ sudo nebula -config /etc/nebula/config.yml
> INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:outgoing endPort:0 groups:[] host:any ip:<nil> proto:0 startPort:0]"
> INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host:any ip:<nil> proto:1 startPort:0]"
> INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:incoming endPort:443 groups:[any] host: ip:<nil> proto:6 startPort:443]"
> INFO[0000] Firewall started                              firewallHash=c870c0375cbc7304f60e31f373d76b6eb281a9994cae22630ab1c2d97c73207a
> WARN[0000] Adding UNSAFE Route                           route=10.0.2.0/24 via=10.0.254.1
> INFO[0000] Main HostMap created                          network=10.0.254.1/24 preferredRanges="[]"
> INFO[0000] UDP hole punching enabled                    
> **FATA[0000] failed to set mtu 0 on route 10.0.2.0/24; file exists** 

I am trying to have Nebula route the subnet that my LXD containers are on (10.0.2.0/24).

I already have the LXD Bridge Interface **t1-br** (IP 10.0.2.1) and I configured it for an MTU
of only 1300

So in Nebula "unsafe_routes" processing its dying because Nebula can't set the MTU complaining that the "_**file exists**_.

**It tries to set the MTU despite the fact that the 10.0.2.1 t1-br interface was already set to 1300**

This Node's  IP ROUTE (partial):

> $ ip route
> default via 64.227.0.1 dev eth0 proto static 
> **10.0.2.0/24 dev t1-br proto kernel scope link src 10.0.2.1**

**Comment by nbrownus** [comment]
#209 should resolve this issue I believe

**Comment by bubbyd** [comment]
I have just encounterd this same fatal error (173) unsafe route MTU set to 1300. 

I have tried Debian 11 Bullseye and Ubuntu 22.04 server editions to allow access to other systems on the LAN 
via unsafe route. I have done all of the things that bmullan had done; to no avail. 

FATA[0000] failed to set mtu 0 on route 192.168.14.0/24; file exists
