### ISSUE TITLE
FATA[0000] Activate failed: error in syscall.RawSyscall(syscall.SYS_CONNECT, ...): operation not permitted

### ISSUE THREAD

**Issue by goedym** [slackhq/nebula#174]
I'm trying to get this running in MacOS Catalina.  When I try running it manually, this is the result:
./nebula -config config.node.yaml
INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:outgoing endPort:0 groups:[] host:any ip:<nil> proto:0 startPort:0]"
INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host:any ip:<nil> proto:0 startPort:0]"
INFO[0000] Firewall started                              firewallHash=0b03f21d896ea52a717719ed2530c566ea6c212951db0441b4d8c04f5f15dd09
INFO[0000] Main HostMap created                          network=192.168.3.2/24 preferredRanges="[]"
INFO[0000] UDP hole punching enabled
FATA[0000] Activate failed: error in syscall.RawSyscall(syscall.SYS_CONNECT, ...): operation not permitted

I already have it successfully running on two Ubuntu nodes.  Followed the same steps here, so I'm surprised to have the issue.

**Comment by nbrownus** [comment]
Are you running as root or your own user?

**Comment by goedym** [comment]
My bad.  I thought I'd tried it as root, but clearly I didn't.  That works.  I'm still trouble getting it started as a service, but that's clearly another issue.
