### ISSUE TITLE
Nebula Routing Question

### ISSUE THREAD

**Issue by mikfra** [slackhq/nebula#182]
I had a general question in regards to how nebula routes traffics between three nodes with two nodes that cannot access each other. 

For instance:
node1:
- IP: 10.10.10.1
- DENY ALL FIREWALL
- ALLOW 10.10.10.3

node2:
- IP: 10.10.10.2
- DENY ALL FIREWALL
- ALLOW 10.10.10.3

node3:
- IP: 10.10.10.3
- DENY ALL
- ALLOW 10.10.10.0/24

Will nebula route traffic through node 3 between nodes 1 and 2 without additional network configuration? I.E. port-forwarding on node 3

**Comment by sachTom** [comment]
I don't think so, you'll have to configure node 3 to forward traffic 1->2 and vice versa.
