### ISSUE TITLE
Nebula lighthouse in different subnet causes issues with latest build

### ISSUE THREAD

**Issue by GettingTechnicl** [slackhq/nebula#185]
I use a 128 ip range, class B network with a /17 subnet. 

I have my lighthouses in their own subnet purposefully. I'm wondering if I can bypass this check of verifying the lighthouse in the current subnet, as that is not something I want. Thank you

**Comment by nbrownus** [comment]
In our current state `nebula` needs a route via nebula to the lighthouses. If they exist in different islands then a client node can't communicate with the lighthouse.
