### ISSUE TITLE
Minor: use /usr/local/sbin for nebula binary

### ISSUE THREAD

**Issue by jkrauska** [slackhq/nebula#19]
since nebula seems to require to be run as root, it may make sense to standardize on /usr/local/sbin for the binaries? (As references in service scripts and ansible)

**Comment by rawdigits** [comment]
I expect package maintainers for different distributions will decide on their own, but we'll think about changing it in our official docs as we work through them. Documentation needs to brought up to snuff in general. Thanks for the suggestion!
