### ISSUE TITLE
Error when starting nebula on CentOS7

### ISSUE THREAD

**Issue by dampfhamm3r** [slackhq/nebula#194]
When trying to start Nebula on a CentOS7 server, I get the following error:

```
﻿﻿ERRO[0000] failed to discover udp listening address      error="function not implemented"
ERRO[0000] Failed to send handshake message              error="sendto: function not implemented" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1460770442 remoteIndex=0 udpAddr="lighthouse-public-ip:4242" vpnIp=10.81.0.1
ERRO[0000] Failed to send handshake message              error="sendto: function not implemented" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1460770442 remoteIndex=0 udpAddr="lighthouse-public-ip:4242" vpnIp=10.81.0.1
```

While the error pops up, I've checked if the nebula interface appears and if I see a listening port. This seemed to be ok:

```
[root@servername ~]# ifconfig nebula1 && netstat -tulpen | grep 4242
nebula1: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1300
        inet 10.81.0.30  netmask 255.255.255.0  destination 10.81.0.30
        inet6 fe80::3df:fd1a:646d:95b0  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3  bytes 144 (144.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

udp        0      0 0.0.0.0:4242            0.0.0.0:*                           0          5363109    27342/./nebula
```

CentOS release:
7.7.1908 (Core)

Kernel:
Linux 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nbrownus** [comment]
We are all a tad confused as the required syscalls (`sendto` and `getsockname`) should exist in your kernel. 

That said:
1. 3.10 is quite old and no longer supported by the as of a few years ago [kernel team](https://www.linux.com/news/linux-kernel-310-reached-end-life-users-are-urged-move-linux-44-lts-1/)
2. Can you describe more of your environment a bit more, it seems something (maybe selinux?) is getting in the way

**Comment by dampfhamm3r** [comment]
I know that CentOS is always a bit slow with updating to new releases. As you said, it seems really only to be related to the mentioned kernel version.
The server was installed with the 'minimal' installation ISO.
Also, for testing purposes firewalld and selinux is disabled.
Another test with CentOS8 was successfull.
