### ISSUE TITLE
How to change from AES?

### ISSUE THREAD

**Issue by obelisk** [slackhq/nebula#20]
At your talk it was said to avoid using AES-256-GCM if you'll be adding ARMv7 devices to the network because it will result in extremely poor performance on them due to the lack of hardware accelerated AES. The recommendation was to use keccak but how does one configure that in Nebula?

**Comment by rawdigits** [comment]
In the config.yaml, set the option:

```cipher: chachapoly```

note: you must do this for ALL nodes using a particular nebula network. Mixed mode is not supported.

**Comment by obelisk** [comment]
Thanks so much!
