### ISSUE TITLE
V1.1 nebula-linux-mips Fails with Illegal Instruction on OpenWrt (SOLVED)

### ISSUE THREAD

**Issue by fghorow** [slackhq/nebula#201]
I just attempted to execute the binary packaged at https://github.com/slackhq/nebula/releases/download/v1.1.0/nebula-linux-mips.tar.gz on an OpenWrt MIPS 24kc architecture machine.

As stated in the title, it immediately failed with an error message of "Illegal Instruction". The machine is confirmed via `lscpu` to be a Big-Endian configuration.
 
My deep suspicion, having previously seen this error message only upon trying to boot Debian on OpenWrt boxes, is that the nebula binary requires either hardware FPU instructions, or the kernel to be compiled with SoftFPU. The distribution OpenWrt kernels for MIPS 24kc are not compiled with SoftFPU.

If my suspicion is correct -- something which would take me a significant amount of time to verify -- the only workaround I know of requires setting up an OpenWrt cross-compilation chain and building the whole thing from source.  

Is there some way to avoid emitting FPU instructions in nebula binaries? That *might* be a quicker way to check my suspicion...

In any case, I'm submitting this issue so future OpenWrt users can see that this is a known issue.

**Comment by fghorow** [comment]
OK. I can confirm that the issue was a lack of soft-float support.

Current workaround to get a working nebula executable (tested under Ubuntu 19.10 cross-compilation, with its go1.13.1 package installed and configured to be the default go compiler):

1.  clone the nebula source from this repo.

3.  set these environment variables:
`GOOS=linux
 GOARCH=mips
 GOMIPS=softfloat`
  That last variable is NOT set by default in the nebula build environment.

10. compile:
`go build -trimpath -ldflags "-s -w" -o ./nebula "./cmd/nebula"`
I am no expert on the go build system. Those `-s -v` flags produce a stripped binary. Perhaps there is also some other state created by previous compilation attempts that affected my results. YMMV. The resulting binary is in `./nebula`

11. (optional) compress the executable:
`upx nebula` 
I needed to do this in order to fit onto my router's (very) limited storage space. Again, YMMV.

Once those steps are done on my Ubuntu box, I copied the executable over to my router and executed it. Instead of complaining about an instruction error, it now presents me with the `usage` information, which I take as evidence of a successful "hello world".

Hope this helps somebody else!

**Comment by wadey** [comment]
Thanks for giving details on how to make it work! I'll look into having the release process build a `mips-softfloat` binary.

Have you tested actually running with a config file and seeing if it can connect to other hosts and route traffic?

**Comment by fghorow** [comment]
Hi Wade,

The executable ran, but connection failed for some reason or other. (I can’t remember details. It was aeons ago, “pre-Covid-19”.)

Can I please ask you to check this out for yourselves? I am sorry, but I am 100% committed in time to 3D printing face shields for medical personnel right now for the Covid-19 emergency in NYC.

Sorry I couldn’t be more help right this instant!

Frank Horowitz


> On Apr 2, 2020, at 10:41 AM, Wade Simmons <notifications@github.com> wrote:
> 
> 
> Thanks for giving details on how to make it work! I'll look into having the release process build a mips-softfloat binary.
> 
> Have you tested actually running with a config file and seeing if it can connect to other hosts and route traffic?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Frank Horowitz
frank@horow.net

**Comment by wadey** [comment]
Thanks Frank! I don't have a mips device with OpenWRT, so I don't have a good way to test this out. Perhaps when you have time again in the future we can work with you to debug this and get it all working, but obviously no rush. Take Care :+1:

**Comment by fghorow** [comment]
Would it help if I shipped you an old OpenWRT compatible MIPS device?

I have several laying around gathering dust…

Frank


> On Apr 2, 2020, at 10:59 AM, Wade Simmons <notifications@github.com> wrote:
> 
> 
> Thanks Frank! I don't have a mips device with OpenWRT, so I don't have a good way to test this out. Perhaps when you have time again in the future we can work with you to debug this and get it all working, but obviously no rush. Take Care 👍
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Frank Horowitz
frank@horow.net
