### ISSUE TITLE
does nebula support socks5 port forward

### ISSUE THREAD

**Issue by billzhuang** [slackhq/nebula#203]
there is a socks5 proxy listen on 0.0.0.0:1086 in client A, and i set in client A's config file
```
    # Allow socks proxy between any nebula hosts
    - port: 1086
      proto: any
      host: any
```
i still can not connect to client A's 1086 port, no matter in other clients or lighthouse. any idea

normal tcp ports looks good in nebula network

**Comment by billzhuang** [comment]
> there is a socks5 proxy listen on 0.0.0.0:1086 in client A, and i set in client A's config file
> 
> ```
>     # Allow socks proxy between any nebula hosts
>     - port: 1086
>       proto: any
>       host: any
> ```
> 
> i still can not connect to client A's 1086 port, no matter in other clients or lighthouse. any idea
> 
> normal tcp ports looks good in nebula network

**Comment by billzhuang** [comment]
after post the issue, just find it works. 
sorry for the consufe.

**Comment by nbrownus** [comment]
Just tested with `danted` as a SOCKS5 server and all is working. I'd check your SOCKS server configuration.
