### ISSUE TITLE
Feature Request: Route traffic through other nodes like Tinc VPN.

### ISSUE THREAD

**Issue by breisig** [slackhq/nebula#218]
Nebula looks like a great VPN but one great feature that is missing is being able to automatically route traffic through other nodes in case each node is not able to talk directly to each other like Tinc VPN does. This is a VERY powerful mesh feature that has allowed for greater high availability in case network traffic between two nodes directly get blocked or becomes erratic that Tinc is able to re-route the traffic through different nodes. If Nebula supported this feature then most Tinc users [like myself] would switch over to Nebula.

**Comment by cg31** [comment]
This PR is for an opposite request... but I think it can also satisfy your request:
https://github.com/slackhq/nebula/pull/217

**Comment by coderobe** [comment]
That PR appears unrelated.

I would also like to see this, as it provides an efficient failover method should some routes break.

**Comment by TheTyrius** [comment]
Somewhat related to #204. I believe this is being worked on (see also rawdigits' comments on #33 ).

**Comment by breisig** [comment]
Having traffic being able to re-route through the lighthouse is a first step but to be feature complete like Tinc, traffic should also be able to be re-routed through other nodes in case the lighthouse isn't available/reachable. [even to make it a toggle able feature]

**Comment by tarrenj** [comment]
> Having traffic being able to re-route through the lighthouse is a first step but to be feature complete like Tinc, traffic should also be able to be re-routed through other nodes in case the lighthouse isn't available/reachable. [even to make it a toggle able feature]

I agree that a full dynamic routing solution would be the real solution here. I think figuring out a way to let the user configure that wholly independently and have it "peer" over the Nebula interfaces. The issue with this is that traffic would have to be decrypted by nebula, go through the kernel routing table, and finally reenter the Nebula overlay at each hop. I _think_ Nebula could pull the routes in and route the traffic directly (even if the intermediary node is not in the proper Security Group), but I'm not sure.

Also see these:
https://github.com/slackhq/nebula/issues/204#issuecomment-999035177
https://github.com/slackhq/nebula/issues/274

**Comment by falshunov** [comment]
> If handling the routing directly within Nebula is preferred, I (currently) recommend [BATMAN](https://en.wikipedia.org/wiki/B.A.T.M.A.N.) routing.
@tarrenj 

It is not working because:
If use batman over l2 you must have mac-address on the tunnel interface.
If use batman over l3 you must have a broadcast address on the tunnel interface.

Nebula proto doesn't have it both. 
Very sadly but ospf+mpls(?)+ip_sla(soft) = routing by low latency and short path via nebula.

**Comment by tarrenj** [comment]
@falshunov Thanks for the extra info! I haven't had time to actually test myself yet, so that's very helpful.

**Comment by brad-defined** [comment]
Nebula 1.6.0 is released with a Relay feature, to cover cases like a Symmetric NAT.
https://github.com/slackhq/nebula/pull/678

Check out the example config to see how to configure a Nebula node to act as a relay, and how to configure other nodes to identify which Relay can be used by peers for access.

**Comment by JohnMaguire** [comment]
Due to the release of the relay feature, I'm going to close this issue out as solved. If you're continuing to experience connectivity issues, please feel free to open up a new issue or [join us on Slack](https://join.slack.com/t/nebulaoss/shared_invite/enQtOTA5MDI4NDg3MTg4LTkwY2EwNTI4NzQyMzc0M2ZlODBjNWI3NTY1MzhiOThiMmZlZjVkMTI0NGY4YTMyNjUwMWEyNzNkZTJmYzQxOGU). Thanks!
