### ISSUE TITLE
Tip about client side DNS or script call

### ISSUE THREAD

**Issue by windwalker78** [slackhq/nebula#237]
Hello,

   I'm experimenting a lot recently and besides the bug with DNS name in static_host_map not working 100%, I find nebula really cool.
  I know updating resolv.conf on clients is not supported and I cannot push name servers, but is there any option or trick to call a script on tunnel up/down?
   I guess adjusting the systemd service parameters will work this around, but I prefer to do it if possible via nebula binary.

Regards

**Comment by sahoahfoa** [comment]
I'd love for this to be a feature. I currently run a resolver on my lighthouse and it would be great to configure my nodes to use it for look-ups.

**Comment by JohnMaguire** [comment]
Hi all. We appreciate the interest in this feature but would prefer to keep the surface area of nebula low. We think that this use case is best solved through the use of systemd (i.e. [`ExecStartPre=` and `ExecStartPost=`](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStartPre=)) or a Bash wrapper script.
