### ISSUE TITLE
macOS Release Binaries Aren't Signed

### ISSUE THREAD

**Issue by obelisk** [slackhq/nebula#24]
macOS binaries should be signed to prevent tampering and eventually to notify gatekeeper that it is allowed to run.

**Comment by rawdigits** [comment]
Now to learn about signing in OSX.... 
Step 1: find a mac

**Comment by Yafsec** [comment]
For people having problems running the nebula binary on OSX for now:

-Select the nebula binary from within finder
-Press [control] and click the binary
-select open
-accept the warning and run the binary once

After this you can run it from the terminal without errors

**Comment by RoelWKramer** [comment]
Since both binaries are command line utils, you can also remove them from quarantine:

`xattr -d com.apple.quarantine ~/bin/nebula-cert`

`xattr -d com.apple.quarantine ~/bin/nebula`

**Comment by uluckas** [comment]
@RoelWKramer thanks, works like a charm but disables a security layer.

Therefor executable signing is still an important feature request.

**Comment by Tycho-S** [comment]
This is especially important in corporate environments where gatekeeper (only run signed apps) is mandatory. It would really be great if they could be codesigned.

Slack's Mac app is signed properly (albeit using the tinyspeck.com signature, not slack's own) so the knowledge and keys/Apple subscription are all there :)
