### ISSUE TITLE
Any idea if add quic or fake tcp to make better connection?

### ISSUE THREAD

**Issue by butterl** [slackhq/nebula#242]
Hi,  
Since some times ISP or some router node will make QoS or limit to udp connection (as for wireguard，the connection lost within minute),  and a fake tcp header will make it better connection to override. 

Also Google's  Fuchsia  have a mesh networking service called overnet, which change from a udp connectin to quic（not know if same issue as I meet in wireguard）

if there is a chance to make a quic of fake tcp way for the UDP QoS ?

**Comment by xiaolei0125** [comment]
Since many ISP make QoS for UDP or drop UDP connection , Can Nebula support to use TCP as  an option to support more network environments？

I know TCP protocol is not suitable for  for NAT punch，but we can use lighthouse to relay forwarding traffic. Thanks.
