### ISSUE TITLE
Imprecise error messages

### ISSUE THREAD

**Issue by coderobe** [slackhq/nebula#26]
Running `nebula -config /this/doesnt/exist` or `nebula -config /no/read/permissions` (nonexistent path and unreadable file, respectively) results in
```
FATA[0000] no pki.ca path or PEM data provided          
```

While generally correct, i suppose, this should maybe point out that the config file could not be found or read.

**Comment by nbrownus** [comment]
Thanks for reporting!

**Comment by target-drone** [comment]
Perhaps also a note or emphasis in the docs that the config file _must_ end in .yaml or you get this unhelpful error message.  
Or a change to remove the file extension restriction.

**Comment by nbrownus** [comment]
@target-drone `.yaml` or `.yml` are both fine as an extension. The reason a specific extension is required is because we will traverse a directory tree if you point your `-config` at one. The error should also be much more clear on master and soon to be `v1.1.0`

**Comment by wadey** [comment]
#189 is a PR to not require the .yml or .yaml file extension if you point `-config` directly at a file instead of a folder.
