### ISSUE TITLE
FATA[0001] no such device 

### ISSUE THREAD

**Issue by msmarks** [slackhq/nebula#27]
I am run nebula in Raspberry Pi 1 Model B+, `sudo ./nebula -config config.yaml` But it says `FATA[0001] no such device`. Is it mean it fail to create tun dev?

**Comment by nbrownus** [comment]
@msmarks can you give us more of the log output?

**Comment by obelisk** [comment]
I had this problem when I tried to run on Arch, using Ubuntu worked fine so I think this is a problem with how some operating systems create tun interfaces.

**Comment by obelisk** [comment]
@nbrownus When I got this there was no other output, is there a verbose mode I could try?

**Comment by zeisss** [comment]
@obelisk you can set the loglevel to debug in the `config.yml` file.

**Comment by coderobe** [comment]
@obelisk It's got nothing to do with Arch directly. I'm running it just fine on there.

**Comment by obelisk** [comment]
I will grab some logs and report back!

**Comment by obelisk** [comment]
Changing to debug resulted in no new log lines related to `FATA[0000] no such device`

**Comment by obelisk** [comment]
Fixed by:
```
pacman -Syu
<reboot>
modprobe tun
nebula -config /etc/nebula/config.yml
```

**Comment by rawdigits** [comment]
I wonder if the tun device is not loaded automagically on arch.
Mind trying `modprobe -a tun` and then running again?

**Comment by coderobe** [comment]
The tun driver is loaded automagically on Arch.
However, users upgrading their system might prevent that from happening - when the upgrade pulls in a newer kernel, the old modules for the running kernel are discarded.
Given that a reboot was part of the issue resolution, this very well could've been what happened.

**Comment by obelisk** [comment]
@coderobe That seems likely because I'd done a `pacman -Syu` about an hour before I tried to use Nebula which probably updated the kernel.

**Comment by nbrownus** [comment]
Next release will have an improved error message for this, thanks for reporting!
