### ISSUE TITLE
Feature Request: Support to resolve lighthouse domain name(DDNS) when reconnect or connect failed

### ISSUE THREAD

**Issue by xiaolei0125** [slackhq/nebula#273]
My lighthouse used a public ip but not fixed,  ip changed every day, so I used a  domain name(support DDNS) in static_host_map;
`static_host_map:
  "192.168.10.1": ["lh1-nb.myddns.top:4242"]`

When nebula start,  can get correct lighthouse ip and work well,  but when my lighthouse public ip changed, other nebula node lost connecttion with lighthouse, since  nebula still used old lighthouse ip to connecting, so connecting failed.

Is possible to resolve lighthouse domain name again when reconnect or connect failed ?

**Comment by xiaolei0125** [comment]
same feature as [#294 ](url)

**Comment by aa51513** [comment]
What is the latest status of this issue?

If you are worried that the dns resolution result contains multiple IP addresses, you can directly select the first one, which is better than doing nothing, isn't it?

**Comment by JohnMaguire** [comment]
Hi all - I just wanted to drop a quick comment to mention that the fix from #796 was released in v1.7.0. We found a bug in the behavior there and quickly pushed out v1.7.1 which should re-query domains in the `static_host_map`. Please give it a shot and let us know what you think!
