### ISSUE TITLE
[android] Failed to get a tun/tap device    

### ISSUE THREAD

**Issue by iCodZilla** [slackhq/nebula#291]
I use a linux-arm64 version file on Android device. it failed with the error message like below

```
FATA[0000] Failed to get a tun/tap device                error="no such file or directory"
```

I found the error cames from main.go  (abround line 120)

```golang

// here, err is nil 
tun, err = newTun(
    config.GetString("tun.dev", ""),
 		tunCidr,
 		config.GetInt("tun.mtu", DEFAULT_MTU),
 		routes,
 		unsafeRoutes,
 		config.GetInt("tun.tx_queue", 500),
)
// here, err is "no such file or directory",  
// but newTun not runs at all, cause I put a panic log inside it and it not triggerd
```

after newTun returns, the err value became what I found on Android device. but when I insert a panic inside newTun function, 
it did not run into it. so, where is the "err" message came from? this make me confused :(

I must do something wrong or misunderstand something, so, anyone can give me some help?

**Comment by nbrownus** [comment]
Android works by pre allocating a tun device and handing the file descriptor to nebula. We have an android client currently in beta, join the slack group and head over to #android if you want to test it.

**Comment by iCodZilla** [comment]
from android cpp source code, it create tun interface like below, newTun (Linux) function almost does the same thing, but on Android, the original tun interface path is "/dev/tun" not "/dev/net/tun", so I modified the source file to Android version

here is the c++ source code from Android system:
```c
static int create_interface(int mtu)
{
    int tun = open("/dev/tun", O_RDWR | O_NONBLOCK);

    ifreq ifr4;
    memset(&ifr4, 0, sizeof(ifr4));

    // Allocate interface.
    ifr4.ifr_flags = IFF_TUN | IFF_NO_PI;
    if (ioctl(tun, TUNSETIFF, &ifr4)) {
        ALOGE("Cannot allocate TUN: %s", strerror(errno));
        goto error;
    }

    // Activate interface.
    ifr4.ifr_flags = IFF_UP;
    if (ioctl(inet4, SIOCSIFFLAGS, &ifr4)) {
        ALOGE("Cannot activate %s: %s", ifr4.ifr_name, strerror(errno));
        goto error;
    }

    // Set MTU if it is specified.
    ifr4.ifr_mtu = mtu;
    if (mtu > 0 && ioctl(inet4, SIOCSIFMTU, &ifr4)) {
        ALOGE("Cannot set MTU on %s: %s", ifr4.ifr_name, strerror(errno));
        goto error;
    }

    return tun;

error:
    close(tun);
    return SYSTEM_ERROR;
}

```

here is my modificated newTun version, just simply replace "/dev/net/tun" with "/dev/tun":
```golang
func newTun(deviceName string, cidr *net.IPNet, defaultMTU int, routes []route, unsafeRoutes []route, txQueueLen int) (ifce *Tun, err error) {
	fd, err := unix.Open("/dev/tun", os.O_RDWR, 0)
	if err != nil {
		return nil, err
	}

	var req ifReq
	req.Flags = uint16(cIFF_TUN | cIFF_NO_PI)
	copy(req.Name[:], deviceName)
	if err = ioctl(uintptr(fd), uintptr(unix.TUNSETIFF), uintptr(unsafe.Pointer(&req))); err != nil {
		return
	}
	name := strings.Trim(string(req.Name[:]), "\x00")

	file := os.NewFile(uintptr(fd), "/dev/tun")

	maxMTU := defaultMTU
	for _, r := range routes {
		if r.mtu > maxMTU {
			maxMTU = r.mtu
		}
	}

	ifce = &Tun{
		ReadWriteCloser: file,
		fd:              int(file.Fd()),
		Device:          name,
		Cidr:            cidr,
		MaxMTU:          maxMTU,
		DefaultMTU:      defaultMTU,
		TXQueueLen:      txQueueLen,
		Routes:          routes,
		UnsafeRoutes:    unsafeRoutes,
	}
	return
}
```

`ip addr show tun0` shows the interface is UNKNOWN

```shell
tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1300 qdisc pfifo_fast state UNKNOWN qlen 500
link/none
inet 192.168.166.8/24 scope global tun0
valid_lft forever preferred_lft forever
```
but the start scripts says Neblula interface is active: 
```
INFO[0000] Nebula interface is active                    build=dev+20200829084140 interface=tun0 network=192.168.166.8/24 udpAddr="0.0.0.0:4242"
```
I can't ping on each node, there must be something wrong with my modification,  would you please show me some advice?

**Comment by nbrownus** [comment]
You need to establish the `tun` device with the android specific APIs. https://developer.android.com/reference/android/net/VpnService.Builder

**Comment by iCodZilla** [comment]
build Nebula as an library, create a VPN service, then handle file descriptor to Nebula, finally it works, thanks for your great help @nbrownus
