### ISSUE TITLE
blocklist best practices

### ISSUE THREAD

**Issue by DarkArc** [slackhq/nebula#304]
Hi, this is a really cool project and some really cool technology.

I was wondering what the best practices are surrounding the blocklist. A couple of questions in particular come to mind in the situation of revoking a _certificate X_:'
1. Do all nodes need to include in their blocklist the fingerprint of _certification X_, or is it sufficient to apply this to lighthouses only?
2. Are there any suggested means for synchronizing the blocklist between different nodes?

I'm primarily curious how this plays out if a node Y is compromised, and you need to get it out of the network as fast as possible; what do you need to do, and how do you reduce/remove the opportunity for human error?

**Comment by junky89** [comment]
Hi, I'm also interested on this question. I can't find how to deal with compromised nodes. And if the primary key is compromised? it's possible to rotate certificate without a network restart?

**Comment by nbrownus** [comment]
> Do all nodes need to include in their blocklist the fingerprint of certification X, or is it sufficient to apply this to lighthouses only?

I would err on the side of yes, all hosts need the set of fingerprints you deem compromised, until the certificate expires. You can do this only at the lighthouse but it will not impact any existing tunnels in your mesh to that compromised host.

> Are there any suggested means for synchronizing the blocklist between different nodes?

I would recommend using you config management stack or a system like `consul` or `zookeeper` depending on your requirements. How quickly do you need to react? What infrastructure exists under your control today? What is your threat model?

> And if the primary key is compromised? 

I am assuming "primary key" here is talking about the root CA key. You can trust multiple roots at the same time. Ideally you would trust at least 2. 1 root that is currently signing certificates and 1 that is stored offline and used for a "break glass" type of scenario where your 1st root is compromised. You can switch to signing with that 2nd root, re-issue certs to your mesh, and drop the compromised root from your set of trusted root certificates.

> it's possible to rotate certificate without a network restart?

It is, a `SIGHUP` will trigger `nebula` to re-read the configuration file. Trusted root certs, the nodes cert, and private key will be re-loaded in memory. Not every config directive reacts to a reload but many of them do, and we have a task to update that list.

**Comment by DarkArc** [comment]
Thanks for the response. For now this is primarily for personal use so my threat model is rather tame. It's good to know these things in case a laptop gets stolen, or in discussing deploying this to more widespread infrastructure than my home + some installations on elderly relatives machines. :)

It might be nice if there was a simpler solution, for instance, the ability to point to a blocklist server with a configurable synchronization time, that manages the list of blocked certificates. It seems that could be handy for both casual and corporate configurations alike.

**Comment by JohnMaguire** [comment]
I've gone ahead and added a note on how to update the blocklist here: https://nebula.defined.net/docs/config/pki/#pkiblocklist

I think the question of how to ease blocklist distribution is a good one, but it probably goes hand-in-hand with tickets like #479 which address config distribution. Currently this is considered out of scope of the Nebula project.
