### ISSUE TITLE
FreeBSD requires tunX

### ISSUE THREAD

**Issue by jradxl** [slackhq/nebula#309]
It seems that FreeBSD requires tunX, and trying neb1 causes this error message:-

Nebula Error Message:
ERRO[0000] Failed to get a tun/tap device                error="tun.dev must match `tun[0-9]+`"

Having spent some hours configuring up Nebula within OPNsense, alas I'm defeated at the last step as the OPNsense webUI prevents tunX from appearing.
I've tried renaming an existing interface, ifconfig neb2 name tun2, but that doesn't solve issue.

Is there a work-around?
Can the restriction be removed, because then there could be a OPNsense Plugin!!
Thanks

**Comment by wadey** [comment]
It looks like this is possible with FreeBSD, but not straight forward (you have to create the device and then rename it). Some prior art for how we can implement this in the future: https://github.com/pkg/taptun/pull/7

**Comment by litecactus** [comment]
I too have run into the same issue - nothing more to add though.

**Comment by gabeio** [comment]
I managed to get passed that error by changing the value in the nebula config.yaml to match that regex `tun###`.

https://github.com/slackhq/nebula/blob/20bef975cd8dc0c9cc729a49565c0f481ebe41b9/examples/quickstart-vagrant/ansible/roles/nebula/templates/config.yml.j2#L52

**Comment by noseshimself** [comment]
Temporary solution: Launch nebula on FreeBSD-based systems via /usr/local/etc/rc.d:

```
#!/usr/local/bin/bash

# PROVIDE: nebula
# REQUIRE: NETWORKING
# KEYWORD: shutdown
#
# nebula_enable (bool): Set to "YES" to enable wireguard.  (default: "NO")
#

. /etc/rc.subr

name=`basename $0`
rcvar=nebula_enable
confname="/${name}_config.yml"
confdir="/usr/local/nebula/etc"
pidfile="/var/run/${name}.pid"

extra_commands="restart"      

start_cmd="nebula_start"
stop_cmd="nebula_stop"
restart_cmd="nebula_restart"
#status_cmd="nebula_status"


nebula_start()
{
  (/usr/local/nebula/bin/nebula -config $confdir/$confname 2>&1 & echo $! > ${pidfile}) | logger -t ${name} &

  logger -t ${name} "launching ${name} with PID $!"

  ifrename=${name}_rename_interface 
  if checkyesno ${ifrename} ; then
    (
      sleep 5
      old=${name}_source_interface 
      new=${name}_target_interface
      ifconfig ${!old} name ${!new} > /dev/null
      logger -t ${name} "renaming ${!old} to ${!new}"
    ) &
  fi
}

nebula_stop()
{
  if [ -f "$pidfile" ] ; then
    kill `cat ${pidfile}`
    rm ${pidfile}
    if checkyesno ${name}_rename_interface ; then
      new=${name}_target_interface
      ifconfig ${!new} destroy
    fi
  fi
}

nebula_restart()
{
  run_rc_command "stop"
  run_rc_command "start"
}


# echo `date` " nebula-startup is running for ${name}"} >> /root/nebula-debug.txt

load_rc_config nebula

: ${nebula_enable="NO"}

run_rc_command "$1"
```

/etc/rc.conf.d/nebula
```
nebula_enable="YES"
nebula_rename_interface="YES"
nebula_source_interface="tun-whatever-you-put-into-the-config.yml"
nebula_target_interface="nebula0"
root@router:/etc # 
```
