### ISSUE TITLE
Ownership status of implementations

### ISSUE THREAD

**Issue by ETCaton** [slackhq/nebula#315]
The README links to [Mobile Nebula](https://apps.apple.com/us/app/mobile-nebula/id1509587936) and [Nebula](https://play.google.com/store/apps/details?id=net.defined.mobile_nebula&pcampaignid=pcampaignidMKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1) on the iOS and Google Play store respectively. As far as I can tell, these apps' source code isn't available and they aren't under the Slack brand (instead under [Defined Networking](https://medium.com/definednet)).

Will Slack be putting resources into developing an iOS/Android app, or are Defined Networking's implementations the only planned mobile implementations at this time? Are there any plans to change ownership of/archive this repo?

**Comment by ETCaton** [comment]
Trying to get a better understanding of where Slack/Defined Networking fit into Nebula's future, but I apologize in advance if this issue doesn't follow some guideline 😅

**Comment by nbrownus** [comment]
Slack and Defined Networking are working closely with regards to this repo. The mobile apps are solely being developed by the Defined team at the moment.

The mobile apps are basically glue code, some UI for the nebula configuration file, and massaging for each mobile os to boot the code in this repo.
