### ISSUE TITLE
IPv6 in underlay network

### ISSUE THREAD

**Issue by krombel** [slackhq/nebula#322]
In https://github.com/slackhq/nebula/issues/6#issuecomment-555771624 you mentioned, that you would like to distinguish IPv6-implementation in underlay and overlay-Network and would focus on implementing it for the underlay network first.

How is the situation in this regard? Are there any updates since the linked comment?

I would like to have that feature because of the following use-case which can come in quite handy: In cases I misconfigured my v4-stack but v6 is still fully functional. You might guess why nebula could get useful in this situation 😉 
I can define multiple addresses in [static_host_map](https://github.com/slackhq/nebula/blob/v1.3.0/examples/config.yml#L20) for the lighthouses and would like to do so for IPv4 and IPv6.

For people who might want do have som pointers: My short look at the code reveald [NewListener()](https://github.com/slackhq/nebula/blob/v1.3.0/udp_linux.go#L58-L90) in case of Linux.

Thanks for your work btw!

**Comment by herbetom** [comment]
It's also a must have for IPv6 only servers. Yes, these currently often have IPv4 connectivity via nat (e.g. for accessing GitHub), but I hope that this will eventually no longer be necessary on some of my VMs.

**Comment by kvtb** [comment]
It raises question on how IPv6-only machines would connect IPv4-only machines

**Comment by herbetom** [comment]
I would suggest to simply don't use IPv4-only Hosts. At least in combination with IPv6-only Hosts :wink: 

Otherwise logging the error is probably "enough". 

I don't think Nebula should try to "solve" this. One should probably use dedicated IPv6 transition mechanisms for this.

**Comment by kvtb** [comment]
Yes, there will be a requirement for all the participant to be reachable via either IPv4 or IPv6.
Otherwise, we hit the issue with 2 hosts being unable to make a peering.
There won't be dual stack nebula, but IPv4 nebula (as now) or IPv6 nebula (which is probably useless because total IPv4 connectivity is more common)

**Comment by nbrownus** [comment]
ipv6 support for the physical network is currently implemented in master and will be included in the v1.4.0 release we are planning to cut soon. We have ambitions to enable it within the virtual network as well but I can not speak to when that might land at this time.
