### ISSUE TITLE
Panic due to a slice bounds out of range error inside `Encode` of the `Header` type.

### ISSUE THREAD

**Issue by pventuzelo** [slackhq/nebula#333]
**Summary:**

During the decoding of some specific bytes, the function `Encode` for the `Header` type will trigger a  slice bounds out of range leading to a panic of the complete program/process.

**Description:**

This bug occurs inside `HeaderEncode` at line 96 when the program tried to slice the `b` byte array without checking the size first. Based on the comments, this function is suppose to panic in case of issue since there is not `error` returned by the function. Nevertheless, it make more sense to verify the len of the data inside `func (h *Header) Encode` before calling `HeaderEncode` line 132 like it is done inside the function `Parse` line 137 to 139.
link: https://github.com/slackhq/nebula/blob/43a3988afce2a440bdd83acba4df3e118c9e96d9/header.go#L132

**Potential patch:**
``` golang
if len(b) < HeaderLen {
	return eHeaderTooShort
}
```

## Steps To Reproduce:

STEP 1: create a go project: `mkdir testing; touch main.go; touch go.mod`
STEP 2: `go.mod` content
``` golang
module main

go 1.15

replace github.com/slackhq/nebula => ../

require github.com/slackhq/nebula v0.0.0-00010101000000-000000000000 // indirect


```

STEP 3: `main.go` content

``` golang
package main

import (
	nebula "github.com/slackhq/nebula"
)

func repro_HeaderEncode(){
	data := []byte("\x0a\x0a\x0a\x0a\x0a\x00")
	var out nebula.Header
	_, _ = out.Encode(data)
	// panic: runtime error: slice bounds out of range [:16] with capacity 6
}


func main() {
	repro_HeaderEncode()
}

// Run with:
// go run main.go
```

STEP 4: Execute the program with: `go run main.go`

## Supporting Material/References:

This testing program will crash with the following error message:

``` sh
panic: runtime error: slice bounds out of range [:16] with capacity 6

goroutine 1 [running]:
github.com/slackhq/nebula.HeaderEncode(0xc0000d3f5a, 0x6, 0x6, 0x0, 0x0, 0x845461, 0xc, 0xc0000bc0b8)
	/home/scop/Documents/bugbounty/nebula/header.go:96 +0x7f
github.com/slackhq/nebula.(*Header).Encode(0xc0000d3f60, 0xc0000d3f5a, 0x6, 0x6, 0xc000000180, 0xc0000d3f78, 0x407e85, 0xc000026118, 0x0)
	/home/scop/Documents/bugbounty/nebula/header.go:132 +0x74
main.repro_HeaderEncode(...)
	/home/scop/Documents/bugbounty/nebula/crashrepro/main.go:17
main.main()
	/home/scop/Documents/bugbounty/nebula/crashrepro/main.go:23 +0x67
exit status 2
```

**Comment by forfuncsake** [comment]
Thanks for the thorough report @pventuzelo!

I've taken a look through the code and confirmed that this panic will not present in binaries compiled from the sources in this repo. As it stands, all code paths that lead to an `EncodeHeader` call safely pass in an `mtu`-sized slice.
One would need to import the nebula package and use that function "incorrectly" (as demonstrated) for this panic to occur, so there is no requirement for an urgent patch at this time.

That said, we'd certainly welcome a PR that makes `(*Header).Encode()` more resilient with your proposed solution.
