### ISSUE TITLE
raspberry: nebula.service started before time was sync

### ISSUE THREAD

**Issue by admun** [slackhq/nebula#334]
I installed nebula on a raspberry pi3 running centos7.

nebula is started using the example systemd service script @ https://github.com/slackhq/nebula/blob/master/examples/service_scripts/nebula.service

On reboot an error was observed

● nebula.service - Nebula mesh VPN
   Loaded: loaded (/usr/lib/systemd/system/nebula.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 1969-12-31 16:00:23 PST; 50 years 10 months ago
  Process: 609 ExecStart=/var/lib/nebula/nebula -config /var/lib/nebula/config.yml (code=exited, status=1/FAILURE)
  Process: 600 ExecStartPre=/usr/sbin/modprobe tun (code=exited, status=0/SUCCESS)
 Main PID: 609 (code=exited, status=1/FAILURE)

Dec 31 16:00:22 pi3-02.local systemd[1]: Starting Nebula mesh VPN...
Dec 31 16:00:22 pi3-02.local systemd[1]: Started Nebula mesh VPN.
Dec 31 16:00:23 pi3-02.local nebula[609]: time="1969-12-31T16:00:23-08:00" level=error msg="Failed to load ca from config" error="error while adding CA certificate to CA trust store: provided CA certificate is expired; kkhome.net"
Dec 31 16:00:23 pi3-02.local systemd[1]: nebula.service: main process exited, code=exited, status=1/FAILURE
Dec 31 16:00:23 pi3-02.local systemd[1]: Unit nebula.service entered failed state.
Dec 31 16:00:23 pi3-02.local systemd[1]: nebula.service failed.

Since there is no hw clock on pi, the OS is rely on chrony/ntpd to sync the time. I think nebula was started before that, hence this error.

A manual restart fixed the issue.

I think the service script should take that into account, ideally only on raspberry pi

**Comment by MikePadge** [comment]
This is most likely a Cento-ARM isssue, I've never seen this on Raspbian 

Try changing "After=basic.target network.target" to "After=basic.target ntpd.service" or chronyd.service since ntp is I guess officially chronyd in Centos8.

**Comment by admun** [comment]
To close the loop, I finally fix it w/ this systemd service file

```
[Unit]
Description=Nebula mesh VPN
Wants=basic.target
After=basic.target network.target chronyd.service remote-fs.target
Before=sshd.service

[Service]
Type=simple
SyslogIdentifier=nebula
StandardOutput=syslog
StandardError=syslog
ExecStartPre=/usr/sbin/modprobe tun
EnvironmentFile=/var/lib/nebula/config.yml
ExecStart=/var/lib/nebula/nebula -config /var/lib/nebula/config.yml
# TODO use kill -HUP
ExecReload=/usr/bin/pkill nebula; /var/lib/nebula/nebula -config /var/lib/nebula/config.yml
ExecStop=/usr/bin/pkill nebula
Restart=always

[Install]
WantedBy=multi-user.target

```
