### ISSUE TITLE
openwrtx64 can't run nebula

### ISSUE THREAD

**Issue by zgcbug** [slackhq/nebula#338]
I downloaded the file nebula（linux-amd64.tar.gz）to run，not found errors。
root@OpenWrt:~# ./etc/nebula/nebula -config /etc/nebula/config.yml
-ash: ./etc/nebula/nebula: not found
root@OpenWrt:~# bash ./etc/nebula/nebula -config /etc/nebula/config.yml
bash: ./etc/nebula/nebula: No such file or directory
root@OpenWrt:~# /etc/nebula/nebula -config /etc/nebula/config.yml
-ash: /etc/nebula/nebula: not found
root@OpenWrt:~# bash /etc/nebula/nebula -config /etc/nebula/config.yml
/etc/nebula/nebula: /etc/nebula/nebula: cannot execute binary file

**Comment by wadey** [comment]
It looks like you are trying to run the binary with `bash`. Assuming you downloaded the binary to `/etc/nebula/nebula`, trying executing it like this (remove the `bash`):

    /etc/nebula/nebula -config /etc/nebula/config.yml

**Comment by zgcbug** [comment]
root@OpenWrt:~# /etc/nebula/nebula -config /etc/nebula/config.yml
-ash: /etc/nebula/nebula: not found
same error

**Comment by wadey** [comment]
You should redownload the binary and put it in either /usr/bin or /usr/local/bin and run it from there

**Comment by zgcbug** [comment]
I've tried，same errors

**Comment by actronzs** [comment]
> I've tried，same errors

on openwrt router:

copy nebula to /usr/bin/
copy config.yml to /etc/nebula/
run it like this: nebula -config /etc/nebula/config.yml

I also suspect that you want to start the wrong type of nebula. for openwrt router architecture (arm, mips, softfloat) must be the right one.

**Comment by ftong2020** [comment]
Interestingly, I encountered this issue as well. I was running Openwrt targeting x86_64(on Vmware Esxi with Intel chip) Version 19.07. The binary works fine on Ubuntu 64bit VMs, but will not work on openwrt.

Error message is exactly the same,
root@OpenWrt:~# ./nebula
-ash: ./nebula: not found

If I switch it to nebula binary targeting darwin(MacOs), it will produce the same error as if it is running on ubuntu
root@OpenWrt:~# ./nebula
�: not foundne 1: ����
./nebula: line 2: H__PAGEZEROx__TEXT����__text__TEXT: not found
./nebula: line 3: syntax error: unexpected "("

Compile it with openwrt x86 toolchain might help, but I don't know.

**Comment by ftong2020** [comment]
I did some research and realized that this is a common problem with minimal linux which are using musl libraries. If you check your openwrt's libc version, by running "/lib/libc.so", it will print something like this:
musl libc (x86_64)
Version 1.1.24
Dynamic Program Loader
Usage: /lib/libc.so [options] [--] pathname [args]

and currently binary released by officals are compiled with glibc, which is not compatible with it. You will encouter the same issue if you run it in alpine based linux containers.

The solution is quite simple, just compile it from source with golang + musl library. Currently my approach is to use a customized golang:alpine docker image with make/gcc/musl-dev installed from apk command.

Or try this super long one liner: docker run --rm --name nebulacompile -v `pwd`/nebula:/nebula golang:alpine sh -c 'apk add make gcc musl-dev &&  cd /nebula && make all'

**Comment by wadey** [comment]
You can also try compiling with `CGO_ENABLED=0`, as we don't rely on CGO (and I'm thinking we should probably just switch to CGO_ENABLED=0 in the released builds).

**Comment by ftong2020** [comment]
> You can also try compiling with `CGO_ENABLED=0`, as we don't rely on CGO (and I'm thinking we should probably just switch to CGO_ENABLED=0 in the released builds).

Yep,  disable cgo works for me as well.

**Comment by stangri** [comment]
On snapshots and 21.02-snapshots of OpenWrt you can run: `opkg update; opkg install nebula;` to install native OpenWrt nebula package.

I've asked about adding information about OpenWrt packages to the README, but there's no place to add information about packages which are not available for download from releases ATM.

**Comment by stangri** [comment]
This can be closed now, that there's a native OpenWrt nebula package.
