### ISSUE TITLE
root certificate is expired, how to renew

### ISSUE THREAD

**Issue by msmarks** [slackhq/nebula#341]
My root certificate is expired, and I lost all connections to all nodes. how I can fix it.

**Comment by zeisss** [comment]
Hi, you need to generate a new CA and roll it out to all device.  You cannot extend an existing CA afaik.

Generally you want to create a second CA before the first one expires and start using both and slowly do a rolling replacement of the old with the new one.

**Comment by msmarks** [comment]
@zeisss thank you for the advice.

**Comment by kvtb** [comment]
> start using both and slowly do a rolling replacement

but `pki.ca` support only one root certificate.
on slow rolling replacement there inevitable will be nodes with different `pki.ca` and they won't trust each other

**Comment by wadey** [comment]
> but `pki.ca` supports only one root certificate.

This is incorrect, as the example mentions you can put multiple CA certificates in the file: https://github.com/slackhq/nebula/blob/v1.3.0/examples/config.yml#L6
