### ISSUE TITLE
Is it possible to manually add an advertised IP?

### ISSUE THREAD

**Issue by Mrc527** [slackhq/nebula#347]
Hello,
I've a setup with a docker container running a nebula endpoint.

I forwarded the container ports on the host but the nebula server is advertising his local IP, correctly.
Is there a way to instruct the nebula node to advertise an IP/port which is not a local interface IP? That would decrease my link setup speed.

Thanks!

Marco

**Comment by jimpea21** [comment]
I see this is an old thread, so perhaps you resolved this already, but I think it's useful to note that the WAN IP for a Nebula node won't be discovered for advertisement if the node is on the same LAN as the lighthouse (at least, in my testing this is what happened, repeatedly).

My understanding is that Nebula will advertise all discoverable IP's to the lighthouse though. You can blacklist IP's and interfaces so that they are **not** advertised, but I'm not aware of a way to force an arbitrary IP to be advertised.

When you say 'not a local interface IP', do you specifically mean the public internet WAN IP is not advertised? This is the issue I had, and moving the lighthouse to a cloud VPS will fix this.

**Comment by Mrc527** [comment]
Hi @jimpea21,

my problem is with Docker. If I forward the nebula port, say 5555, to the host (option -p 5555:5555) the nebula executable still see it's own local IP (172.16.20.1 for example) instead of the IP of the host (192.168.1.20). All the subsequent jumps, the WAN for example, are correctly identified but this small issue prevents other nebula nodes on the same local network (192.168.1.0/24) to identify my docker instance as they clearly cannot connect to a docker IP (172.16.0.0/12).

They try to connect over the WAN, but depending on the router you may have success or not. The correct strategy should be to allow my docker instance to advertise the correct IP:PORT of the host machine and, since I understand it's difficult to find out, I propose an option to manually specify it.

**Comment by jimpea21** [comment]
I see, this makes a lot of sense.

Thinking about this in normal-network land though, why not just add a static route on your router to point 172.12.0.0/12 to point to your Docker host IP 192.168.1.20? The Docker host is going to drop any random IP communication, but connections to the specified port 5555 should get forwarded as expected. Thus, advertising the internal docker IP won't matter - it will get forwarded to the default router, which will send it to the docker host, which will forward the required port into the container.

The other thought I have is that you could add a static_host_map entry onto the _other_ clients to point to the VPN IP of the container. So in the Nebula config, if your container has VPN IP 10.20.20.20 and is configured on port 5555 as you say, and the Docker host has LAN IP 192.168.1.20 then you might have this in the config.yml for the other nodes:

````
static_host_map:
  "10.20.20.1": ["43.23.11.60:4242"] # Lighthouse on cloud VPS
  "10.20.20.20": ["192.168.1.20:5555"] # Docker container 1 via host LAN IP
````

The downside is you need to do this on every client that needs to know where the container is :/

I certainly agree that being able to force advertisement of a particular IP:port directly from the Nebula node would be a lot easier and Docker seems a good use case. The local_allow_list already allows filtering what subnets are advertised, it doesn't seem to be a big jump to remove the "filter" aspect and turn that into an "advertise everything listed here" config section.

**Comment by Mrc527** [comment]
The solution you propose is exactly what I'm currently doing, as I'm so lucky to have access to my router.
But this is certainly not a safe assumption for regular users who get the router from their ISP.

> I certainly agree that being able to force advertisement of a particular IP:port directly from the Nebula node would be a lot easier and Docker seems a good use case. The local_allow_list already allows filtering what subnets are advertised, it doesn't seem to be a big jump to remove the "filter" aspect and turn that into an "advertise everything listed here" config section.

Exactly, I think it won't be a huge change and it would add some more flexibility.
