### ISSUE TITLE
Add option to encrypt CA private key with password

### ISSUE THREAD

**Issue by ofer-dev** [slackhq/nebula#348]
Hello,
I think it's better to encrypt the CA private key so that the unencrypted key only exists in memory. Although it wouldn't help at all if the machine is compromised, it can help in cases of misconfiguration or human errors. One less footgun to worry about.

Thanks, 
Ofer

**Comment by dmaroulidis** [comment]
@ofer-dev you could try storing the CA private key on encrypted storage, such as an encrypted block volume, and then only mount it when you need to do CA-related tasks (signing new keys, etc).

**Comment by erayd** [comment]
@dmaroulidis That isn't really a solution; it still results in the key being resident in plaintext on the filesystem.

It's certainly better than nothing though :-).

**Comment by JohnMaguire** [comment]
Thanks for the request! I'm closing this issue as a duplicate in favor of #8 which calls out the AEAD requirement.
