### ISSUE TITLE
[Android] cannot access public internet with Nebula on 

### ISSUE THREAD

**Issue by zoenglinghou** [slackhq/nebula#349]
The Nebula android app successfully connects me to the devices in the nebula network, but with the Nebula VPN on (with or without connecting to any of the networks), Android cannot connect to the internet. I tried to search the issues with no avail.
Here is my config file.
```conf
pki:
  ca: |
    -----BEGIN NEBULA CERTIFICATE-----
    <xxx>
    -----END NEBULA CERTIFICATE-----
  cert: |
    -----BEGIN NEBULA CERTIFICATE-----
    <xxx>
    -----END NEBULA CERTIFICATE-----
  key: <hidden>
  blacklist: []
static_host_map:
  10.0.0.1:
  - <lighthouse>:4242
lighthouse:
  am_lighthouse: false
  serve_dns: false
  dns:
    host: ""
    port: 0
  interval: 0
  hosts:
  - 10.0.0.1
  remote_allow_list: {}
  local_allow_list: {}
listen:
  host: 0.0.0.0
  port: 4242
  batch: 64
  read_buffer: 0
  write_buffer: 0
punchy:
  punch: true
  respond: false
  delay: 1s
cipher: aes
local_range: ""
sshd:
  enabled: false
  listen: ""
  host_key: ""
  authorized_users: []
tun:
  dev: tun1
  drop_local_broadcast: true
  drop_multicast: true
  tx_queue: 500
  mtu: 1300
  routes: []
  unsafe_routes: []
logging:
  level: info
  format: text
stats:
  type: ""
  interval: ""
  prefix: ""
  protocol: ""
  host: ""
  listen: ""
  path: ""
  namespace: ""
  subsystem: ""
handshakes:
  try_interval: 100ms
  retries: 20
  wait_rotation: 5
firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000
  outbound:
  - port: any
    proto: any
    host: any
  inbound: []
```
Am I doing something wrong? I was just trying to set it up like my other *inx devices and they had no issue accessing internet at all.

**Comment by wadey** [comment]
What is the subnet you picked for your certificate? My guess is that your chosen subnet overlaps with your default internet gateway (like you picked 10.0.0.1/16 and your router is actually 10.0.0.1 as well.)

**Comment by zoenglinghou** [comment]
I believe my route is on 192.168.1.1 (that's where the "admin" page is), and the subnet should be on 192.168.1.0/24 (my laptop is on 192.168.1.140) or something like that. :thinking:

**Comment by titouanco** [comment]
Looks like I'm having the same issue, for me it seems to be related to the Android feature "Private DNS".
When private DNS is set to off and Nebula is switched on internet is still accessible, but when a private DNS provider is set Nebula is not able to resolve static host hostname and DNS resolution system wide stop working (accessing servers directly with an IP address still works).

@zoenglinghou Are you using the private DNS feature by any chance ?

**Comment by zoenglinghou** [comment]
Yeah, I am using private DNS... I think that's where the issue is. After disabling privateDNS, I am able to visit the internet with Nebula on...

**Comment by zoenglinghou** [comment]
Closing issue as this is problem is inherently Android's issue.

**Comment by titouanco** [comment]
@zoenglinghou It might be a good idea to open an issue on [DefinedNet/mobile_nebula](https://github.com/DefinedNet/mobile_nebula) then ?

**Comment by zoenglinghou** [comment]
Sure.
