### ISSUE TITLE
Android Feature Request: Allow for setting DNS

### ISSUE THREAD

**Issue by mediocregopher** [slackhq/nebula#356]
I have a host on my nebula network running a DNS server, and I'd like to be able to have my android phone (also on that network) use that server as it's DNS resolver. I could theoretically use Private DNS but that would require me setting up DNS Over TLS, which then requires me to set up a public DNS entry for my server. This would be an information leak I'd like to avoid.

Rather than do that, the android app could set the DNS resolver as part of its VPN settings. ZeroTier has the ability to do this on its android app, so it ought to be possible.

(Sorry if this is not the right place for android feature requests, I'm not sure if that's really a part of this project or if it's a 3rd party thing. If this isn't the right place could you let me know where I should direct my request?)

**Comment by nbrownus** [comment]
This belongs over at https://github.com/DefinedNet/mobile_nebula
