### ISSUE TITLE
Question: Somewhere to contribute documentation?

### ISSUE THREAD

**Issue by ArmoredBlood** [slackhq/nebula#36]
Is there somewhere setup yet to contribute to documentation? I plan on starting to figure nebula out and would like to help with the documentation while I learn it.

**Comment by coderobe** [comment]
There aren't really that many things to learn that aren't already covered by the comments in the example config i think

**Comment by nbrownus** [comment]
I think we will end up doing github pages for more detailed topics. Will likely get to that next week.

**Comment by lfarkas** [comment]
it'd be nice to write at least a faq. eg nebula vs openvpn vs wireguard etc...

**Comment by jrop** [comment]
> There aren't really that many things to learn that aren't already covered by the comments in the example config i think

While the config is well commented, and a good place to start, documentation is preferable here, as it allows more explanation of certain topics that extend beyond just a line of text.  It seems also that there are many people who would enjoy contributing docs (including me).

**Comment by bmullan** [comment]
Also some debug & troubleshooting tips would be useful

**Comment by JohnMaguire** [comment]
Hi all! We now have docs live at https://nebula.defined.net/docs. You may contribute here: github.com/definednet/nebula-docs/
