### ISSUE TITLE
Does nebula support multipath / dynamic pathing?

### ISSUE THREAD

**Issue by PicoCreator** [slackhq/nebula#360]
Wanted to ask for clarification, as I cant find much documentation regarding this - and find it hard to simulate this accurately.

Does nebula automatically switch to an alternative connection, if an existing (ie. direct path to server A in region A, to server B in region B), is degraded, to an alternative path (ie. Indirect path to server C in region B, and hopping over to server B in region B). Note this is not regarding "connection down" and more like connection "degraded" situation (latency spikes, bandwith throttle, etc). Which unfortunately happens quite frequently for a region we deploy into.

Zerotier implements multipath : https://www.zerotier.com/manual/#2_1_5
I believe that Cisco SD-WAN uses the dynamic path approach.

**Comment by nbrownus** [comment]
Short answer is no.

Longer answer is that we will visit some form of this with a relaying feature. Relaying being a final fallback for nodes that can't sort out their NAT troubles. We had originally planned to do multipath but determined it wasn't a good fit for Slacks production use case. Hub and spoke VPNs are difficult to scale effectively and we really didn't want dedicated transit nodes anymore, getting rid of these was a primary design goal. We also didn't want every node to be eligible to proxy traffic as that could lead to a full mesh outage in the worst case scenario.

**Comment by PicoCreator** [comment]
Thanks for clarifying.

Having experienced first hand distributed system failure, with cascading workload moving from one node to another. I agree with the choice on not wanting every node to be eligible to reroute traffic for another node. Until the needed safeguards are in place.

Awesome work here!
