### ISSUE TITLE
Firewall Rules

### ISSUE THREAD

**Issue by emreozcelik** [slackhq/nebula#365]
When I run the Nebula, it tells me:

```
INFO[0000] Firewall rule added   firewallRule="map[caName: caSha: direction:outgoing endPort:0 groups:[] host:any ip: proto:0 startPort:0]"
INFO[0000] Firewall rule added   firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host:any ip: proto:0 startPort:0]"
```

After that, when I look at the 'socklist' I can see the Nebula.

```
udp   4242      27665       0   2987    7  nebula
```

But I can't see the listening port in the 'iptables' and I can't get a handshake until I allow it manually.

Is this the intended behavior?

**Comment by nbrownus** [comment]
The nebula firewall does not rely on `iptables`, it is handled within the `nebula` process itself and it controls packets on the nebula mesh and not packets on the physical network layer. You will need to ensure UDP packets can flow on the physical link for nebula.
