### ISSUE TITLE
Nebula Gui

### ISSUE THREAD

**Issue by gharsallahmoez** [slackhq/nebula#377]
is there an open source tool that provides Graphical user interface(gui) for nebula ?

**Comment by jimpea21** [comment]
Not that I'm aware of...Nebula hasn't been out that long for the general public though.

My understanding is that Nebula was originally designed to be run as an 'always on' service in the background, and I use it as such. I don't see a need for a GUI in this use case.

Perhaps you can outline what you would expect from a GUI though, and what platforms you would want it on, and someone might start such a project :)

**Comment by oliverbutler** [comment]
> Perhaps you can outline what you would expect from a GUI though, and what platforms you would want it on, and someone might start such a project :)

Myself, (and likely many users), would love to help work on a CA management/GUI user friendly face for nebula. Bringing it closer to the user experience from other overlay VPN solutions.

**Comment by MrAvana** [comment]
Also:  gui to toggle/ check the status of the connection.

**Comment by from-wtm** [comment]
Like @MrAvana said - a GUI toggle would be great. This would be fantastic for our WFH folks who struggle with  remembering to turn VPN on. A little green dot in the menu bar (on a mac) or system tray would be great.

**Comment by SamSirry** [comment]
I think aiming for a GUI client like the good ol' NeoRouter's would be a nice long-term goal.
It shows which hosts are online/offline, optionally grouped, and provides a quick menu or toolbar with custom commands. Another Window also allows for setting up firewall rules...
![neorouter 1](https://user-images.githubusercontent.com/30126053/119748646-df861900-be84-11eb-87bc-801ddfa3eb9d.png)

**Comment by Chaostheorie** [comment]
Is there anyone still interested in this? Seems like a good idea for end-users of a network to make nebula more attractive to companies and organizations with many employees/ members (i.e. work from home with non-company devices with a nebula company network).

**Comment by unreality** [comment]
I created a basic GUI for windows available at https://github.com/unreality/nebula-windows-ui

**Comment by JohnMaguire** [comment]
Thanks for the feature request.

The Nebula project is focused on providing highly performant and security tunneling between your devices, with simplicity as a design goal. In order to ensure a focus on security and performance it's important to keep the surface area of Nebula low.

While a GUI for Nebula could make deployment of Nebula easier for users, it's currently considered out of scope of the OSS project. We welcome community / third-party efforts here, such as the project @unreality linked above.

Thanks for using Nebula!
