### ISSUE TITLE
[macOS] Unable to ping its own IP

### ISSUE THREAD

**Issue by nfam** [slackhq/nebula#38]
Lighthouse (192.168.100.1): a DigitalOcean droplet with public IP.
Laptop (192.168.100.2): MacbookAir 2018 Catalina.
Config: I use the example config (with lighthouse public IP)

I can ping from Laptop to Lighthouse, and from Lighthouse to Laptop. But on the Laptop, I cannot ping its own IP (192.168.100.2).

![Screenshot 2019-11-23 at 11 50 21 PM](https://user-images.githubusercontent.com/35899503/69482398-5506c880-0e4d-11ea-8ed0-88292e0acd0c.png)

On another Linux laptop with IP (192.168.100.3), I can ping its own IP.

Is it the limitation of macOS `utun` or somehow I need to config my Mac?

**Comment by rawdigits** [comment]
I think this is a peculiarity of utun and the mode we have to use for nebula on osx, which is actually "Point-to-Point" mode. I think you can do the workaround here to make local traffic work:

https://superuser.com/questions/1283421/cant-ping-localhost-from-utun-interface

**Comment by nfam** [comment]
If we need to set pf redirect rule
```sh
rdr on utun0 from any to 192.168.100.2-> lo0
```
then we may need to know utun interface name in advance (for shell script files).
On my macOS Catalina, when I start nebula, it brings up `utun4` (after the last utun) even I configured `dev: neb0` or `dev: utun6`. Is there any way to fix the utun name?

**Comment by nbrownus** [comment]
`utun` does not have a way to set the device name sadly. You could use `nebula-cert` to print the ip address from the certificate and target the tun device that has been allocated that ip.

**Comment by harpchad** [comment]
> `utun` does not have a way to set the device name sadly.

It does, but [water](https://github.com/songgao/water) does not. There is a [pull request](https://github.com/songgao/water/pull/72) that adds the functionality to water, but it's been sitting since august. Water in general seems to be neglected at the moment.

I've tested with the patched version of water and a modified tun_darwin.go, it works. Caveat is the device name must be of the form utun[0-9]+, basically you can pick the number. It's still useful to have a predictable interface name.

**Comment by rolandjitsu** [comment]
Does anyone else have an issue with reaching any other node than the lighthouse from a macOS (M1 chips w/ latest OS version - 11.4)? I cannot ping it's own nebula IP nor any other node that's connected to the same lighthouse.

**Comment by brad-defined** [comment]
Fixed in #501 
Released in Nebula 1.6.0
