### ISSUE TITLE
Running virtual ip services like keepalived  over Nebula?

### ISSUE THREAD

**Issue by raghukovvuru** [slackhq/nebula#389]
Hi all, I am trying to implement HA load balancing with  Keepalived and HAProxy for the Kubernetes cluster over the Nebula interface. The setup consists of 1 Master and 2 Backups. Everything looks fine, virtual IP is being assigned to the master node and, is being assigned to the next backup node if the master fails. But the problem is the virtual IP can't be reached from other nodes. 

Configuration: 
Master: 192.1.2.1  ( Also Lighthouse)
Backup: 192.1.2.2  ( Also Lighthouse)
Backup2: 192.1.2.3
VIP: 192.1.2.100

Route on each node
`192.1.2.0/24 dev nebula1 proto kernel scope link src 192.1.2.2 MTU 1300 `

Nebula Interface on Master node
```
nebula1: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1300 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none
    inet 192.1.2.1/24 scope global nebula1
       valid_lft forever preferred_lft forever
    inet 192.1.2.100/24 scope global secondary nebula1
       valid_lft forever preferred_lft forever
    inet6 fe80::4527:8535:1c33:b128/64 scope link stable-privacy
       valid_lft forever preferred_lft forever
```

**Comment by caguiclajmg** [comment]
Aren't IPs bound to certificates? This would also mean you can't toss around a "virtual IP" on a nebula overlay network

**Comment by raghubuilds** [comment]
> Aren't IPs bound to certificates? This would also mean you can't toss around a "virtual IP" on a nebula overlay network

Yes, this is what I am thinking. Nebula nodes or lighthouse can't reach virtual IP doesn't know the identity of it. I am going to try this setup with Wireguard.

**Comment by raghubuilds** [comment]
Solved this by creating a GRETAP tunnel over Wireguard. Gretap handles layer2 ethernet frames through Wireguard which provides encryption. I Will try with Nebula because it's simple and has more features. I will let know if it works.

**Comment by nbrownus** [comment]
@caguiclajmg has it right, if you wish to load balance over nebula you currently have to do it before a packet enters the tunnel or after it exits the destination, depending on your needs. Each tunnel is secured independently from the other, meaning a packet destined for 10.1.1.1 can not be read by 10.1.1.2 if it happens to receive it.

**Comment by smeana** [comment]
> Solved this by creating a GRETAP tunnel over Wireguard. Gretap handles layer2 ethernet frames through Wireguard which provides encryption. I Will try with Nebula because it's simple and has more features. I will let know if it works.

Hello @raghukovvuru did you manage to solve this using nebula?

regards

**Comment by RowenTey** [comment]
Has anyone found any solid solutions to achieve a "floating IP" for HA aside from running an additional L2 tunnel?

**Comment by yaroslav-gwit** [comment]
General advice: don't use Nebula this way. `keepalived` expects a "flat" network and you'll have nothing but issues running it over any VPN tech. It may be running fine over WG/Nebula + GRE/VxLAN, until one day it stops working or fails-over randomly, back and forth, and you won't even know where to start the troubleshooting session.

If the app is in a single region or in a single DC, use a flat network with `keepalived` and `HAProxy`. If they are not in the same region - use BGP/OSPF for the IP failover, or an application aware DNS record failover (which is simpler to implement).
