### ISSUE TITLE
nebula mobile

### ISSUE THREAD

**Issue by GPConnect** [slackhq/nebula#398]
Hello,
the nebula mobile app give us the public key and ask us to sign it with our CA to generate the cert needed ! 
what the command to use to do it ? it's not explained it the readme ! 
Thanks

**Comment by GPConnect** [comment]
should i add the "-in-pub" variable to the "nebula-cert sign" command ? 
./nebula-cert sign -in-pub "" -name "" -ip "" -groups ""

**Comment by nbrownus** [comment]
`-in-pub` is the correct usage, the intention is that unprotected private key material never leave the device it is generated on. Pass the path to a file containing the public key your mobile device generated to this command.

`./nebula-cert sign -in-pub "/path/to/pub.key" -name "device name" -ip "10.0.0.9" -groups "phone"`

Once v1.4.0 is released you can use the `-out-qr` flag to generate a qr code of the resulting certificate. You can then scan that image with your phone to make importing it easier.
