### ISSUE TITLE
What's the difference between this and say LogMeIn Hamachi's mesh network?

### ISSUE THREAD

**Issue by StewAlexanderACC** [slackhq/nebula#4]
Awhile back I tried to use LogMeIn Hamachi's mesh network 

https://documentation.logmein.com/webhelp/EN/CentralUserGuide/LogMeIn/c_hamachi_header_ManageNetworks.html

Outside of a cost model, how is this different?

**Comment by StewAlexanderACC** [comment]
I had a node in the US eastern US and another in the Philippines, using Himachi and boy was it tediously slow... partly due to the very slow network speed on the Philippine host that basically was connected by hotspot internet over cellular

**Comment by rawdigits** [comment]
I'm not directly familiar with their offering, but at a glance, theyu don't appear to have an open source version, and I don't know that they offer segmentation. I could be wrong, as this was just via a quick look.
