### ISSUE TITLE
How does the firewall work?

### ISSUE THREAD

**Issue by SyntheticGoop** [slackhq/nebula#422]
Hi! Thanks for the great application. Using it has been a pleasure so far.

I am trying to understand how the firewall works and there doesn't seem to be much documentation around it.
The only example I found was the allow all outgoing, allow incoming pings rule in the example.

I have a few questions:
1. When in the context of inbound, the port refers to the local port. Conversely, in the outbound context, does the port refer to the local or external port?
2. If it refers local and I have a service that communicates from any local port to a predefined foreign port, can I open the firewall for just local any -> foreign fixed?
3. Does the service automatically allow responses to an inbound firewall rule to pass? Or do I have to set another outbound rule for that?

I would be willing to make a PR with usage examples and documentation.

**Comment by caguiclajmg** [comment]
1. Seems to be the remote/external port

https://github.com/slackhq/nebula/blob/7a9f9dbded135947abb5f55acdf1befbe484bc91/firewall.go#L616-L622

2. See above
