### ISSUE TITLE
drop_local_broadcast and drop_multicast not effective

### ISSUE THREAD

**Issue by coderobe** [slackhq/nebula#45]
Using Wireshark i can see broadcast & multicast traffic on the network no matter which state these flags are set to.
I tried checking nebula's code, and could not find where `drop_local_broadcast` and `drop_multicast` are actually used, so i am having a hard time debugging this.

Can someone explain to me how these flags are supposed to work, and where i can find the implementation?

**Comment by nbrownus** [comment]
Config is pulled in here https://github.com/slackhq/nebula/blob/master/main.go#L265-L266
Enforced here https://github.com/slackhq/nebula/blob/master/inside.go#L17-L25

If there are any bugs they would like be
- https://github.com/slackhq/nebula/blob/master/inside.go#L194
- https://github.com/slackhq/nebula/blob/master/interface.go#L78

**Comment by coderobe** [comment]
Hmm, that looks sane. I must be doing something odd with my setup then...
