### ISSUE TITLE
Make release names uname -r compatible

### ISSUE THREAD

**Issue by SebDanielsson** [slackhq/nebula#455]
Would make it easier to download and install nebula on a variety of platforms and architectures.

For example I would like to use this oneliner whether I'm downloading Nebula on my M1 Mac or my x86_64 Linux server:
curl -L https://github.com/slackhq/nebula/releases/download/v1.3.0/nebula-$(uname)-$(uname m).tar.gz | tar -xvz; chmod +x nebula nebula-cert; chown root:root nebula nebula-cert

Right now this will translate to nebula-linux-x86_64.tar.gz while the release is named nebula-linux-amd64.tar.gz

**Comment by wadey** [comment]
It's not one line, but this is what I do:

https://github.com/wadey/nebula-tools/blob/85c1170b7ea8ddf4b2ee0c4400b57bda1ae89190/nebula-release.sh#L4-L9

**Comment by SebDanielsson** [comment]
This is awesome, then I can get away with the following:
`curl https://raw.githubusercontent.com/wadey/nebula-tools/master/nebula-release.sh -o nebula-release.sh; chmod +x nebula-release.sh; ./nebula-release.sh`

**Comment by SebDanielsson** [comment]
Are there any plans to include nebula in the Homebrew, dnf  and AUR repos?

**Comment by jdoss** [comment]
@SebDanielsson See https://github.com/slackhq/nebula/pull/414 for DNF and Arch repos.

**Comment by SebDanielsson** [comment]
Thanks for the help guys, hoping for a release on Homebrew as well😃

**Comment by wadey** [comment]
> Thanks for the help guys, hoping for a release on Homebrew as well😃

I don't use it myself, but it's there already:

https://formulae.brew.sh/formula/nebula#default
