### ISSUE TITLE
Nebula will not start on ipv4-only host

### ISSUE THREAD

**Issue by jprostko** [slackhq/nebula#467]
Hello,

Is it a hard requirement that ipv6 be available on all hosts running nebula as of v1.4.0?  I started upgrading one of my lighthouses to v1.4.0, only to find that nebula would crash out when starting up due to "unable to open socket: address family not supported by protocol".

I had that host set to have **ipv6.disable=1** within its GRUB configuration, and after changing the GRUB entry to remove the ipv6 flag, nebula was able to start fine after the reboot, and the UDP listener binded to [::ffff:0.0.0.0] just fine.  Afterwards I also explicitly disabled ipv6 on all interfaces but loopback, and nebula also started up fine in that scenario.  It seems it's just looking to ensure that the ipv6 kernel module is loaded?

I saw some discussions about ipv6 in other issues, as well as the PR below, but nothing made it sound like ipv6 was now a hard requirement.

https://github.com/slackhq/nebula/pull/369

Thank you.

**Comment by Kemichal** [comment]
I had the same problem on a host, worked after re-enabling ipv6.

**Comment by vladimir-incountry** [comment]
@jilyaluk thanks for the PR. I hope the Nebula team will merge it.
Due to the company security requirements, it is turned off and we cannot use the latest version.

**Comment by perfecto25** [comment]
facing same issue, ipv6 is disabled for security, unable to use nebula

**Comment by Savemech** [comment]
@nbrownus @wadey @rawdigits @JohnMaguire 
Hi team!
Could you please take a look?

**Comment by perfecto25** [comment]
can this be merged? We want to use this tool but are unable to due to ipv6 requirements

**Comment by rjsocha** [comment]
Same here. Please allow option to disable ipv6 sockets.

**Comment by lukytux** [comment]
Same here. Please allow option to disable ipv6 sockets.

**Comment by JohnMaguire** [comment]
Hi @Savemech - we're aware of the issue with IPv4-only hosts and have plans to resolve the issue. Unfortunately we don't have an ETA at this time.

**Comment by d4l3k** [comment]
Just ran into the same issue on an embedded platform, it's been a year since the last update. Is there any timeline for when that PR might land?

**Comment by wadey** [comment]
This has been fixed with #787
