### ISSUE TITLE
Error running as non-root user without TUN

### ISSUE THREAD

**Issue by mrbluecoat** [slackhq/nebula#470]
This is similar to  #300 but in my case I don't need the TUN interface so my config.yml includes:

```
tun:
  # When tun is disabled, a lighthouse can be started without a local tun interface (and therefore without root)
  disabled: true
```

I'm running as the ubuntu user but I'm getting these two errors:

```
systemctl --user status nebula.service
● nebula.service - Nebula Service
     Loaded: loaded (/home/ubuntu/.local/share/systemd/user/nebula.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-05-13 23:26:48 UTC; 2s ago
   Main PID: 969 (nebula)
     CGroup: /user.slice/user-1001.slice/user@1001.service/nebula.service
             └─969 /usr/local/bin/nebula -config /home/ubuntu/nebula/config.yml

May 13 23:26:48 lighthouse systemd[774]: Started Nebula Service.
May 13 23:26:48 lighthouse nebula[969]: {"error":"operation not permitted","level":"error","msg":"Failed to set listen.read_buffer","time":"2021-05-13T23:26:48Z"}
May 13 23:26:48 lighthouse nebula[969]: {"error":"operation not permitted","level":"error","msg":"Failed to set listen.write_buffer","time":"2021-05-13T23:26:48Z"}
```

I'm not sure what `Failed to set listen.write_buffer` means.

Here's my nebula.service file:

```
[Unit]
Description=Nebula Service

[Service]
Restart=always
RestartSec=1
ExecStart=nebula -config /home/ubuntu/nebula/config.yml

[Install]
WantedBy=multi-user.target
```

**Comment by mrbluecoat** [comment]
never mind, user error. I should have kept these lines commented out: https://github.com/slackhq/nebula/blob/master/examples/config.yml#L87-L88

**Comment by nbrownus** [comment]
You have `listen.write_buffer` and `listen.read_buffer` set in your config and lack the permission to establish them. This is a non fatal error and nebula should be running just fine despite them. If you want the errors to go away you could give nebula `CAP_NET_ADMIN` capabilities or remote the config items.

If you have stats enabled you could see if you need to tweak these buffer sizes by looking at `udp.*.drops`, `udp.*.rcvbuf`, and `udp.*.sndbuf`

**Comment by mrbluecoat** [comment]
Will this also have the same effect?

```
echo 'net.core.rmem_default=20000000' | sudo tee -a /etc/sysctl.conf
echo 'net.core.wmem_default=20000000' | sudo tee -a /etc/sysctl.conf
sudo sysctl -p
```

( per https://github.com/slackhq/nebula/blob/master/examples/config.yml#L84 )

**Comment by nbrownus** [comment]
Yes and it would also affect every other socket on your system, and you may not want that. We use a system call on linux that can go above the max sysctl setting because we didn't want other services at Slack to take advantage of the larger buffer possibilities and eating all the available memory.
