### ISSUE TITLE
How can i Work with stats page?

### ISSUE THREAD

**Issue by rfakit** [slackhq/nebula#476]
hi
I uncomment the stats section for graphite bu i got this error after run the server.
and can not find any document around this topic

2021/05/19 06:55:31 dial tcp 127.0.0.1:9999: connect: connection refused

**Comment by caguiclajmg** [comment]
That error message is as descriptive as it gets, is there a graphite instance running at `127.0.0.1:9999`?

**Comment by rfakit** [comment]
can u give me a guide to use this part in stats page

**Comment by rfakit** [comment]
> That error message is as descriptive as it gets, is there a graphite instance running at `127.0.0.1:9999`?

no i didnt run anything else. should i?

**Comment by rfakit** [comment]
i have to setup graphite stack.
so thanks
