### ISSUE TITLE
Broken on iPadOS 15 - Developer Beta 1

### ISSUE THREAD

**Issue by JoshuaMulliken** [slackhq/nebula#490]
I set up the app on my iPad running the beta version of iPadOS 15 and other VPN apps work just fine but even after a uninstall and reinstall this is still broken.

I am happy to test on iPad OS 15 if there is a way to share my logs. I get this when trying to read the logs for the connection.

![Screenshot 2021-06-27 at 7 36 12 PM](https://user-images.githubusercontent.com/36283247/123562809-00d96e00-d77f-11eb-9c46-7ddfa2cc48e2.png)

**Comment by nbrownus** [comment]
Thanks for reporting. We are aware of the issue and will have a fix for it in the coming weeks. 

Apple made a change to further obfuscate the tun device file descriptor from vpn service providers.
