### ISSUE TITLE
config works on 1 computer, not on another

### ISSUE THREAD

**Issue by kevindtimm** [slackhq/nebula#492]
I have 3 computers, gateway, old and new.  
gateway is win10 host, ubuntu vm (vm is where nebula runs), win10 host runs vpn connection
old is ubuntu baremetal
new is kubuntu baremetal

My nebula has worked perfectly on gateway and old for 18 months (or more). 

I got new about a month ago, replicated old configuration onto it, removed old from the mesh and all was well.
We had some power issues a few days ago and now new no longer works.
If I remove new and add old, old continues to work.

How can I troubleshoot what network traffic goes through on old -> gateway that does not go through on new -> gateway?

What can I post here that would help to debug?

**Comment by nbrownus** [comment]
Nebula logs would be helpful, it sounds like maybe you didn't move your ca and/or host certificate and private key over.

**Comment by kevindtimm** [comment]
it's been 4 months, I've figured it out.

**Comment by virtadpt** [comment]
@kevindtimm How did you fix it?
