### ISSUE TITLE
1.6.1 crashes ARM64 Debian 10-based Crostini container on boot (ChromeOS)

### ISSUE THREAD

**Issue by stangri** [slackhq/nebula#499]
I have the following init script (as `/lib/systemd/system/nebula@.service`) that I use on both X86_64 and ARM64 computers/VMs:

```
[Unit]
Description=nebula %I
Wants=basic.target
After=basic.target network.target

[Service]
SyslogIdentifier=nebula
StandardOutput=syslog
StandardError=syslog
ExecReload=/bin/kill -HUP $MAINPID
ExecStart=/usr/local/bin/nebula -config /etc/nebula/%i.yml
Restart=always

[Install]
WantedBy=multi-user.target
```

That works fine on X86_64 platform, but in an ARM64 Crostini container (Lenovo Duet Chromebook) if I enable the service, it crashes the Crostini container on next boot. I can't capture the error message in the Terminal as it disappears and Terminal closes too quickly. Without terminal, I don't have access to the crostini system log nor can I fix anything, so the only way out was to reset the Linux container or restore it from a good backup. The Crostini container is Debian 10-based, but I do not have an ARM64 system which I could test with a pure Debian 10 image/nebula.

If I do NOT enable the service, but instead manually start the service after the container is up, there's no issue whatsoever.

I realize that this is not the greatest bug report as far as reports go, I just wanted to raise the flag and give some information if devs want/can investigate it further and/or see if anyone else had this issue and was able to overcome it somehow or if the systemd gurus spot something in the init script itself.

**Comment by nbrownus** [comment]
This is a fairly complex situation! I would assume there is some race/bug with the `network.target` here. I'm not very familiar with chromeos but maybe try a later target? `multi-user.target` should be pretty much at the end.

**Comment by stangri** [comment]
> This is a fairly complex situation! I would assume there is some race/bug with the `network.target` here. I'm not very familiar with chromeos but maybe try a later target? `multi-user.target` should be pretty much at the end.

@nbrownus -- sorry it took me a while to test/reply. Sadly, changing `After=basic.target network.target` to `After=basic.target multi-user.target` didn't seem to help.

If you have any other suggestions (or if I misunderstood your first one), please let me know.

I use the same script on other Linux systems (including x86-based ChromeOS) and it works fine, but something is definitely up with the arm64.

**Comment by noseshimself** [comment]
You might deleay it even more; in another situation (launching kwalletd from a systemd service file) I did not get any reasonable ``After=`` state t launch it after the environment variable DISPLAY was around. There seems to be something inherently broken in the ChromeOS Linux countainers.

**Comment by stangri** [comment]
> Wants=basic.target network-online.target nss-lookup.target time-sync.target
> After=basic.target network.target network-online.target

@JohnMaguire Just tested that and with nebula binary 1.6.1 on Debian 11 container on Lenovo Duet it still crashes the container with the following message appearing in the console:

```
ERROR vsh: [vsh.cc(244)] Failed to accept connection from daemon: Resource temporarily unavailable (11)
```

If I do not enable the service start and start it manually it works fine.

**Comment by stangri** [comment]
I'm no longer able to test Nebula in the configuration which was causing the crash, so I'm closing this.
