### ISSUE TITLE
Windows service

### ISSUE THREAD

**Issue by chrispolley** [slackhq/nebula#50]
This is great - thanks!

My application is a blend of cloud (linux) and multi-site on-prem (mostly windows but also linux) machines. I found that I could get this installed as a service on Windows 7 and Windows 10 using cygwin's cygrunsrv, but was unable to using the built-in sc from Microsoft (see https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/sc-create and https://support.microsoft.com/en-us/help/251192/how-to-create-a-windows-service-by-using-sc-exe).

I suspect this is because the code doesn't use golang.org/x/sys/windows/svc to implement the Windows service hooks.

If you have got this to run as a service on Windows workstations, could please you include tips?
Thanks!

**Comment by rawdigits** [comment]
This may just make your day..... :)

check out #3, which already works fine on Windows. It not only allows nebula to run as one, but also lets nebula register itself as a service via the command line, so you don't need a wrapper like the one from cygwin.

**Comment by rawdigits** [comment]
If anyone needs a precompiled binary for this, I'm happy to post one somewhere... If not, you just change branch and run `make service bin-windows` to create the service-aware version.

**Comment by chrispolley** [comment]
Yes, it does, thanks!
Successfully built, I will try this out.

**Comment by chrispolley** [comment]
OK, it seems to work. However, simply doing "nebula -service install" [in the config directory] doesn't work. Combining "nebula -config c:\nebula -service install" then "nebula -service start" works.

**Comment by SpaceEggs** [comment]
i use [winsw](https://github.com/kohsuke/winsw) to run nebula as a windows service.

**Comment by rawdigits** [comment]
merged in #3

**Comment by livid** [comment]
When installing the service, it seems the absolute path to config.yml is required.

```
nebula -service install -config c:\Example\Nebula\config.yml
```

**Comment by MADhase** [comment]
> When installing the service, it seems the absolute path to config.yml is required.
> 
> ```
> nebula -service install -config c:\Example\Nebula\config.yml
> ```

The absolute path to the certificate-files is needed, too (inside the config.yml).
