### ISSUE TITLE
Android app: support multiple nebula instances at the same time

### ISSUE THREAD

**Issue by stangri** [slackhq/nebula#500]
Currently if I have multiple nebula instances in the android app, I can only enable one at a time. Please allow to enable/connect both nebula instances.

**Comment by nbrownus** [comment]
This is more of a [`mobile_nebula`](https://github.com/DefinedNet/mobile_nebula) issue

Android limits us to a single vpn process and nebula is centered around a single site configuration.

Although if this were to ever be supported it would likely be implemented in `mobile_nebula` as an intermediate router, with at least 1 large caveat: The active nebula networks must not overlap.
