### ISSUE TITLE
UDP multicast

### ISSUE THREAD

**Issue by maxikrie** [slackhq/nebula#504]
Hello,

I am currently evaluating Nebula and I am quite impressed with the ease of getting it running and its functionality! 

However, I am trying a specific use case where UDP multicast packets are sent from one machine, but not received on another machine. Both machines are connected through a router on an Ethernet network, where one acts as a Nebula lighthouse and the other is a simple node to the Nebula VPN. I have verified pinging between both machines and the multicast example works when tested on the Ethernet network directly. Also, I see the multicast packets on wireshark on the sending machine, however they do not appear on the receiver.

Should UDP multicast work at all on Nebula VPN and also what role does drop_multicast play in the config file (I have set this to 'false').

Many thanks!
Max

**Comment by maxmcd** [comment]
Hey @maxikrie, I think this is the answer you're looking for: https://github.com/slackhq/nebula/issues/208#issuecomment-608060419

**Comment by maxikrie** [comment]
Thank you - I saw this, but since it has been a while and future support was hinted, I was wondering whether there have been upgrades. Also, it would be great to get some clarification about status and future plans.

**Comment by nbrownus** [comment]
There are no plans currently to support either multicast or broadcast but we would be happy to discuss the features in the NebulaOSS Slack group.

**Comment by maxikrie** [comment]
Thank you for clarification!

**Comment by JohnMaguire** [comment]
Closed as not planned.
