### ISSUE TITLE
Question:  Setup for Mesh networks like Google Wifi?

### ISSUE THREAD

**Issue by eddiewebb** [slackhq/nebula#513]
I have nebula running fine on 2 cloud platforms, but on my home network (which uses mesh via google wifi) I need to map each individual port of each device, carefully choosing which port to avoid conflicts. 

```
Me --WIFI--> [Google APs] --cat5e--> [Cable Router(bridged)] --> [Internet ..]
```

If I don't the handshakes go out fine, but responses get dropped on return path. This seems common with double NAT, but it seems some setups have mediations.  **I hoped putting my router in bridge mode would fix double NAT issue - but Google support says no mesh system supports udp hole punch** though, was like "yeah 'cloud based' routers do this, all of them, deal with it [ and manually set each device, each port]" and that there is nothing in or in front of the router I can do to fix it.

So I'm just curious beyond the general complexities of NATs and double NATs a la #33 if there were any confirmed success or failures on mesh networks generally. (maybe it;s something in my cable modem I can adjust, etc)

**Comment by brad-defined** [comment]
Nebula 1.6.0 is released with a Relay feature, to cover connectivity cases like the one you're encountering.
https://github.com/slackhq/nebula/pull/678

If you don't want to keep manually forwarding ports through each device, you can try out a Relay configuration.

You can check out the example config to see how to configure a Nebula node to act as a relay, and how to configure other nodes to identify which Relay can be used by peers for access. Also, take a look at https://github.com/slackhq/nebula/issues/33#issuecomment-1180569297 for more info on how to configure it.

**Comment by JohnMaguire** [comment]
FWIW, the mobile apps have been updated to support relays!

At this time, I'm closing this out for inactivity. If you continue to have issues after trying the relay feature, please feel free to open up a new issue or [join us on Slack](https://join.slack.com/t/nebulaoss/shared_invite/enQtOTA5MDI4NDg3MTg4LTkwY2EwNTI4NzQyMzc0M2ZlODBjNWI3NTY1MzhiOThiMmZlZjVkMTI0NGY4YTMyNjUwMWEyNzNkZTJmYzQxOGU). Thanks!
