### ISSUE TITLE
iOS App Generating Invalid Key Pairs

### ISSUE THREAD

**Issue by micahjmartin** [slackhq/nebula#517]
When generating a certificate with the iOS app, the pubkey and private key are not matching.

## Versions

__iOS__
```
App version: 0.0.41-1 (sha:93b106f)
Nebula version: 1.4.1 (go1.16.3)
```

__Windows (CA)__
```
Nebula-Cert version: 1.4.0
```

## Step to reproduce
1. Export certificate from iOS device
2. Sign certificate `.\nebula-cert.exe sign -in-pub device.pub -ip 10.78.1.1/16 -groups Mobile -out-qr device.png`
3. Load  QR via Scanning `device.png`
4. After setting up a lighthouse, the client will flash a message "Config test error: private key is not a pair with public key in nebula cert"

## Other information
The generated certificate is
```
-----BEGIN NEBULA CERTIFICATE-----
Cm0KCFNSREtzSnNzEgmBgrhSgID8/w8iBk1vYmlsZSjTr7aJBjDT79ufBzogxaIT
/DLQNr5fec5wLheC47NmdyFIqLWBvnH1MF9HZxJKIHLyiq/g6A2fMxnI8su0I4Ml
PbFHIfSm+dxkRWK2jqXJEkDzocGxI8SXEGTI89MKrnlazweGJ5CpJgKwHvjRFGQD
szHGNCAiTkeciLv67L+mzNxstaOUoUnIl0idJKSc57cG
-----END NEBULA CERTIFICATE-----
```

Using `.\nebula-cert.exe print -path ..\device.crt` we get the following information:
```
                Is CA: false
                Issuer: 72f28aafe0e80d9f3319c8f2cbb42383253db14721f4a6f9dc644562b68ea5c9
                Public key: c5a213fc32d036be5f79ce702e1782e3b366772148a8b581be71f5305f476712
```

As we can see from the screenshot below, the public key in the cert is the same as the original  public key on the device, this implies that the generated public key does not match.

![2021-08-30-230006_001](https://user-images.githubusercontent.com/15130760/131436340-6873bed2-d0d9-4192-91fc-53beef6730ef.jpeg)
![2021-08-30-230110_001](https://user-images.githubusercontent.com/15130760/131436347-7a04dc5b-3735-4714-9159-6821144e85dd.jpeg)

**Comment by krazy-glue** [comment]
Same thing on iPad even on android and using the public key created by the app to create the certificate the same problem arise

**Comment by micahjmartin** [comment]
First of all, sorry I did not find the Github for the mobile client, I appreciate the link!

Secondly, thank you for that fix, I must have just been navigating away during the setup. That seemed to fix my error
