### ISSUE TITLE
Node certificates limited to a specific machine

### ISSUE THREAD

**Issue by maxikrie** [slackhq/nebula#519]
Hello,

I am trying to understand a potential security issue / unexpected behavior if a node certificate, e.g. the one in the example generated by ./nebula-cert sign -name "laptop" -ip "192.168.100.2/24" -groups "laptop,home,ssh", is intentionally / unintentionally / maliciously copied to multiple machines. In any case, I assume this will cause unexpected behavior as multiple machines access the network with the same IP address.

Is there a way to limit the certificate to a specific machine or are there other means to prevent above from happening?

Many thanks!
Max

**Comment by adamphetamine** [comment]
I'm sorry I don't really get this
- I can't really figure out how to stop the connection being duplicated if the files are copied to another machine
- and also how Brads approach fixes this?

**Comment by wildardoc** [comment]
What he is saying is don't let it be copied.  Generate it on the machine
that needs it so you are not copying and it only resides in the one
machine.  The next step is to protect the files on an account that only the
nebula tunnel account has access to.  If you keep the private key secret no
one can decrypt the info.  However that will not protect from someone
generating a new key pair for the same address.  I believe that will cause
unpredictable behavior with the network.  I haven't tested it.  As I don't
know how the keys will move around the network.  As such you won't be able
to unencrypt all the data for your device was some machines will have your
public let and some will have the other machines.

**Comment by adamphetamine** [comment]
Thanks for the further explanation @wildardoc 
At this point I think it would be more useful to simply say
'Try to protect the keys and config files from users. It is possible to copy these files to another machine and steal it's identity, and currently there is no protection for this'
I'm ok that this is the case, I just think it should be explicit (and probably means I've chosen my root folder badly)
Thank you!

**Comment by wildardoc** [comment]
As long as someone has root access they can get the keys. If you are
concerned about security I would make certain you have good passwords and
lock the nebula folder to owned by root with permissions of 0700 so other
users don't have access.  Also keep the signing certificate under close
protection.

**Comment by adamphetamine** [comment]
Thanks for the extra info and advice.

**Comment by maxikrie** [comment]
Thanks a lot everybody!
