### ISSUE TITLE
Whitelist/Blacklist local interfaces

### ISSUE THREAD

**Issue by spencerryan** [slackhq/nebula#52]
We have been playing with nebula to build a higher speed overlay between several of our sites (all behind different NATs) over the internet than relying on IPsec built into our firewalls. One issue we are running into however, is that even if we set preferredRanges in the config (which is loading/parsing correctly based on the logs), the nodes will find each other over MPLS/low speed networks and not the internet. All sites have a fairly low speed MPLS any-any mesh. 

It would be great if we could tell nebula to not include a local IP as part of the path selection criteria. In the interim I can block the UDP port at the site's firewall to/from the MPLS zone but that gets unwieldy fairly quick.

**Comment by nbrownus** [comment]
We'll noodle on a deny list, should be pretty simple. In the mean time, can you deploy a firewall change to block off UDP for this address space?

**Comment by spencerryan** [comment]
It does work if we have a firewall (either on the host or upstream) block the port as that causes nebula to cycle to another IP. We're having other issues with NAT on both ends, but that isn't related to this request. 

A very brief dive into the code, perhaps it's possible to just load another array from the config file and feed that into localIps() at or around here https://github.com/slackhq/nebula/blob/61d9f241b991bccaa8b82eeee712b49b233d4e2f/hostmap.go#L728

To also exclude any IP's in the config file. Not sure where else that is used but at a quick glance it's just for hostmap and might be an easy enhancement.
