### ISSUE TITLE
Explain how groups work in the readme

### ISSUE THREAD

**Issue by robehickman** [slackhq/nebula#521]
The 'groups' feature and how to create network segregation is not explained anywhere as far as I have seen. The documentation really needs to say that they are created using optional parameters when creating certs, and giving a worked example that explains how to set up a network with segmentation would be very helpful.

**Comment by johnmaguire** [comment]
At this point in time, Step 4 of the README shows how they are created using the optional parameter when creating certs: https://github.com/slackhq/nebula?tab=readme-ov-file#4-nebula-host-keys-and-certificates-generated-from-that-certificate-authority

The example `config.yml` has an example of how to use them: https://github.com/slackhq/nebula/blob/master/examples/config.yml#L343-L348

Additional guidance is available in the [firewall docs](https://nebula.defined.net/docs/config/firewall/).

I'm not sure what else needs to be done here, so I'm going to close this out. PRs can be made against this repository as well as https://github.com/DefinedNet/nebula-docs/ if anyone would like to submit further improvements.
