### ISSUE TITLE
Hub and spoke topology

### ISSUE THREAD

**Issue by chirayu-patel** [slackhq/nebula#528]
First of all awesome work guys !! 

We have a situation where the customer might not want full mesh connectivity between all the nodes but just the connectivity of each node just to a central hub. The central hub could be the lighthouse itself or a separate node.

Is there any way to define which connections should be allowed between which nodes.

Thanks

**Comment by wildardoc** [comment]
That should be what you use the groups for when you make the
certificates.  I've not done it but I believe that is the purpose of
the setting.

**Comment by chirayu-patel** [comment]
Understood.. thx !!
