### ISSUE TITLE
Please add “next steps” or “API” to readme

### ISSUE THREAD

**Issue by bionicles** [slackhq/nebula#53]
Hey,

I think it would be useful to run ansible over nebula to manage a docker swarm. The readme has a getting started Guide but what about the rest of the usage lifecycle (ex how do you actually use nebula once it’s configured?)

Would it be possible to add a section of docs for next steps once the hosts are connected, and perhaps some API list of functions/commands/arguments/options?

Thanks for sharing your project with us,

Bionicles

**Comment by johnmaguire** [comment]
I think for the most part this is covered by the guides here: https://nebula.defined.net/docs/guides/

If there's a specific area of documentation that needs improved, feel free to let us know or [submit a PR.](https://github.com/DefinedNet/nebula-docs/)
