### ISSUE TITLE
Revoke certifiate to block node

### ISSUE THREAD

**Issue by chirayu-patel** [slackhq/nebula#536]
nebula-cert deals with generating certificates.
But there is no mention of revoking them
Should it be done using openssl comand ?

**Comment by chirayu-patel** [comment]
can anyone please help on this ??

**Comment by nbrownus** [comment]
You can block certificates in the local nebula configuration https://github.com/slackhq/nebula/blob/9f34c5e2baa7b05b34bcbb13b62beb1bafd92530/examples/config.yml#L10-L12

`nebula` uses it's own certificate format and `openssl` is not capable of working with it.

**Comment by chirayu-patel** [comment]
Understood .. thx !!
