### ISSUE TITLE
Issue with using FQDN in Static Host Map on Linux

### ISSUE THREAD

**Issue by ibehren1** [slackhq/nebula#543]
Using an FQDN in the Static Host Map on linux causes issue with assigning IP to the interface.

Hostmap example:

```
...
static_host_map:
  "192.168.100.8": ["gateway.example.com:4242"]
...
```

The configuration tests ok with `nebula -test -config config.yml` but upon starting the service, the interface does not get the IP assigned.

```
[root@lighthouse-ue-1a nebula]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
...<snip>...
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP group default qlen 1000
...<snip>...
       valid_lft forever preferred_lft forever
21: nebula1: <POINTOPOINT,MULTICAST,NOARP> mtu 1500 qdisc noop state DOWN group default qlen 500
    link/none 
```

Notice there is no IP on the interface above.

Remove that entry with FQDN resolves issue but I dont have a static IP for this host and am working around a firewall (Palo Alto) that is not letting responses through the NAT.

Version:
```
[root@lighthouse-ue-1a nebula]# nebula -version
Version: 1.4.0

[root@lighthouse-ue-1a nebula]# uname -a
Linux lighthouse-ue-1a.example.com 4.14.246-187.474.amzn2.aarch64 #1 SMP Tue Sep 7 21:48:09 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

Running here on Amazon Linux 2 -- same seems to happen on Ubuntu 20.04 LTS instances.

Works fine on MacOS 1.4 client.

**Comment by nbrownus** [comment]
`static_host_map` entries won't influence the ip address assigned to the tun device. They tell `nebula` that a given vpn ip is reachable at the provided real ip addresses. It is mainly used to tell `nebula` how to reach the lighthouse, as lighthouses should have a public, static, ip address on the internet.

The ip address assigned to the tun device comes from the certificate you give the host running nebula.

**Comment by ibehren1** [comment]
Yes but the documentation says (https://github.com/slackhq/nebula/blob/master/examples/config.yml#L17) routable ip/dns name.  The issue is that using a DNS name (FQDN) in that field causes above described issue where IP is not put on the interface.  If you remove the FQDN and use an IP the interface gets the IP assigned.

```
# The static host map defines a set of hosts with fixed IP addresses on the internet (or any network).
# A host can have multiple fixed IP addresses defined here, and nebula will try each when establishing a tunnel.
# The syntax is:
#   "{nebula ip}": ["{routable ip/dns name}:{routable port}"]
# Example, if your lighthouse has the nebula IP of 192.168.100.1 and has the real ip address of 100.64.22.11 and runs on port 4242:
static_host_map:
  "192.168.100.1": ["100.64.22.11:4242"]
```

**Comment by nbrownus** [comment]
Nebula logs would be helpful in understanding more of what is going on. It's almost as if the dns query is never resolving.
