### ISSUE TITLE
What if lighthouse certificate got compromised

### ISSUE THREAD

**Issue by rucciva** [slackhq/nebula#556]
Just recently discovered nebula and love how it doesn't involve a control server. Even the lighthouse can be excluded from the data plane by disabling the tun interface.
Though since lighthouse certificate is just like any other node certificate, i'm wondering in the worst scenario, can an attacker who successfully stole the certificate use it to join the overlay network?
If so, is there any workaround to prevent lighthouse certificate to be used as such?

Thanks.

**Comment by nbrownus** [comment]
> This is new to me, so are you saying that when we specify static_host_map , the specified node can only receive tunnel initiation request (since it might use another IP or Port when initiating outgoing connection) ?

Not quite, I am describing a mitigation against handshaking with an unanticipated recipient. You can try this by specifying a `static_host_map` entry for an incorrect vpn ip. This also works when an evil or misbehaving lighthouse tells you incorrect information.

If node A is at 192.168.1.1 and has a vpn ip of 10.0.0.1, configure the static host map in node B to say vpn ip 10.0.0.2 is at 192.168.1.1. Do a `ping 10.0.0.2` and you will see in the logs that the wrong host responded and that 192.168.1.1 has been blocklisted for 10.0.0.2.

**Comment by kwinz** [comment]
Is there any way to store the private key in a HSM so it can't be stolen in the first place?

I would like is PKCS#11 support ( issue #328 ). With PKCS#11 I can store the private key in a TPM. Almost all servers and client machines come with a TPM. A TMP is requirement for Windows 11, and if you don't have an actual hardware TPM then your AMD or Intel CPU can provide a TMP 2.0 compatible one. And most cloud providers also provide your VM you a virtual TPM.
