### ISSUE TITLE
Looking for a bit of help in re LightHouse in two device VPN

### ISSUE THREAD

**Issue by johnjces** [slackhq/nebula#562]
I know not where else to ask so please go easy on me as I need a bit of help please. I successfully installed nebula on two (2) raspberry pi 4's, starting at boot and piping logging to a log file. One a Lighthouse the other a basic node. Per all the instructions it states at least two nodes are needed with one being a lighthouse. Both of my networks are available via 1) a public static and 2) persistent public IP. One, the lighthouse network, port 4242 forwarded to the nebula pi. The other I haven't forwarded, as from my reading, the lighthouse is pointed to by my one non lighthouse. Logs show connected, the tun driver is up, ifconfig shows correctly and life is good.
My question is, does a lighthouse have the same connectivity as any non lighthouse client? Routing to the raspberry pi's lan IP using my lighthouse as my gateway for the remote LAN, I get nothing. No Ping, no tracert etc. The opposite is also true. My remote client cannot ping the lighthouse LAN clients, (being properly routed to the rasp pi nebula as a gateway.
Thanks for any help! OR better yet, where can one get help? Which forum?
Thanks again! Looking forward to getting this working as it just seems simple to me and that is good!!!

**Comment by caguiclajmg** [comment]
> My question is, does a lighthouse have the same connectivity as any non lighthouse client?

Yes

> Routing to the raspberry pi's lan IP using my lighthouse as my gateway for the remote LAN, I get nothing. No Ping, no tracert etc. The opposite is also true.

Did you perhaps forget to add the subnet that you're routing to into the certificate of the node that handles that subnet?

**Comment by johnjces** [comment]
Thanks so much! From my research it seemed that should be true. I "think" I added the subnet but... I couldn't say for sure. Is there anyway to check via the log or by changing the log level before recreating the certs?

**Comment by wildardoc** [comment]
./nebula-cert print -path /path/to/the/cert.crt

https://github.com/slackhq/nebula/pull/119/files

**Comment by johnjces** [comment]
My bad! All is now working well!!
