### ISSUE TITLE
Nebula can't establish connection from behind NAPT

### ISSUE THREAD

**Issue by usovalx** [slackhq/nebula#565]
I have tried installing nebula on android phone, but it is unable to connect to another machine when phone is using mobile data.
It appears mobile data connection is using NAPT, with source port changing for every connection.

Network layout:
lighthouse - public IP (cloud machine)
home - broadband with NAT, port forwarding set up for nebula
phone - android behind NAPT

All devices are running latest released versions - 1.4.0 on linux boxes (lighthouse/home) and 1.4.1 on android.

Looking at nebula logs on the lighthouse, I can see the connection from phone
```
Nov 04 00:18:05 tycho nebula[24387]: time="2021-11-04T00:18:05Z" level=info msg="Host roamed to new udp ip/port." certName=op7.nb newAddr="85.255.1.1:57377" udpAddr="xxxx" vpnIp=10.10.220.31
```

Trying to ping `home` box from the phone, I can see home machine tryint to send the handshake (it's set up with punchy & respond)
```
Nov 04 00:18:35 nas2.lan nebula[1283752]: time="2021-11-04T00:18:35Z" level=info msg="Handshake message sent" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=3888370739 udpAddrs="[85.255.1.1:57377 10.10.111.55:46287 192.168.167.57:46287]" vpnIp=10.10.220.31
```

Looking at the tcpdump on home box, I can see incoming handshakes, however source port appears to be different from what is visible on lighthouse
```
00:19:43.259643 IP 85.255.1.1.4944 > 10.10.10.21.5454: UDP, length 252
00:19:43.290009 IP 10.10.10.21.5454 > 85.255.1.1.57377: UDP, length 236
```

I understand that with such aggressive NAT it is impossible to set up the tunnel TO `phone` (current android app doesn't allow to set it to respond to punches).

However in this case nebula at `home` receives handshakes from the `phone`, but insists to reply to handshake using *only* addresses provided by the lighthouse.
It should be adding source ip:port of the handshake message to the list of possible `udpAddrs` when replying to the handshake.

**Comment by nbrownus** [comment]
What does the nebula firewall look like on the home box? By default it's doesn't allow any traffic.

It also looks like you may have a nebula network address space and a local network address space collision.

**Comment by usovalx** [comment]
I'm quite sure the issue is NAPT translation on cell network.
When phone is on wifi network either at home or at work, it connects fine.

To try explainig it once more - on the boundary of mobile network there is aggressive port and address translation.
So outbound handshakes from the phone end up with different source ip/port addresses for different destinations.
Whereas nebula instance on `home` seems to assume phone public host/port will be the same as seen on lighthouse.

**Comment by usovalx** [comment]
If you need any more details - ip addresses, packet captures, etc - I can grab those.

**Comment by nbrownus** [comment]
Read back through. Nebula will certainly have issues getting through situations like this. The best way to solve it with todays capabilities would be to enable ipv6 on your home network.

Relaying is the only other way around and nebula does not currently support this.

**Comment by usovalx** [comment]
Unfortunately IPv6 isn't an option - UK vodafone network doesn't seem to support it yet.
I don't see any fundamental issues with establishing tunnel in my case - as longs as at least one side is accessible from internet.


Looking at `outside.go` and `handshake_ix.go` it seems that `home` should be able to receive the handshake from mobile (I can definitely see incoming handshakes in tcpdump), and identify the peer from certificate data.

All error exits from `ixHandshakeStage1` should produce some data in logs and at the very least I should be able to see `Handshake message received` in the logs.

Is there some kind of firewall / filtering before inbound packets reach `readOutsidePackets` stage in nebula?

**Comment by usovalx** [comment]
It seems I have finally figured it out.
It appears I have managed to misconfigure firewall on the `home` host itself where it won't let incoming handshakes.
The funny thing - everything still worked because of punch-back mechanics for punching through nat (and firewall connection tracking).

Once I fixed firewall rule to accept incoming heartbeats, android app can now successfully establish connection.
There is still a little issue of not being able to initiate connection *to the phone*, because android app doesn't allow to configure punch-back flag.

**Comment by nbrownus** [comment]
That's great to hear! We didn't enable punch back on mobile due to battery concerns, the mobile client code is also OSS and available here https://github.com/DefinedNet/mobile_nebula

**Comment by usovalx** [comment]
I guess having a toggle for punch-back, in case it's ever needed would have been convenient, though it wouldn't have helped for my case :)

I guess only other annoyance with android app - I didn't figure out a way to have it auto-start and enable connection.
So for example when I tried to set up phone backups via nebula, every couple of days it will stop working until I manually restart & reconnect it.
