### ISSUE TITLE
Suggestion: Unify example config file extension 

### ISSUE THREAD

**Issue by zhechenzhu** [slackhq/nebula#57]
I deployed nebula on some of my machines after listening to a recent episode of Linux Unplugged. It worked really well. Thank you. 

One issue that I ran into while setting up systemd service on a linux machine is that, due to the yaml file extension mismatch between the provided example config file and the service file, the service refuse to start. The example config file is named "config.yaml" while the config file path in the systemd service file is "/etc/nebula/config.yml". Toke me a while to figure out.

I would suggest unifying the file extensions to save some head scratch for new users.

**Comment by rawdigits** [comment]
Good suggestion, and thanks for noting this! We will probably change the example file name.
