### ISSUE TITLE
Accessing other LAN devices, 'Unsafe Routes'

### ISSUE THREAD

**Issue by johnjces** [slackhq/nebula#570]
Good day again!

In learning about Nebula, one of the things that I would love to do and that I "think" Nebula can do is expose other devices on my network such as my main router, or my phone system or RDP into a PC etc via that devices LAN IP address. According to the documentation starting at line 568;

"While Nebula is awesome, it might be useful to connect *through* a nebula node
to somewhere else on your network..."

My Nebula network consists of two nodes, one (named) "lighthouse" on a public available IP, (NATed with port forwarding enabled), with a Nebula address of 192.168.98.1. (blindly followed some Web pages documentation for IP setup), on a LAN address of 192.168.0.0/24.

My other node, "other" is also NATed bu no port forwarding is setup as it is not a lighthouse and port forwarding shouldn't be needed. This Node's Nebula IP is 192.168.98.3.

I created node certificates for the Lighthouse and, what I call the "other" node allowing them to carry this "unsafe" traffic on thier respective LANs per lines 583 - 589. I ensured this time that /24 netmask was included!

i then added into the respective config.yml the following for "other";

tun:
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:
    - route: 192.168.0.0/24
      via: 192.168.98.1

My "lighthouse' node is, same as above except:

  unsafe_routes:
    - route: 192.168.1.0/24
      via: 192.168.98.3

From node to node I can ping 192.168.0.15 (lighthouse lan ip) from 192.168.1.30 (other lan IP) without any issue as well as the inverse of the example ping. Pinging the Nebula assigned IPs has never been an issue. I cannot ping any other pingable device on either LAN.

The config.yml file has both in and outgoing firewall rules for any protocol and etc., set to 'any'.

Am I mis-interpreting something or is my config messed up somehow.

Again, thank-you very much for any help!

John

**Comment by Zyfax** [comment]
You may look at this: https://theorangeone.net/posts/nebula-unsafe-routes/

Maybe you are missing a iptables rule or a route table.

**Comment by johnjces** [comment]
@Zyfax 

THANK-YOU! The link you provided was invaluable as I 'thought' that Nebula 'automagically' took care of some of these internal things as since it had some firewall rules, but its very own firewall, and etc. Assumed too much! One thing I had to do was add IPV4 forwarding in sysctl.conf, if I remember correctly, to be able to ping the Nebula network IP via another device, i.e. my pc after adding a route to windoze. Cannot yet ping from another network device as I just now need to set up proper routes in my router for each LAN segment. Anyway, from either Nebula node I can happily ping ANY network device on any network. But the idea is to amke the RPi a full VPN gateway for any device on any network. Getting there!
