### ISSUE TITLE
Install two default unsafe routes via multiple lighthouses

### ISSUE THREAD

**Issue by vbeskrovny** [slackhq/nebula#573]
Dear team,

I am trying to achieve the following scenario: two lighthouses A & B and one client.
The client connects to two lighthouses and each client's configuration .yml tries to install default unsafe route via the A & B lighthouse IP. 
I am getting the following error message: `level=fatal msg="failed to set mtu 1300 on route 0.0.0.0/0; file exists"`
Meaning it is not possible to install two same default routes via two different lighthouses. Only one LH as a default gateway is possible.

I tried not to use the unsafe routing option, and configure the 0.0.0.0/0 route using linux routing pointing to two LH IP addresses, but the traffic is not routed via nebula client's interface, therefore not possible to use LH IP as a gateway to the internet...

Is there any way to correct it or achieve my scenario?

Many thanks!

**Comment by nbrownus** [comment]
The only way to proxy traffic like a traditional vpn would be to use `unsafe_routes` and with v1.5.0 you can specify the metric/priority.

`routes` is meant to be used under very specific circumstances where you know the underlay route for a given vpn ip can support larger MTUs. Slack uses this in very specific areas where they can guarantee the paths support jumbo frames.

**Comment by vbeskrovny** [comment]
I see. Thank you for the feedback.
