### ISSUE TITLE
Type mismatch leads to panic

### ISSUE THREAD

**Issue by rawdigits** [slackhq/nebula#594]
panic: interface conversion: interface {} is *net.IP, not iputil.VpnIp

goroutine 16 [running, locked to thread]:
github.com/slackhq/nebula/overlay.(*tun).RouteFor(0x10, 0x52d9a8)
        github.com/slackhq/nebula/overlay/tun_linux.go:153 +0x8f
github.com/slackhq/nebula.(*Interface).getOrHandshake(0xc00020ed80, 0xc0a80801)
        github.com/slackhq/nebula/inside.go:75 +0x90
github.com/slackhq/nebula.(*Interface).consumeInsidePacket(0xc00020ed80, {0xc00038c000, 0x12e, 0x2329}, 0xc00039a000, {0xc00039a010, 0xc, 0xc}, {0xc00038e500, 0x2329, ...}, ...)
        github.com/slackhq/nebula/inside.go:36 +0x108
github.com/slackhq/nebula.(*Interface).listenIn(0xc00020ed80, {0x7fdcc615c2d8, 0xc00007cc40}, 0x0)
        github.com/slackhq/nebula/interface.go:224 +0x14d
created by github.com/slackhq/nebula.(*Interface).run
        github.com/slackhq/nebula/interface.go:182 +0xa5

**Comment by ekavun** [comment]
I have a somewhat related issue in #1207
