### ISSUE TITLE
lighthouse High availability

### ISSUE THREAD

**Issue by jbenguira** [slackhq/nebula#597]
Hello
What is the correct way to achieve High availability of a nebula network?

Is it to have 2 lighthouse nodes with the same certificate and to configure all the clients to use those 2 lighthouse nodes?

**Comment by caguiclajmg** [comment]
Why do you need the lighthouses in an HA setup? Does having multiple lighthouses not work for you?

**Comment by sneakernuts** [comment]
^ 

This. Multiple lighthouses would be the easiest. Compute cost-wise HA usually cost the same as running two VMs concurrently.

Back to the HA setup, it really depends on your requirements.

**Comment by jbenguira** [comment]
I'm configuring a Nebula network with 200 VMs, some of them will reboot from times to times
If I have only 1 lighthouse node ... and if it's under maintenance for any reason (OS upgrade for eg) the existing booted machines will continue to work, but the new nodes added or rebooted while the lighthouse node is down will not work

That's why I though that having a second Lighthouse node will help for this scenario
Is there a guide anywhere on diffent HA options?

**Comment by tarrenj** [comment]
I've had good luck with HAProxy in the past, but I've never tried it with Nebula: https://cbonte.github.io/haproxy-dconv/2.4/intro.html

I also agree with what others have said, that simply running a second lighthouse would be much simpler and still achieve your intended result.  Out of curiosity, can you go over why you prefer a single HA node to several traditional ones please?

**Comment by caguiclajmg** [comment]
> If I have only 1 lighthouse node ... and if it's under maintenance for any reason (OS upgrade for eg) the existing booted machines will continue to work, but the new nodes added or rebooted while the lighthouse node is down will not work

That's why you should have more than 1.

> That's why I though that having a second Lighthouse node will help for this scenario Is there a guide anywhere on diffent HA options?

There are no suggested options for an HA setup, it's simply "deploy more as needed".

**Comment by wadey** [comment]
I think there is a bit of confusion in this conversation. You should definitely run multiple lighthouses at the same time, preferably hosted in different data centers. 

All of your clients should have all of the lighthouses active in their configs. (You can list multiple in the config file. They are all "shared nothing", so as long as at least one lighthouse is alive and functioning, you will have no downtime for your network.

**Comment by tarrenj** [comment]
After rereading this thread I think the real question is on how to host multiple lighthouses.  I guess one _could_ say running multiple lighthouses _is_ an HA configuration.

> Is it to have 2 lighthouse nodes with the same certificate and to configure all the clients to use those 2 lighthouse nodes?

Each node, regardless of lighthouse status, requires its own certificate and key signed by the root CA. When configuring a second lighthouse you just set `am_lighthouse` to `true` and add it to the `hosts` list on all non lighthouse nodes.

**Comment by rawdigits** [comment]
The lighthouses were designed to be independent, and the answers they provide are coalesced locally by each Nebula node. You should absolutely run multiple, and they should not share any identities between them. This is by design, and as a datapoint, when I left slack, there were 6 lighthouses, and each of the 50,000+ nebula nodes talked to each lighthouse directly. The lighthouses were globally distributed, and were not configured to talk to each other in any way. This is the proper way to run nebula for HA, and in multiple years of running this way, there has never been a loss of availability.

I spoke about this when doing a presentation for All Things Open in 2020, and recommend you watch this video for more context/info. I've linked directly to the section where I discuss the Lighthouse Architecture here: https://youtu.be/qy2cgqglt3o?t=2225

**Comment by sneakernuts** [comment]
> The lighthouses were designed to be independent, and the answers they provide are coalesced locally by each Nebula node. You should absolutely run multiple, and they should not share any identities between them. This is by design, and as a datapoint, when I left slack, there were 6 lighthouses, and each of the 50,000+ nebula nodes talked to each lighthouse directly. The lighthouses were globally distributed, and were not configured to talk to each other in any way. This is the proper way to run nebula for HA, and in multiple years of running this way, there has never been a loss of availability.
> 
> 
> 
> I spoke about this when doing a presentation for All Things Open in 2020, and recommend you watch this video for more context/info. I've linked directly to the section where I discuss the Lighthouse Architecture here: https://youtu.be/qy2cgqglt3o?t=2225

Those 6 lighthouses should be renamed to supernovas 🤣 on a more serious note, that's an amazing stat to share. Thank you.

**Comment by jbenguira** [comment]
Thanks all for the response, indeed my goal was to achieve HA with 2 nebula lighthouse nodes
I was not totally sure about what should be shared.

After some trials and errors I was able to make it work with 2 LH nodes

1) both LH nodes must be signed by the same CA cert
2) both LH nodes must have the same CA.crt
3) all clients should have static map and host pointing to the 2 LH nodes and be signed by the same CA

And yes it's working now, but I have to restart nebula on both nodes for the ping between my clients to work again after shutting down LH1

I guess there is a reconnect delay or something, I will investigate :)

**Comment by theblop** [comment]
@jbenguira do you also use the lighthouse dns? I wonder what's the best way to make it HA too.

Is it best to have multiple lighthouses with the same internal nebula IP or different IPs?

e.g. all lighthouses have the same IP:
```
static_host_map:
  "172.20.0.1":
    - "lighthouse01.example.com:4242"
    - "lighthouse02.example.com:4242"
    - "lighthouse03.example.com:4242"

# on clients only:
lighthouse: { hosts: ["172.20.0.1"] }
```
or each lighthouse has its own IP:
```
static_host_map:
  "172.20.0.1": ["lighthouse01.example.com:4242"]
  "172.20.0.2": ["lighthouse02.example.com:4242"]
  "172.20.0.3": ["lighthouse03.example.com:4242"]

# on clients only:
lighthouse: { hosts: ["172.20.0.1","172.20.0.2","172.20.0.3"] }
```
I am not sure how the DNS resolver would work in the first instance where multiple lighthouses share the same IP:
```
dig @172.20.0.1 foo.nebula 
```
Which lighthouse will reply in that case?? What if one lighthouse is down, one out of 3 queries would fail?

**Comment by sneakernuts** [comment]
> @jbenguira do you also use the lighthouse dns? I wonder what's the best way to make it HA too.
> 
> Is it best to have multiple lighthouses with the same internal nebula IP or different IPs?
> 
> e.g. all lighthouses have the same IP:
> 
> ```
> static_host_map:
>   "172.20.0.1":
>     - "lighthouse01.example.com:4242"
>     - "lighthouse02.example.com:4242"
>     - "lighthouse03.example.com:4242"
> 
> # on clients only:
> lighthouse: { hosts: ["172.20.0.1"] }
> ```
> 
> or each lighthouse has its own IP:
> 
> ```
> static_host_map:
>   "172.20.0.1": ["lighthouse01.example.com:4242"]
>   "172.20.0.2": ["lighthouse02.example.com:4242"]
>   "172.20.0.3": ["lighthouse03.example.com:4242"]
> 
> # on clients only:
> lighthouse: { hosts: ["172.20.0.1","172.20.0.2","172.20.0.3"] }
> ```
> 
> I am not sure how the DNS resolver would work in the first instance where multiple lighthouses share the same IP:
> 
> ```
> dig @172.20.0.1 foo.nebula 
> ```
> 
> Which lighthouse will reply in that case?? What if one lighthouse is down, one out of 3 queries would fail?
> 
> **Update:** ~after some testing it seems that a single IP for all the lighthouses works pretty well for DNS HA too! I can ping and run DNS queries against the single lighthouse IP and start/stop lighthouses without disruption.~ **Update2:** actually I think dnsmasq was caching some DNS replies because eventually I get some empty dns results... **Update3:** So reading the doc again, if my understanding is correct, each lighthouse only knows about the nodes that connect to it, therefore its dns server can only answer about the hosts it knows. I guess that if a LH goes down, the hosts that connected to it initially will disappear from the DNS? @rawdigits any more details how the DNS works in that case? **Update4:** ok so after about a minute the missing DNS name resolves again - It makes sense as the reconnection happens after the "interval" setting!
> 
> So the conclusion seems to be that the DNS resolution can fail for up to a minute if a lighthouse goes down.

I think having multiple light houses with different IPs is the recommendation.

**Comment by theblop** [comment]
> I think having multiple light houses with different IPs is the recommendation.

Is there anything about this in the official docs?
Also using multiple IPs means that the DNS resolver on the clients must be configured with multiple DNS servers.

Here is my dnsmasq config to resolve the .nebula domain with the single IP lighthouse solution:
```
# /etc/NetworkManager/dnsmasq.d/nebula.conf
server=/nebula/172.20.0.1#53
```
and with multiple IPs this would be:
```
# /etc/NetworkManager/dnsmasq.d/nebula.conf
server=/nebula/172.20.0.1#53
server=/nebula/172.20.0.2#53
server=/nebula/172.20.0.3#53
```
But a single LH down would make one in 3 requests fail (I think dnsmasq does round robin dns)

**Comment by tarrenj** [comment]
Each nebula process (lighthouse or otherwise) must be given its own IP address and certificate/key, regardless of if it's on the same host as another nebula process.

I haven't played with the built in DNS yet, but I would assume that adding all the lighthouse nebula IPs to the resolve.conf is the recommended solution. It's possible that DNS entries could propagate through the lighthouses, but I doubt that has been implemented.

**Comment by jbenguira** [comment]
> > @jbenguira do you also use the lighthouse dns? I wonder what's the best way to make it HA too.
> > Is it best to have multiple lighthouses with the same internal nebula IP or different IPs?

I am not using Nebula DNS, it's not needed for my use case, but I did played a bit with multiple nodes having the exact same cert/key as an experiment to understand how it's handled, here are my findings:

1) you can enable nebula on 2 nodes with the same cert/key/nebulaIP but only one of them will receive the traffic
2) if you shutdown one of the node the other one will receive the traffic instead
3) if you resume the first node the traffic is still directed to the second node in this scenario until you stop the second node and restart the first one

I would love to be able to have round robin in nebula to spread the traffic when several nodes have the same cert/key/ip

**Comment by tarrenj** [comment]
> I would love to be able to have round robin in nebula to spread the traffic when several nodes have the same cert/key/ip

I expect them to add an error condition for when a node connects with a certificate already in use to a future version. Any situation involving certificate reuse is not an intended or supported use case, as far as I know.

**Comment by jbenguira** [comment]
> I expect them to add an error condition for when a node connects with a certificate already in use to a future version. Any situation involving certificate reuse is not an intended or supported use case, as far as I know.

Yes I know ... but it would be a lot of fun if it was supported and could be used for load balancer, HA, failover ...

**Comment by theblop** [comment]
Well to achieve some kind of DNS HA I eventually configured 3 lighthouses with different IPs and this dnsmasq config on each client host to resolve the `.nebula` domain with the lighthouses DNS running on port 15353:
```
# /etc/NetworkManager/dnsmasq.d/nebula.conf
all-servers
server=/nebula/172.20.0.1#15353
server=/nebula/172.20.0.2#15353
server=/nebula/172.20.0.3#15353
```
`all-servers` instructs dnsmasq to send dns queries to all the configured DNS servers at the same time and return with the first that answers.

This assumes NetworkManager is configured to use and start dnsmasq (this is on centos8):
```
# /etc/NetworkManager/conf.d/dns.conf
[main]
dns=dnsmasq
```

**Comment by benyanke** [comment]
@jbenguira maybe I'm missing something, but what's fun about adding additional failover complexity if nebula can simply run active/active against all of them? The absolute best form of HA is shared-nothing w/ active/active operation, if your app supports it, and nebula does. Failovers (active/passive) with primary selection like databases use are only ever used because a/a isn't possible.

Just run 2-3 lighthouses and if one is down, that's fine. The others will seamlessly handle the load.

**Comment by jbenguira** [comment]
> @jbenguira maybe I'm missing something

Yes indeed you are missing something! I'm running 2 nebula LH nodes in shared nothing mode. 

What I was suggesting is having support for multiples devices having the same Nebula IP for other use cases ...
If you have services that you want to host with HA eg a "Web server", you have to create a load balancer and point the LB to your X Nebula IP Addresses. It would be interesting to be able to simply have multiple servers with the same nebula IP and the LH nodes could act as a LB

**Comment by benyanke** [comment]
I think you seem to be misunderstanding nebula. It's not an all in one network utility, it's a secure transport layer. Turning LH nodes into loadbalancers would completely change the architecture. Normal user traffic doesn't even go through the lighthouse, it's only used for the initial connection standup.

Why try and force nebula to be your LB, when you can just run a loadbalancer in front of multiple nebula IPs?

Sharing and IP between two devices is effectively impossible the way modern networks are configured without a reverse proxy in the middle (which nebula isn't). I suggest you run nginx or traefik in front of your nodes.

**Comment by jbenguira** [comment]
I'm not misunderstanding that part of nebula at least, I totally get that it's a meshed network and LH nodes are used only to indicate to connected peers where to find other peers. It seems very hard for you to understand my idea ... but it's really simple in fact. LH Nodes could informs Nebula clients about the list of potential targets with the same nebula IP.
This could be similar to having multiple DNS A entries and doing round robin DNS. So really it's the clients that will split the packets to various devices with the same nebula IP.

With your suggestion, Nginx or Traefik becomes the SPOF ... and a real network loadbalancer is costly.


I don't want to waste any more time on this discussion, it seems this idea is not welcome anyways here... so I will close this topic now

**Comment by benyanke** [comment]
No, I definitely understand your idea, I'm stating it's not what nebula is designed for.

As you said, there's already tools for removing single points of failure like DNS.

**Comment by nbrownus** [comment]
@jbenguira We have done some thinking on what load balancing in nebula might look one day. If you would like, please open a new issue or join the slack group it can be discussed.

**Comment by jbenguira** [comment]
> @jbenguira We have done some thinking on what load balancing in nebula might look one day. If you would like, please open a new issue or join the slack group it can be discussed.

Lovely, it could be an amazing feature! I'll definitely join the slack group to discuss it :)
