### ISSUE TITLE
Add Certificate Signing Request support to nebula-cert

### ISSUE THREAD

**Issue by tarrenj** [slackhq/nebula#600]
https://www.globalsign.com/en/blog/what-is-a-certificate-signing-request-csr

This would support an offline CA and allow for generating host keys directly on the host.

The workflow _could_ be as follows:

1. Generate the CA offline with `sudo nebula-cert ca -name "Nebula Lab"`
2. Copy the ca.crt to the new Nebula host
3. Generate the CSR and `host.key` with`nebula-cert csr -name "host" -ip "10.1.0.2/24" -subnets "10.3.0.0/24"`
4. 4.Copy the CSR to the offline CA
5. Create the full host certificate (on the offline CA) `nebula-cert sign host.csr`
6. Copy the full host certificate back to the Nebula host

**Comment by ofer-dev** [comment]
Nebula-cert already support similar operation. You can generate private and public keys on the host using "nebula-cert keygen" command and sign the public key on the offline CA using "nebula-cert sign"

**Comment by ofer-dev** [comment]
Nebula-cert already support similar operation. You can generate private and public keys on the host using "nebula-cert keygen" command and sign the public key on the offline CA using "nebula-cert sign"

**Comment by tarrenj** [comment]
> Nebula-cert already support similar operation. You can generate private and public keys on the host using "nebula-cert keygen" command and sign the public key on the offline CA using "nebula-cert sign".

Oh, well if that works then that's perfect! I'll test later this week and close this issue if successful.

**Comment by tarrenj** [comment]
@ofer-dev Thanks for the recommendation, it worked perfectly.
