### ISSUE TITLE
Will a connection work in a LAN without hairpining ?

### ISSUE THREAD

**Issue by rambip** [slackhq/nebula#605]
My router does not have a loopback interface, and I would like to know if a connection will work between 2 nodes on the same private network.

I don't understand how exactly does the lighthouse work, can you tell me if it will work for sure ?

**Comment by nbrownus** [comment]
Client nodes report the ip addresses they know they own to a lighthouse. Your lighthouse ideally is on the public internet, and if it is, will learn about the public ip address of client nodes talking to it (clients don't always know their public ip).

When a node A wants to connect to node B, it will ask the lighthouse for all known ip addresses for node B, then send handshake packets to all those ip addresses. As long as the handshake packet can arrive on any of the ip addresses, you will get a tunnel.

In some cases you the tunnel might be stood up under the less ideal route. Nebula will try to roam clients to what it believes the best path is and you can configure what the best route is here: https://github.com/slackhq/nebula/blob/e31006d546d0ec5914244c093fe19aad3606ead7/examples/config.yml#L125-L129
