### ISSUE TITLE
Report on certificate lifetime in prometheus metrics

### ISSUE THREAD

**Issue by benyanke** [slackhq/nebula#608]
It would be very useful to get the certificate expiry date/time in the prometheus metrics, so that administrators could write an prometheus alert to query which hosts need their certs renewed soon.

Is this functionality planned, or would it be accepted as a PR?

**Comment by nbrownus** [comment]
That makes a lot of sense and I don't think I had considered it before just now. Pretty easy to do and would certainly accept a PR for it.

**Comment by benyanke** [comment]
Thanks! I started the work here.

https://github.com/benyanke/nebula/tree/nebula-issue-608

**Comment by benyanke** [comment]
@nbrownus - I put up a PR (#613) which isn't quite ready for merge, but is 80% of the way there and seems to basically working.

How does it look at a high level? Is this the right general approach within the nebula code base, or should it be architected in a different way?

**Comment by johnmaguire** [comment]
Closed by #782.
