### ISSUE TITLE
panic: runtime error on arm7 32bit binary

### ISSUE THREAD

**Issue by SteveDevOps** [slackhq/nebula#62]
Hey guys, trying to fire up a lighthouse on an odroid hc1 armv7 board. Here is error I'm getting:

panic: runtime error: index out of range [3] with length 0

goroutine 1 [running]:
encoding/binary.bigEndian.Uint32(...)
	/usr/lib/go/src/encoding/binary/binary.go:111
github.com/slackhq/nebula.ip2int(...)
	/tmp/nebula/cidr_radix.go:140
github.com/slackhq/nebula.NewLightHouse(0xd20001, 0xa006401, 0xc0eb50, 0x1, 0x1, 0x3c, 0x1092, 0xc1ad4c, 0x0, 0x0)
	/tmp/nebula/lighthouse.go:50 +0x1ac
github.com/slackhq/nebula.Main(0xbee18901, 0xa, 0x0, 0x705d88, 0x5)
	/tmp/nebula/main.go:192 +0xe30
main.main()
	/tmp/nebula/cmd/nebula/main.go:42 +0x1e4

last successful message: INFO[0000] UDP hole punching enabled  

I'm on a custom debian-stretch image with 4.14.127 kernel

**Comment by nbrownus** [comment]
Can your provide your config, specifically `lighthouse.hosts`?

**Comment by SteveDevOps** [comment]
I am using:
 hosts:
    - ""

**Comment by nbrownus** [comment]
That'd do it. I'll work up a PR here in a bit to catch this case and provide a better error. You can just leave out that part of the config and it should work fine though.

**Comment by SteveDevOps** [comment]
yep.. just figured that out... thx!

**Comment by nbrownus** [comment]
Should help future folks, thanks for reporting!
