### ISSUE TITLE
Android App: "config test error: private key is not a pair with public key in nebula cert"

### ISSUE THREAD

**Issue by stilsch** [slackhq/nebula#620]
I am getting "config test error: private key is not a pair with public key in nebula cert" while trying to connect to my site.

Steps to reproduce:

- Install latest nebula Android app from Playstore on Samsung S10e with Android 12.

- Export Certificate `S10.pub.bin` from the App, sign it via:
```
./nebula-cert sign -in-pub "/data/Sync/S10.pub.bin" -name "s10e_signed.pub.crt" -ip "192.168.100.4/24" -groups "phone"
RC=0
```

- verify it:
```
./nebula-cert verify  -crt s10e_signed.pub.crt.crt -ca ca.crt 
RC=0
```

- import it into the app. 

- App says **Valid=yes**

- Import `ca.crt` (same as used above for signing) into app

- App says **Valid=yes**

- SAVE

- App says: "config test error: private key is not a pair with public key in nebula cert"

- App-Log: Error while reading files [long path]: No such file or directory, errno=2

Any Ideas?

**Comment by tarrenj** [comment]
Assuming you've removed the contents of `[long path]` but it's actually included in the error message, can you post the filename it's trying to read please?  Is it attempting to read the CA or private key?

**Comment by schuft69** [comment]
![Screenshot_20220112-203556_Nebula](https://user-images.githubusercontent.com/3663262/149209534-1ca95669-73a9-4bc3-928a-914684521419.jpg)

**Comment by kden416** [comment]
Same problem. I set ca.crt and host.crt, but i can't see where can i choose host.key in application.
So i get error :

> time="2022-02-02T08:20:16Z" level=error msg="Failed to load certificate from config" error="private key is not a pair with public key in nebula cert"

**Comment by ppacory** [comment]
# Same problem on ios     




![IMG_2546](https://user-images.githubusercontent.com/996068/152656705-80ab1d19-1763-4fa1-89af-8dea970162a4.PNG)
![IMG_2547](https://user-images.githubusercontent.com/996068/152656707-f68dca11-8a6f-4497-98dd-15d2a53ddd1c.PNG)
![IMG_601486C7D363-1](https://user-images.githubusercontent.com/996068/152656734-5c29b604-a807-4476-bbd8-8d8a66b3accd.jpeg)

**Comment by ppacory** [comment]
Find the problem for me,  the answer :  https://github.com/DefinedNet/mobile_nebula/issues/48  

you have to be careful to stay on the public key page and not go back or the phone screen freezes ... etc. otherwise the public/private key changes and  you certified the wrong key.

**Comment by xxxserxxx** [comment]
Also note: if you're used to the desktop method, like me, you **can not** generate the priv/pub keys on the lighthouse and copy them over to mobile. You **must** use the private key the mobile app generates, copy **that** to your lighthouse and sign it, then copy the resulting cert back to your mobile app.

**Comment by JohnMaguire** [comment]
Hi - I'm closing this issue out as it's a mobile Nebula issue which should be reported at https://github.com/DefinedNet/mobile_nebula. Thanks @ppacory for providing the solution.

Recent versions of mobile Nebula should have resolved this bug, as well as allow for importing of a private key. This practice is not recommended as it potentially exposes to your private key to many systems. Cheers!
