### ISSUE TITLE
unsafe_routes not working on Windows

### ISSUE THREAD

**Issue by davidflowerday** [slackhq/nebula#622]
Hi,
I have a Linux node that has access to another subnet that I was trying to expose via Nebula. I have the Linux node configured correctly, and I verified this is working by accessing the subnet using Nebula on my Android device. Now I'm attempting to access that same subnet from a Windows node, but as soon as I add a route under `unsafe_routes` in the Windows configuration file I get the following error:
```
level=error msg="Failed to get a tun/tap device" error="route MTU not supported in Windows"
```

I attempted some diagnosis of this myself and I think I may have discovered the problem. That error is coming from here:
https://github.com/slackhq/nebula/blob/b5b9d33ee753b510b316f15b503ecb11209fdf9b/overlay/tun_windows.go#L22-L24

Looking at the history of the file, `newTun` used to take both a `routes` and an `unsafeRoutes` parameter. It looks to me like the `routes` parameter was removed, and the `unsafeRoutes` parameter was renamed to just `routes`. But, I think this check was meant for the (old, now-removed) routes parameter and shouldn't apply to the unsafe routes (and thus should have been removed). Is this correct?

https://github.com/slackhq/nebula/commit/467e605d5e3fae0325ce7f8453b541504dfa3444#diff-a9abb9f33571cd8be9210630f273adc0967167c4ba9c5e05d8ba418741e36584

I did remove this check and rebuilt on my local machine and it seems to work as expected, but I'm not sure if there's something else I'm missing.

Thanks for making Nebula! I'm new to it but am liking it a lot so far.

**Comment by ddemarco5** [comment]
I've seen this same issue (and fixed it in the same way)
Seems like the result of a refactor that wasn't 100% tested on windows.

I've just started working with this software, so I'm not too familiar with the codebase... but I imagine a regular contributor would be able to fix this without much issue... it just needs some eyes on it.

**Comment by westinpigott** [comment]
Using Nebula 1.5.0 on Windows resolved this for me.  Looks like there is already a fix in the code also, so will just wait for next release.
