### ISSUE TITLE
[Mac] Multiple NICs on same network doesn't work

### ISSUE THREAD

**Issue by NiceGuyIT** [slackhq/nebula#625]
I ran across a scenario where adding a 2nd connection (Ethernet) will cause Nebula to fail. The process is still running but I can't ping the lighthouse. I can reproduce this on a Mac by connecting to WiFi and then plugging in an Ethernet cable. Both connections get an IP on the same network and I'm assuming they have different metrics for the routing. It doesn't matter which interface is connected first. Connecting or turning on the 2nd interface causes Nebula to not route anything. This does **not** happen if the two networks have different IPs/routing.

I have Nebula running on Linux (openSUSE Leap 15.3) with multiple NICs, both bridged, and the problem doesn't appear. I don't know if that's because both interfaces are available when Nebula starts, or if it's because both interfaces have the same metric.

I haven't tested Windows.

Nebula v1.5.2 from GitHub releases.

I turned on debug logging but didn't see any errors or exceptions. If you need the logs, let me know and I'll see what I can do.

**Comment by goligo** [comment]
I tried to reproduce the issue, but didn't occur on my Mac. I already had Ethernet connected and enabled the Wifi-Interface, which received a different IP address on the same network as the Ethernet. Nebula lighthouse and other hosts can still be accessed.

**Comment by NiceGuyIT** [comment]
I couldn't reproduce on a Windows VM with 2 NICs.

I also couldn't reproduce on the Mac with 2 Ethernet Thunderbolt connections. I'll have to do more research to see if it's specific to WiFi or that physical network.

**Comment by NiceGuyIT** [comment]
After further testing, I was able to determine the network order is causing the problem. If I connect two Thunderbolt Ethernet adapters, the first one "Thunderbolt Ethernet" seems to be tied to Nebula. If I disconnect that cable, Nebula doesn't reconnect using the other interface. If I leave that one connected, I can disconnect "Thunderbolt Ethernet 2" and Nebula will stay connected.

If I change the network order in the network preferences or using `networksetup -ordernetworkservices`, then "Thunderbolt Ethernet 2" becomes the problem interface while "Thunderbolt Ethernet" can be disconnected without causing problems.

It doesn't matter if it's the Thunderbolt Ethernet or WiFi. It's the first network listed when Nebula starts. If that network interface is disconnected or not available, Nebula fails even if another network connection is available.

The nebula network is 172.25.0.0/13. I could not reproduce this problem when the Mac was on a 192.168.1.1/24 network. This fails when the Mac is on a 172.16.100.1/24 network. I'm not sure if this matters since the networks do not overlap.

I built Nebula from master to make sure I'm using the latest and the problem persists. How can I troubleshoot this? Is it possible to debug a live program? Where does Nebula detect a change in network interfaces?

**Comment by NiceGuyIT** [comment]
I got a M1 Mac and can't reproduce this problem. The current Mac is running macOS Monterey version 12.4. It's also running a different Ethernet adapter since the latest Macs have USB-C only.

The previous Mac had DNS configured inside the Nebula network. This Mac has DNS configured outside the network. I don't know plays a factor.

This Mac has Nebula v1.6.0 while the previous Mac had version has v1.5.2.

I have another Mac that can reproduce this problem. If I can dig into it deeper to determine the root cause, I'll reopen.
