### ISSUE TITLE
M1 Support

### ISSUE THREAD

**Issue by marcosrmendezthd** [slackhq/nebula#631]
Hi,

Can we add M1 support?

**Comment by jasikpark** [comment]
I installed nebula via Homebrew: (#630)

- `brew install nebula`
- and setup my nebula config in `/opt/homebrew/etc/nebula/config.yml`
- `brew services restart nebula` to add it to my boot services

```
❯ file $(which nebula)
/opt/homebrew/bin/nebula: sticky Mach-O 64-bit executable arm64
```

**Comment by nbrownus** [comment]
The `nebula` and `nebula-cert` binaries provided in the `nebula-darwin.zip` since v1.5.0 are universal, they natively support both arm64 and amd64.

https://github.com/slackhq/nebula/releases/tag/v1.5.0

**Comment by marcosrmendezthd** [comment]
awesome. thank you.
