### ISSUE TITLE
Nodes not able to ping each other

### ISSUE THREAD

**Issue by ewonchang** [slackhq/nebula#634]
I have a `lighthouse` in a cloud VM with public IP address; `laptop` in a home VLAN and `workstation` in another VLAN.

`lighthouse` 10.13.1.1
`workstation` 10.13.1.3 (LAN IP 10.12.1.6)
`laptop` 10.13.1.4 (LAN IP 10.12.2.221)

All machines are running the latest version of nebula and flavours of Linux. My configurations are minimal and are as follows:

My `lighthouse` config:
```
pki:
  ca: /opt/nebula/ca.crt
  cert: /opt/nebula/lighthouse.crt
  key: /opt/nebula/lighthouse.key
static_host_map:
  "10.13.1.1": ["vm_public_IP:4242"]
lighthouse:
  am_lighthouse: true
  interval: 60
listen:
  host: "[::]"
  port: 4242
punchy:
  punch: true
  respond: true
cipher: aes
tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:
logging:
  level: info
  format: text
firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: any
      proto: any
      host: any
```

My `workstation` and `laptop` config: (the only different part is cert and key files)
```
pki:
  ca: /home/ewon/nebula/ca.crt
  cert: /home/ewon/nebula/workstation.crt
  key: /home/ewon/nebula/workstation.key
static_host_map:
  "10.13.1.1": ["vm_public_IP:4242"]
lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "10.13.1.1"
listen:
  host: "[::]"
  port: 0
punchy:
  punch: true
  respond: true
cipher: aes
tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:
logging:
  level: info
  format: text
firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000
  outbound:
    - port: any
      proto: any
      host: any
  inbound:
    - port: any
      proto: any
      host: any
```

I can ping from nodes to lighthouse and vice versa. However, nodes cannot ping each other. If I ping from `laptop` to `workstation`, I get the following error messages on `laptop`:
```
...
ERRO[0018] Prevented a pending handshake race            certName=workstation fingerprint=5c0f3921e4fc49fc06b34fd2cc58a3242bfb69bde35728ef0219d466fcf0bb2c handshake="map[stage:1 style:ix_psk0]" initiatorIndex=526444663 issuer=b197e555563b8a4b5370b16b18dcc3ff4068caf3ec19818e86ff017ea1260845 remoteIndex=0 responderIndex=3029730967 udpAddr="10.12.1.6:45286" vpnIp=10.13.1.3
INFO[0019] Handshake timed out                           durationNs=8720123570 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=250451344 remoteIndex=0 udpAddrs="[home_public_IP:32907 10.12.1.6:45286]" vpnIp=10.13.1.3
INFO[0020] Handshake message received                    certName=workstation fingerprint=5c0f3921e4fc49fc06b34fd2cc58a3242bfb69bde35728ef0219d466fcf0bb2c handshake="map[stage:1 style:ix_psk0]" initiatorIndex=526444663 issuer=b197e555563b8a4b5370b16b18dcc3ff4068caf3ec19818e86ff017ea1260845 remoteIndex=0 responderIndex=0 udpAddr="10.12.1.6:45286" vpnIp=10.13.1.3
INFO[0020] Handshake message sent                        certName=workstation fingerprint=5c0f3921e4fc49fc06b34fd2cc58a3242bfb69bde35728ef0219d466fcf0bb2c handshake="map[stage:2 style:ix_psk0]" initiatorIndex=526444663 issuer=b197e555563b8a4b5370b16b18dcc3ff4068caf3ec19818e86ff017ea1260845 remoteIndex=0 responderIndex=286921894 sentCachedPackets=0 udpAddr="10.12.1.6:45286" vpnIp=10.13.1.3
...                                                              
```

and on my `workstation` I have the following "info" messages:
```
...
INFO[0018] Handshake message sent                        handshake="map[stage:1 style:ix_psk0]" initiatorIndex=526444663 udpAddrs="[home_public_IP:12583 10.12.2.210:59517 10.12.2.211:59517 192.168.122.1:59517]" vpnIp=10.13.1.4
INFO[0020] Handshake timed out                           durationNs=10182400905 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=526444663 remoteIndex=0 udpAddrs="[home_public_IP:12583 10.12.2.210:59517 10.12.2.211:59517 192.168.122.1:59517]" vpnIp=10.13.1.4
...
```
The logs on `lighthouse` is only the following:
```
root@vm:/opt/nebula# ./nebula -config lighthouse.config.yml
INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:outgoing endPort:0 groups:[] host:any ip: proto:0 startPort:0]"
INFO[0000] Firewall rule added                           firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host:any ip: proto:0 startPort:0]"
INFO[0000] Firewall started                              firewallHash=21716b47a7a140e448077fe66c31b4b42f232e996818d7dd1c6c4991e066dbdb
INFO[0000] Main HostMap created                          network=10.13.1.1/24 preferredRanges="[]"
INFO[0000] UDP hole punching enabled
INFO[0000] Nebula interface is active                    build=1.5.2 interface=nebula1 network=10.13.1.1/24 udpAddr="[::]:4242"
INFO[0006] Handshake message received                    certName=laptop fingerprint=ea008f0243fbeb44254732ec24fd35fa729f1da67920f5c705ef73dced83a5b8 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=392725562 issuer=b197e555563b8a4b5370b16b18dcc3ff4068caf3ec19818e86ff017ea1260845 remoteIndex=0 responderIndex=0 udpAddr="vm_public_IP:12583" vpnIp=10.13.1.4
INFO[0006] Handshake message sent                        certName=laptop fingerprint=ea008f0243fbeb44254732ec24fd35fa729f1da67920f5c705ef73dced83a5b8 handshake="map[stage:2 style:ix_psk0]" initiatorIndex=392725562 issuer=b197e555563b8a4b5370b16b18dcc3ff4068caf3ec19818e86ff017ea1260845 remoteIndex=0 responderIndex=2000406661 sentCachedPackets=0 udpAddr="vm_public_IP:12583" vpnIp=10.13.1.4
INFO[0011] Handshake message received                    certName=workstation fingerprint=5c0f3921e4fc49fc06b34fd2cc58a3242bfb69bde35728ef0219d466fcf0bb2c handshake="map[stage:1 style:ix_psk0]" initiatorIndex=792326294 issuer=b197e555563b8a4b5370b16b18dcc3ff4068caf3ec19818e86ff017ea1260845 remoteIndex=0 responderIndex=0 udpAddr="vm_public_IP:32907" vpnIp=10.13.1.3
INFO[0011] Handshake message sent                        certName=workstation fingerprint=5c0f3921e4fc49fc06b34fd2cc58a3242bfb69bde35728ef0219d466fcf0bb2c handshake="map[stage:2 style:ix_psk0]" initiatorIndex=792326294 issuer=b197e555563b8a4b5370b16b18dcc3ff4068caf3ec19818e86ff017ea1260845 remoteIndex=0 responderIndex=154643726 sentCachedPackets=0 udpAddr="vm_public_IP:32907" vpnIp=10.13.1.3
```

So it seems nodes *can* receive the requests from each other, but why ping (and ssh) won't work? I made sure that `workstation` and `laptop` has no firewall rules in place. There's no YAML syntax error either.

**Comment by tcurdt** [comment]
I am not sure if this applicable here - but stumbled across the fact that the firewall on the lighthouse also needs to allow the traffic in the nebula network. I didn't think it was relevant - but it is. HTH

**Comment by ewonchang** [comment]
> I am not sure if this applicable here - but stumbled across the fact that the firewall on the lighthouse also needs to allow the traffic in the nebula network. I didn't think it was relevant - but it is. HTH

My lighthouse has UDP/4242 open and that's pretty much the end of the story. Lighthouse and nodes can talk, the problem is between nodes.

**Comment by tcurdt** [comment]
Nebula was built without host based firewalls in mind. They run it on AWS and use the firewall on a different level.
I had to allow my overlay network `sudo ufw allow from 10.0.0.0/8 to 10.0.0.0/8`.

**Comment by NikaZhenya** [comment]
Hi, @ewonchang, can you resolve your issue? I am experimenting exactly the same of what you said...

**Comment by KillianKemps** [comment]
I don't know if it helps but I'm encountering a similar issue with a different context.
The servers were running Wireguard and I was migrating to Nebula. The Nebula installation worked well while Wireguard (using wg-quick) was still active on all servers. The servers could ping between them with their Nebula IP : server to lighthouse, server to server in the same internal network and server to server on different networks.

Once I disabled Wireguard, the Nebula connection behaved differently. I could still ping between machines in the same internal network and to the lighthouses with the Nebula IP, but no more between machines on different networks.

In my case, I still haven't fixed my issue, but Nebula works again when the Wireguard interface is up again. I suspect some kind of IP redirection wg-quick may do.

**Comment by joshaspinall** [comment]
Folks, if you haven't already, check out the issue here: #666 

@ewonchang your configuration looks to be the same as others that have commented.  Try the solution linked and see how you get on.  @KillianKemps I haven't seen your configs, but have a look too.

Please report back how you get on!

**Comment by ewonchang** [comment]
> Folks, if you haven't already, check out the issue here: #666
> 
> @ewonchang your configuration looks to be the same as others that have commented. Try the solution linked and see how you get on. @KillianKemps I haven't seen your configs, but have a look too.
> 
> Please report back how you get on!

Thanks. I will have a look after this long weekend

**Comment by KillianKemps** [comment]
@joshaspinall I tried your configuration with `punchy: true` and `punch_back: true` and it didn't fix the issue.
From what I understand, these parameters are deprecated: https://github.com/slackhq/nebula/blob/b5b9d33ee753b510b316f15b503ecb11209fdf9b/CHANGELOG.md#deprecated-2

`punch_back` has been replaced by `respond`, even though it still works and has been kept backward compatible.

**Comment by joshaspinall** [comment]
Thanks @KillianKemps I was not aware that these options had changed.  Both options should work, for the moment at least!

Looking through your configs in more detail, are you certain that your client certs are using separate IP addresses?  I've seen your result when accidentally having two devices sharing an IP.

**Comment by brad-defined** [comment]
From the logs you provided, it looks like the `laptop` can receive packets from the `workstation`:
>INFO[0020] Handshake message received  -snip- udpAddr="10.12.1.6:45286" -snip-

But the `workstation` is not receiving UDP packets from the `laptop` - even though the `laptop` sent a handshake packet.
> INFO[0020] Handshake message sent -snip- udpAddr="10.12.1.6:45286" -snip-


It looks like these hosts should be able to communicate between their VLANS - can they? Can these hosts ping each other? Or do you expect that they can not communicate directly with each other?

there may be something wrong with the VLAN networking / routes, or with firewall on the workstation?

**Comment by bvmanuelpaillafil** [comment]
Ehlo!!

I have the same problem and i've tried many solutions but the communications between host don't succeed.

**Comment by NikaZhenya** [comment]
> I don't know if it helps but I'm encountering a similar issue with a different context. The servers were running Wireguard and I was migrating to Nebula. The Nebula installation worked well while Wireguard (using wg-quick) was still active on all servers. The servers could ping between them with their Nebula IP : server to lighthouse, server to server in the same internal network and server to server on different networks.
> 
> Once I disabled Wireguard, the Nebula connection behaved differently. I could still ping between machines in the same internal network and to the lighthouses with the Nebula IP, but no more between machines on different networks.
> 
> In my case, I still haven't fixed my issue, but Nebula works again when the Wireguard interface is up again. I suspect some kind of IP redirection wg-quick may do.
> 
> Edit: to be more precise it is the `AllowedIPs` parameter in the wg-quick configuration file which allows Nebula to work besides Wireguard. When I remove it, the Nebula connection doesn't work anymore. However, when I remove this parameter and try to reproduce manually the `ip route` commands run by wg-quick, it is not sufficient to make Nebula work.

Hi, this is relevant for my case since I have wireguard (on a docker container) and nebula in the lighthouse. I can't ping between machines on different network, only on the same network or with the lighthouse. I stop the container to see if there was some change and still I am in the same situation. Can I see your config so I can compare to mine?

Thanks

**Comment by ewonchang** [comment]
Ok, after putting up with this issue for many months due to my laziness, I can finally close it.
My issue is exactly the same as described in #666, nodes behind NAT cannot talk to other nodes. In particular, a Linux laptop behind pfSense router is not able to ping other nodes (can only ping the lighthouse)

I used this [tool](https://github.com/slackhq/nebula/issues/666#issuecomment-1115399016 to verify it's a NAT problem on the laptop.

This blog [post](https://blog.ktz.me/punching-through-nat-with-nebula-mesh/) gives the solutions

More discussion in [discord](https://discord.com/channels/693469700109369394/693473676527403048/882039853368348802)

For pfSense, outbound rules and static port option can be found in the [docs](https://docs.netgate.com/pfsense/en/latest/nat/outbound.html#static-port)

Closing.
