### ISSUE TITLE
Nodes can't ping lighthouse but lighthouse can

### ISSUE THREAD

**Issue by smeana** [slackhq/nebula#639]
Hello 

On a new 10 nodes installation, nodes can't ping lighthouse, but the lighthouse can ping them. 
After the pinging from the LH, they are able to ping lighthouse and each other node fine and the mesh works fine.

From the logs I can't see any issue, all the nodes do a correct initial handshake with the lighthouses and the firewall is open to any port, and any protocol.

This never happened to me before, I am not able to find why they cannot ping lighthouse initially.

Regards

**Comment by davisdan** [comment]
Did you ever work out a resolution to this issue? I'm having the same problem, hosts can connect but no traffic flows to the newly connected host until I initiate some traffic from the Lighthouse such as a ping.

With Lighthouse running and Nebula host started I get 'Handshake Message Sent' followed by 'Handshake Message Received' but no traffic flows until I ping the host from the Lighthouse. In the Lighthouse logs I see 'Handshake Message Received' followed by 'Handshake Message Sent' when the host connects as expected. I have tried with punch-back and respond set to true but neither have made any difference.

All nodes are running 1.6.0

Lighthouse Config:
`pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/lh.crt
  key: /etc/nebula/lh.key
static_host_map:


lighthouse:
  am_lighthouse: true
  serve_dns: true
  dns:
    host: a.a.a.a
    port: 53
  interval: 60
  hosts:

listen:
  host: a.a.a.a
  port: 4242

punchy:
  punch: true
  #respond: true
  #punch_back: true
  delay: 1s

cipher: chachapoly

relay:
  am_relay: false
  use_relays: true

tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:

logging:
  level: info
  format: text

firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: icmp
      host: any

  inbound:
    - port: 53
      proto: udp
      host: any
`

Host Config:
`pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/host.crt
  key: /etc/nebula/host.key

static_host_map:
  "172.20.5.1": ["a.a.a.a:4242"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "172.20.5.1"

listen:
  host: 0.0.0.0
  port: 0

punchy:
  punch: true
  #punch-back: true
  respond: true

cipher: chachapoly

relay:
  am_relay: false
  use_relays: true

tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:

logging:
  level: info
  format: text

firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: icmp
      host: any
`

**Comment by JohnMaguire** [comment]
Closing this as stale as the original poster did not respond. Please open a new ticket if you're experiencing issues.
