### ISSUE TITLE
Nebula stopped to work after CA expiration

### ISSUE THREAD

**Issue by NerijusRazvodovskis** [slackhq/nebula#645]
Hello,

after CA expiration, nebula network hosts stopped to work (firewall rules were not working with the old sessions). Maybe someone encountered the same issue? Or maybe someone knows the reason why could it happen?

The version I'm using is v1.5.0

**Comment by peteh** [comment]
Expired certificates are expired and are therefore not considered valid anymore. So technically thats probably already your answer.

**Comment by jasikpark** [comment]
If `stopped to work` means you couldn't connect to things anymore, peteh is right since expiring CAs mean those are invalid & you can't trust them anymore

**Comment by jasikpark** [comment]
basically, every host has a list of CAs in <https://www.defined.net/nebula/config/#pki-ca> that describe which CAs they trust & any host they talk to must have a certificate signed by a CA in their trusted CAs list.

if a CA expires, then it is no longer trusted, and only certificates signed by a new CA or another already trusted CA will be able to be communicated with

**Comment by JohnMaguire** [comment]
Closing this ticket as it does not look like a bug. Please let me know if we can offer any additional assistance.
