### ISSUE TITLE
ping, no ssh

### ISSUE THREAD

**Issue by AquaMCU** [slackhq/nebula#65]
I am trying out nebula on a light tower on DO and two clients. I can ping the light tower as well as the other client, but I can not ssh into them. Do I need to open the ssh port or something?

Oliver

P.s. The port rules are the ones of the example

firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  # The firewall is default deny. There is no way to write a deny rule.
  # Rules are comprised of a protocol, port, and one or more of host, group, or CIDR
  # Logical evaluation is roughly: port AND proto AND ca_sha AND ca_name AND (host OR group OR groups OR cidr)
  # - port: Takes `0` or `any` as any, a single number `80`, a range `200-901`, or `fragment` to match second and further fragments of fragmented packets (since there is no port available).
  #   code: same as port but makes more sense when talking about ICMP, TODO: this is not currently implemented in a way that works, use `any`
  #   proto: `any`, `tcp`, `udp`, or `icmp`
  #   host: `any` or a literal hostname, ie `test-host`
  #   group: `any` or a literal group name, ie `default-group`
  #   groups: Same as group but accepts a list of values. Multiple values are AND'd together and a certificate would have to contain all groups to pass
  #   cidr: a CIDR, `0.0.0.0/0` is any.
  #   ca_name: An issuing CA name
  #   ca_sha: An issuing CA shasum

  outbound:
    # Allow all outbound traffic from this node
    - port: any
      proto: any
      host: any

  inbound:
    # Allow icmp between any nebula hosts
    - port: any
      proto: icmp
      host: any

    # Allow tcp/443 from any host with BOTH laptop and home group
    - port: 443
      proto: tcp
      groups:
        - laptop
        - home

**Comment by villain** [comment]
you need an inbound rule to allow ssh, you only have icmp allowed

```
  inbound:
    # Allow icmp between any nebula hosts
    - port: 22
      proto: tcp
      host: any
```

**Comment by AquaMCU** [comment]
AHH. That did the trick! Thanks.

BTW: This is awesome! I already gave nebula as a tip to a friend
