### ISSUE TITLE
Is it possible to use UDPspeeder to improves network quality?

### ISSUE THREAD

**Issue by yinheli** [slackhq/nebula#652]
UDPspeeder refer: https://github.com/wangyu-/UDPspeeder

If the listen port which export to Lighthouse is customizable (difference to the real listen port) the feature would be supported theoretically.

**Comment by nbrownus** [comment]
Reporting different ports/ips would be enabled by this PR https://github.com/slackhq/nebula/pull/650

**Comment by yinheli** [comment]
awesome
