### ISSUE TITLE
[Feature Request] Add destination network in firewall rule

### ISSUE THREAD

**Issue by rucciva** [slackhq/nebula#654]
Currently, when exposing `unsafe_route`, the firewall rule does not only apply to the nebula node but also to the unsafe_route. This could be avoided If there is additional component of firewall rule that denotes the target network e.g. `dst_cidr`, hence the firewall policy will be `port AND proto AND (ca_sha OR ca_name) AND (host OR group OR groups OR cidr) and dst_cidr` . Since only the nebula node knows full information of both the source and the destination of packet (especially the nebula host, group, and ca), firewall defined on nebula node will be more granular than adding firewall from external system such as iptables.

**Comment by jstasiak** [comment]
I suspect this already merged and released change resolves this issue: https://github.com/slackhq/nebula/pull/507

**Comment by johnmaguire** [comment]
@jstasiak Thank you! Indeed, `local_cidr` can now be used to restrict which local IPs a firewall rule applies to. See [the firewall docs](https://nebula.defined.net/docs/config/firewall/) for more info.
