### ISSUE TITLE
Wintun changes do not work on v1.5.2

### ISSUE THREAD

**Issue by chirayu-patel** [slackhq/nebula#661]
I downloaded the latest windows release v1.5.2 and tried running the normal command but I get the message : "Failed to get a tun/tap device". The exact same way if I run v1.5.0, it works

Has something changed between the 2 versions ?

**Comment by chirayu-patel** [comment]
Hi,

Can anyone please check if there is a similar observation OR I am doing something wrong

**Comment by nbrownus** [comment]
Mind posting the entire log line? Are you using `unsafe_routes`?

**Comment by chirayu-patel** [comment]
time="2022-04-20T23:03:38+05:30" level=error msg="Failed to get a tun/tap device" error="route MTU not supported in Windows"

**Comment by wadey** [comment]
This was fixed with #648 , but is currently unreleased. Stick on v1.5.0 until we can tag the next release which should be in the next few weeks.

**Comment by chirayu-patel** [comment]
And yes the config had unsafe routes but as soon as i removed it, it started working..  has something changed in this version related to unsafe routes ?
