### ISSUE TITLE
Failed to get a tun/tap device" error="route MTU not supported in Windows

### ISSUE THREAD

**Issue by itservices-tanger** [slackhq/nebula#665]
on windows 10, with 1.5.2, as soon as I add unsafe_routes I get the error: 
Failed to get a tun/tap device" error="route MTU not supported in Windows
I had to revert back to 1.5.0
on Linux everything is fine.

**Comment by wadey** [comment]
This was fixed with #648 , currently unreleased but it will be in the next one.
