### ISSUE TITLE
Problem with clients behind the "residential NAT"

### ISSUE THREAD

**Issue by cdspacedos** [slackhq/nebula#666]
Hello Everyone,

I'm new to Nebula, so apologies upfront for the asking/repeating questions. I have a user behind the "residential NAT", and upon connecting to the overlay network, that user can only ping the Lighthouse host (and vice versa), but not other peers in the network. Is there any configuration tip to overcome this problem?

I would eventually use Nebula to connect with a few hundred users worldwide, and I cannot ask them to change their network configuration.

**Comment by joshaspinall** [comment]
I use Nebula in the same manner, and while I occasionally see a hiccup it has been very reliable. I have devices at different houses behind residential NAT, and mobile as well.

Are you using the example config tweaked to suit? Any specific options set?

**Comment by cdspacedos** [comment]
I'm using the example configuration with minimal changes to reflect the public IP address of the lighthouse, the private subnet (in my case 192.156.255.0/24). At the client side I've been configuring options in the "punchy" section hoping that this might help with the CGNAT.

I've attached the sample client + lighthouse configuration file.

[config-short.txt](https://github.com/slackhq/nebula/files/8473641/config-short.txt)
[lighthouse-short.txt](https://github.com/slackhq/nebula/files/8473642/lighthouse-short.txt)

**Comment by cdspacedos** [comment]
Properly configuring the "punchy" section did the trick. Now the clients behind the CGNAT can reach each other. 
Thank you very much for your help @joshaspinall !

I still have to figure out the systemd start/stop scripts for Nebula as I'm using Ubuntu 20.04, but that's going to be easy.

If nobody has any comments/questions, I will close this issue.

**Comment by joshaspinall** [comment]
Happy to help!  Glad that you're up and running successfully.  Please close down when you're ready.

There's an example systemd/init service file in the repo [here](https://github.com/slackhq/nebula/tree/master/examples/service_scripts).

**Comment by IceWreck** [comment]
> Double check the syntax of the `punchy` entry, see mine below. Also, try adding the `punch_back` option, which may be the setting that will help your clients connect.
> 
> `punchy: true` `punch_back: true`


I don't see a reference to  punch_back: true and the punch syntax is different in the example config. Is one of these new ?

**Comment by bouillon** [comment]
Ok, for me is still not woks.
I have the near the same configs

```
punchy:
  punch: true
  punch_back: true
  respond: true
  delay: 1s
```

On lighthouse and hosts.

[lighthouse.txt](https://github.com/slackhq/nebula/files/8492330/lighthouse.txt)
[hosts.txt](https://github.com/slackhq/nebula/files/8492331/hosts.txt)

Can connect only from lighthouse.
Ok may be my network is little bit more complex as i wrote before [hier](https://github.com/slackhq/nebula/issues/666#issuecomment-1096356444) 

like

Fritzbox (router) -> Router (for Wifi) -> Clients
the other side
Mobile Huawei router -> Router (for Wifi) -> Clients

So i have two router on both sides.

Lighthouse logs have some timeouts

апр 14 23:22:45 monitoring nebula-vav_network[207428]: time="2022-04-14T23:22:45+02:00" level=info msg="Nebula interface is active" build= interface=nebula1 network=192.168.100.1/24 udpAddr="0.0.0.0:4242"
апр 14 23:22:46 monitoring nebula-vav_network[207428]: time="2022-04-14T23:22:46+02:00" level=info msg="Handshake message received" certName=kot fingerprint=ab2a01c247fec220581b98fe60ca586d2c5fb21d619cdcb4227c19a7ad84658e handshake="map[stage:1 style:ix_psk0]" initiatorIndex=3528524073 remoteIndex=0 responderIndex=0 udpAddr="109.43.XX.XX:7839" vpnIp=192.168.100.100
апр 14 23:22:46 monitoring nebula-vav_network[207428]: time="2022-04-14T23:22:46+02:00" level=info msg="Handshake message sent" certName=kot fingerprint=ab2a01c247fec220581b98fe60ca586d2c5fb21d619cdcb4227c19a7ad84658e handshake="map[stage:2 style:ix_psk0]" initiatorIndex=3528524073 remoteIndex=0 responderIndex=2350676238 sentCachedPackets=0 udpAddr="109.43.XX.XX:7839" vpnIp=192.168.100.100
апр 14 23:22:59 monitoring nebula-vav_network[207428]: time="2022-04-14T23:22:59+02:00" level=info msg="Handshake message received" certName=isar fingerprint=bb29d7e8434292ba209fe7532905d7565271bf825e959bb3573d920996ce6063 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=692309219 remoteIndex=0 responderIndex=0 udpAddr="88.217.XX.XX:4242" vpnIp=192.168.100.101
апр 14 23:22:59 monitoring nebula-vav_network[207428]: time="2022-04-14T23:22:59+02:00" level=info msg="Handshake race lost, replacing pending handshake with completed tunnel" vpnIp=192.168.100.101
апр 14 23:22:59 monitoring nebula-vav_network[207428]: time="2022-04-14T23:22:59+02:00" level=info msg="Handshake message sent" certName=isar fingerprint=bb29d7e8434292ba209fe7532905d7565271bf825e959bb3573d920996ce6063 handshake="map[stage:2 style:ix_psk0]" initiatorIndex=692309219 remoteIndex=0 responderIndex=1763604980 sentCachedPackets=3 udpAddr="88.217.XX.XX:4242" vpnIp=192.168.100.101
апр 14 23:23:17 monitoring nebula-vav_network[207428]: time="2022-04-14T23:23:17+02:00" level=info msg="Handshake timed out" durationNs=9456964106 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=2136526631 remoteIndex=0 udpAddrs="[]" vpnIp=192.168.100.2
апр 14 23:23:38 monitoring nebula-vav_network[207428]: time="2022-04-14T23:23:38+02:00" level=info msg="Handshake message received" certName=stakan fingerprint=7a4d6fa0e6c5c88ffad6ec65084d454cc4b692681dadddb166f29d74849ff9bb handshake="map[stage:1 style:ix_psk0]" initiatorIndex=1727675021 remoteIndex=0 responderIndex=0 udpAddr="88.217.XX.XX:1026" vpnIp=192.168.100.2
апр 14 23:23:38 monitoring nebula-vav_network[207428]: time="2022-04-14T23:23:38+02:00" level=info msg="Handshake message sent" certName=stakan fingerprint=7a4d6fa0e6c5c88ffad6ec65084d454cc4b692681dadddb166f29d74849ff9bb handshake="map[stage:2 style:ix_psk0]" initiatorIndex=1727675021 remoteIndex=0 responderIndex=3180317803 sentCachedPackets=0 udpAddr="88.217.XX.XX:1026" vpnIp=192.168.100.2
апр 14 23:24:50 monitoring nebula-vav_network[207428]: time="2022-04-14T23:24:50+02:00" level=info msg="Handshake timed out" durationNs=9101206831 handshake="map[stage:1 style:ix_psk0]" initiatorIndex=332034963 remoteIndex=0 udpAddrs="[]" vpnIp=192.168.100.102
~
~
~
`
`

**Comment by joshaspinall** [comment]
@bouillon as with cdspacedos, your syntax is not 'correct' (despite being different to the example file).

Change:
`punchy:`
  `punch: true`
  `punch_back: true`
  `respond: true`
  `delay: 1s`

to:
`punchy: true`
`punch_back: true`
`respond: true`
`delay: 1s`

Please report back how you get on!

**Comment by chirayu-patel** [comment]
I guess there is no issue in syntax, punchy.respond and punchy.punch have been kept backward compatible along with the new config.  You can refer to punchy.go for the same.

I have faced similar issues with the NAT layer existing on both the sides. It just doesn't work.

Zerotier in the same setup is somehow able to make it work. :(

Anyways, cant do much. As of now, I am planning to implement my own relay in such cases using additional routing hop through the lighthouse.

**Comment by chirayu-patel** [comment]
Also, wanted to know , has any one of you used windows client on v1.5.2 ? I get the message : "Failed to get a tun/tap device". The exact same way if I run v1.5.0, it works.

I have raised a separate issue for the same since sometime but no one is responding on that.

Can someone please let me know. 
Thanks

**Comment by bouillon** [comment]
@chirayu-patel i not use windows, only linux clients
@joshaspinall reporting back. Not working. Same issue. Changing to 
punchy: true
punch_back: true
respond: true
delay: 1s

**Comment by DePingus** [comment]
If you're using OPNsense or PFsense have a look here: https://blog.ktz.me/punching-through-nat-with-nebula-mesh/

The reason ZeroTier works is because when ZT fails to punch through UDP, it will fall back to using the moon as a relay. Nebula doesn't have a relay mode.

**Comment by bouillon** [comment]
i'm not using OPNSENSE or PFsense.

**Comment by brad-defined** [comment]
```
% go install github.com/pion/stun/cmd/stun-nat-behaviour@v0.3.5
% stun-nat-behaviour 2>&1 | grep "NAT mapping"
```
NAT's come in many flavors, and Nebula works great even with both peers behind many types of NAT's, but not all. If you run these commands on a Nebula instance that is having trouble connecting to other Nebula peers and get `NAT mapping behavior`: `address dependent` or `address and port dependent`, then I think punchy will not be able to get UDP packets to flow to each other in all cases.

In the `dependent` cases, Nebula will still work if:
- both peers have IPv6 addresses (and you're using the Nebula version that supports IPv6)
- OR if the other peer isn't behind a NAT - meaning it has a public internet IP & firewall that permits unsolicited inbound traffic to the Nebula port (like the lighthouse.)

If you run that command and get `NAT mapping behavior: endpoint-independent` on _both_ peers behind NATs, then Nebula's punchy should work great, and you're likely encountering some other networking issue preventing the Nebula UDP packets from getting where they need to go.

**Comment by jasikpark** [comment]
> If you're using OPNsense or PFsense have a look here: [blog.ktz.me/punching-through-nat-with-nebula-mesh](https://blog.ktz.me/punching-through-nat-with-nebula-mesh/)
> 
> The reason ZeroTier works is because when ZT fails to punch through UDP, it will fall back to using the moon as a relay. Nebula doesn't have a relay mode.

#678 is working on adding experimental support at some point; hopefully, that'll improve things?

**Comment by DePingus** [comment]
Excellent news! Will the mobile apps still work with 1.6.0? Or should we wait for those apps to be updated before upgrading the rest of the lighthouse?

**Comment by brad-defined** [comment]
You can update the rest of your nodes to 1.6 without waiting for the mobile update, which will take a couple weeks to push out. But, you may have access issues from mobile in the meantime.

**Comment by JohnMaguire** [comment]
FWIW, the mobile apps have been updated to support relays!

At this time, I'm closing this out for inactivity. If you continue to have issues after trying the relay feature, pleasefeel free to open up a new issue or [join us on Slack](https://join.slack.com/t/nebulaoss/shared_invite/enQtOTA5MDI4NDg3MTg4LTkwY2EwNTI4NzQyMzc0M2ZlODBjNWI3NTY1MzhiOThiMmZlZjVkMTI0NGY4YTMyNjUwMWEyNzNkZTJmYzQxOGU). Thanks!
