### ISSUE TITLE
How to get a list of connected hosts? or network hosts?

### ISSUE THREAD

**Issue by drno88** [slackhq/nebula#668]
Good day.
First of all, thank you for what you do!

We want to try to get away from VPN in our standard use. But our administrators are used to seeing a list of connected hosts in order to understand who is online and who is offline.
Is there any command for this, for example, on a lighthouse?

Do you also plan to make a simple web interface - for adding / deleting clients, viewing "who is online"?

**Comment by brad-defined** [comment]
https://www.defined.net/nebula/config/#sshd

Check out the sshd configuration setting - it runs an in-memory SSHd server in the nebula process, which supports a number of troubleshooting commands.

If you enable this on your lighthouse, then you can run something like list-hostmap to get a dump of established tunnels.

**Comment by JohnMaguire** [comment]
Closing as solved. Let us know if the sshd solution doesn't do what you want.
