### ISSUE TITLE
Running on OPNSense

### ISSUE THREAD

**Issue by thenitai** [slackhq/nebula#669]
Hi all,

Does anyone have Nebula installed on the OPNSense itself? I almost have it, but it fails in creating a TUN. It's based on FreeBSD 13 and kinda restrictive (obviously). That said, I see packages for Tailscale and Zerotier...

**Comment by thenitai** [comment]
Oh, some kind soul at Slack already created an OPN ports package. Compiled, installed, and everything works perfectly. Thank you 👍

**Comment by djarbz** [comment]
> Oh, some kind soul at Slack already created an OPN ports package. Compiled, installed, and everything works perfectly. Thank you 👍

Do you have a link to that package? I tried searching Slack, but I couldn't find it.
