### ISSUE TITLE
What is the typical setup of nebula? Install nebula on every host if possible?

### ISSUE THREAD

**Issue by Tony2** [slackhq/nebula#672]
I apologize if this is not the right place to ask this question.

I read through various docs I could find but it's not clear what is the typical/recommended setup of nebula: one single huge flat net with nebula installed on every node, except where it's not possible (unsupported devices like printer)?

**Comment by virtadpt** [comment]
That does seem to be how most people use Nebula: To string them into a distributed network when they're not close to each other.  It's more of an "expose services to those hosts" thing than an "access those hosts" thing.

**Comment by JohnMaguire** [comment]
Yes, that's correct. Nebula should be installed on every node that you want accessible on the network, or that you want to have access to the network. For devices like printers you can take a look at unsafe_routes.
