### ISSUE TITLE
iOS App for Japan is not available

### ISSUE THREAD

**Issue by nanozuki** [slackhq/nebula#676]
I am an iOS user in Japan, I found that I can't install nebula for my new device:

![IMAGE 2022-05-05 15:44:54](https://user-images.githubusercontent.com/4208028/166881312-4c22a70a-b25d-4b68-979e-845e8389fb27.jpg)

<img width="295" alt="image" src="https://user-images.githubusercontent.com/4208028/166881450-80350ca4-85c1-4373-a3a1-dab858f4ddfd.png">

Is nebula no longer supporting Japanese iOS devices?

**Comment by btobolaski** [comment]
It is also not available in the US App Store so, it isn’t just the Japanese market.

**Comment by jasikpark** [comment]
> It is also not available in the US App Store so, it isn’t just the Japanese market.  

I'm pretty sure it is? - https://apps.apple.com/us/app/mobile-nebula/id1509587936?itsct=apps_box&itscg=30200 is the link in the readme

**Comment by btobolaski** [comment]
I just clicked the link again and this is what I get 
![1AF250EC-8D05-4B01-8966-0B04CED0D6F5](https://user-images.githubusercontent.com/363694/166950269-af4c8d5c-a3bd-4dfc-804b-26b18a9b9b0a.png)

**Comment by jasikpark** [comment]
currently available on US app store again, like nbrownus said: https://apps.apple.com/us/app/mobile-nebula/id1509587936

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/10626596/170718379-f6fc93d9-2060-4407-91f2-7e2e7d7d9b91.png">

I tried to find it on the japan app store, but a VPN didn't do me much good; switching out `us` with `jp` in the URL timed out

**Comment by jasikpark** [comment]
Closing this, as I believe the app is once again available on both the US and Japan app stores
