### ISSUE TITLE
Remove `x509.cert`/`x509.key` fallbacks?

### ISSUE THREAD

**Issue by jasikpark** [slackhq/nebula#683]
https://github.com/slackhq/nebula/blob/1110756f0f2ea751f0df6aa7ce623ffdad33c63d/cert.go#L55-L57

lists a fallback for supporting x509 keys w/ a comment from 2018 describing that this should be removed when it's gone; is that possible today?

**Comment by wadey** [comment]
We removed x509.ca in #604 so we can probably remove these now too

**Comment by wadey** [comment]
ah my bad, it was #599 that removed `x509.ca` (looks like we got it wrong in the changelog)

**Comment by jasikpark** [comment]
Ah, so `x509` doesn't actually work anymore? There's just zombie config code essentially?

**Comment by jasikpark** [comment]
> does
> 
> https://github.com/slackhq/nebula/blob/1110756f0f2ea751f0df6aa7ce623ffdad33c63d/cert.go#L74-L79
> 
> cause go variable shadowing of `rawKey` so I can remove the above declaration in my removal PR?

🤦 no it doesn't b/c that's `rawCert` not `rawKey`
