### ISSUE TITLE
(Wrong?) speed report for nebular-iface

### ISSUE THREAD

**Issue by psi-4ward** [slackhq/nebula#686]
Hi,
I'm running a prometheus node_exporter on machines with nebula and discovered that:

```
# cat /sys/class/net/nebula1/speed
10
```

and wondered why nebula reports 10Mbit here (which leads to wrong alerts when calculating thinks like network saturation).
Is this confable?

**Comment by nbrownus** [comment]
This is the behavior of the linux tun driver. Last I checked you couldn't change it and it was meaningless to the performance of nebula.

Network saturation can be determined by watching the actual NIC stats and/or the udp buffers reported by nebula or the tun tx queue length reported by the system.
