### ISSUE TITLE
will TAP devices be supported in addition to TUN devices

### ISSUE THREAD

**Issue by bmullan** [slackhq/nebula#69]
I guess there is still documentation I've not found but will Nebula support TAP devices in the future?
Or does it now do so somehow and I'm just missing how to configure it.

**Comment by nbrownus** [comment]
We currently only reason about packets in IP frames. TAP would need us to deal with ethernet frames as well. Can you tell us more about your motiviation for TAP?

**Comment by bmullan** [comment]
@nbrownus 

Hi Nathan.   I retired from 20 yrs at Cisco Systems in 2014 and spend alot of time helping schools w/technical projects.

I do alot of work with Ubuntu and[ LXD Containers ](https://linuxcontainers.org/lxd/introduction/).  LXD containers are thought of as "system" containers because they run a complete linux distro (fedora, centos, debian, ubuntu, alpine etc) vs Docker which is often termed an "application" container.

However, both LXD and Docker containers connect to their Host/Server using a Bridge by default.

- An LXD Host/Server creates a LXDBR0 bridge which by default all LXD containers on that Host connect to.
- All Docker installations represent the docker0 network with bridge; Docker connects to bridge by default.

As a Bridge by definition is L2 having an L2 (TAP) capability makes using a VPN much easier to implement & use.    Yes, in both LXD or Docker you could implement VXLAN and GRETAP over Nebula (or WireGuard) L3 VPN then bridge that to the LXDBR0 or Docker Bridge at L2.

But that would increase complexity and add some overhead.

So at least for my use-case the availability of a TAP device would make Nebula much easier/simpler to utilize.

As FYI a diagram of my use-case is below.   
I "think" you can click on it to enlarge it to get an idea of what I want to do.

![CIAB Overview Diagram (generic)](https://user-images.githubusercontent.com/1682855/70262701-d2420f80-1762-11ea-9a86-3d77eaec1ead.png)

**Comment by bmullan** [comment]
Nathan

Never mind ... I've figured out a work-around so I can use the TAP interface

Sorry for the noise.
