### ISSUE TITLE
windows: expose some method to reload config at runtime

### ISSUE THREAD

**Issue by kazzmir** [slackhq/nebula#694]
On unix systems nebula can be coerced to re-read its configuration file by sending SIGHUP to it. My understanding is Windows lacks the ability to send signals, and therefore nebula cannot take advantage of the SIGHUP method.

It would be convenient if there was some way to cause nebula to re-read its config without having to entirely kill the nebula process. Perhaps by writing to a file that nebula will frequently look for, or a named pipe: https://golangexample.com/a-windows-named-pipe-implementation-written-in-golang/

**Comment by JohnMaguire** [comment]
@kazzmir While it's not as simple as SIGHUP on Linux, I did want to let you know that the built-in SSH server does have a "reload" command. You can find the configuration for the SSH server here: https://www.defined.net/nebula/config/#sshd

**Comment by kazzmir** [comment]
I see, that is very cool! I will try it.

**Comment by kazzmir** [comment]
The `reload` command is not supported on windows, because the ssh server simply sends itself a SIGHUP signal.
```
user@nebula > reload
not supported by windows
```
https://github.com/slackhq/nebula/blob/92dfccf01ac3019ff3e432c11654534be14c052f/ssh.go#L878

So this code would need to be able to interact with the main logic of nebula directly rather than a signal. Maybe there could be a global channel that listens for reloads, where sending SIGHUP would put a value into the channel, and ssh reload does the same.

Quick sketch:
```
reloadChannel := make(chan bool, 2)
signal.Notify(reloadChannel, syscall.HUP)
go func(){
  for {
    select {
      case <-reloadChannel:
          doReload()
    }
  }
}()
...
func sshReload(){
   reloadChannel <- true
}
```
