### ISSUE TITLE
Is there a DNS-like service?

### ISSUE THREAD

**Issue by rileytg** [slackhq/nebula#7]
I've really enjoyed how the SDNs (at least the ones i've used) in kubernetes provide DNS services. 

My understand based on reading the example where the test is pinging an IP (https://github.com/slackhq/nebula/tree/master/examples/quickstart-vagrant#testing-within-the-vagrant-env) that DNS is not provided. 

Or am I mistaken and I can refer to a host by name (e.g. in the quick start, can i run `ping lighthouse1` from the `laptop` box?

**Comment by rawdigits** [comment]
There is a built in DNS function that should work pretty well. It runs on the lighthouse and is enabled via the `serve_dns: true` setting within the configuration file. When this is enabled, you can query the lighthouse on :53 for nebula names, and it will return nebula IPs.

You can also send TXT queries referencing nebula IPs to the lighthouse and it will return the nebula certificate that lighthouse sees for a particular IP.
