### ISSUE TITLE
create wintun interface failed

### ISSUE THREAD

**Issue by yanggis** [slackhq/nebula#704]
Hi, I used nebula 1.5.2 on windows 10 to setup a lan network. 
when I run nebula with a config file, but it ended with an error.
Here is the error info:
 C:\nebula> ./nebula -config c:/nebula/config.yml
time="2022-07-01T10:55:15+08:00" level=info msg="Firewall rule added" firewallRule="map[caName: caSha: direction:outgoing endPort:0 groups:[] host:any ip: proto:0 startPort:0]"
time="2022-07-01T10:55:15+08:00" level=info msg="Firewall rule added" firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host:any ip: proto:0 startPort:0]"
time="2022-07-01T10:55:15+08:00" level=info msg="Firewall started" firewallHash=21716b47a7a140e448077fe66c31b4b42f232e996818d7dd1c6c4991e066dbdb
2022/07/01 10:55:15 Using existing driver 0.14
2022/07/01 10:55:15 Creating adapter
2022/07/01 10:55:15 Failed to set adapter name ""
time="2022-07-01T10:55:15+08:00" level=error msg="Failed to get a tun/tap device" error="create Wintun interface failed, create TUN device failed: Error creating interface: The parameter is incorrect."

Could you guys give a hand, how to fix this issue? Many thanks.

**Comment by yanggis** [comment]
I don't why the adapter name is "", null. This could be the cause to the failure.

**Comment by nbrownus** [comment]
What value do you have for `tun.dev` in your config?

**Comment by yanggis** [comment]
> What value do you have for `tun.dev` in your config?

Hi nbrownus, 
Thanks for the reply.
I dont have any config option for tun.dev; I also checked the config templete,  it doesnt have such option too.
The config works well on linux, but not on windows 10.

**Comment by hmoffatt** [comment]
What was the solution @yanggis ? I have no tun.dev set, but Nebula fails to start with


```
2024/04/29 09:50:42 Using existing driver 0.14
2024/04/29 09:50:42 Creating adapter
2024/04/29 09:50:42 Failed to set adapter name ""
2024/04/29 09:50:42 Using existing driver 0.14
2024/04/29 09:50:42 Creating adapter
2024/04/29 09:50:42 Failed to set adapter name ""
time="2024-04-29T09:50:42+10:00" level=error msg="Failed to get a tun/tap device" error="create Wintun interface failed, create TUN device failed: Error creating interface: The parameter is incorrect."
```

**Comment by coccigelus** [comment]
I have same exactly issue. 2024/05/11 04:39:16 Using existing driver 0.14
2024/05/11 04:39:16 Creating adapter
2024/05/11 04:39:16 Failed to set adapter name ""
2024/05/11 04:39:17 Using existing driver 0.14
2024/05/11 04:39:17 Creating adapter
2024/05/11 04:39:17 Failed to set adapter name ""
time="2024-05-11T04:39:17-05:00" level=error msg="Failed to get a tun/tap device" error="create Wintun interface failed, create TUN device failed: Error creating interface: The parameter is incorrect."

**Comment by hmoffatt** [comment]
I found I just had to set the interface name in the config.

**Comment by coccigelus** [comment]
Thank You for the answer,

 

Still I am facing issues: 

PS C:\Nebula> .\nebula.exe -config config-lighthouse.yaml

time="2024-05-11T11:26:25-05:00" level=debug msg="Client nebula certificate" cert="NebulaCertificate {\n\tDetails {\n\t\tName: server-usa\n\t\tIps: [\n\t\t\t192.168.100.1/24\n\t\t]\n\t\tSubnets: []\n\t\tGroups: []\n\t\tNot before: 2024-05-11 03:45:30 -0500 CDT\n\t\tNot After: 2025-05-11 03:42:06 -0500 CDT\n\t\tIs CA: false\n\t\tIssuer: f9f3a2b40b1bb1c2d9d67422c64d0a9f4787178bcfa52db4339c98c459e1baa3\n\t\tPublic key: 9f03b7a1750208c4930d9843cdfbaf7826c6b28d150eba3e7f42dec62690254a\n\t\tCurve: CURVE25519\n\t}\n\tFingerprint: b372f848a7c15e759a6049b2a4cad5ff9046ca744614cee71df3974dffd155d0\n\tSignature: ccdef27df4aceecb434256c726773c4477a507e4093c49e8d22334050fb5ce313a41aa3f8102f9c1811f63429cab8979e387c35309169fde61a97565e0389f08\n}"

time="2024-05-11T11:26:25-05:00" level=debug msg="Trusted CA fingerprints" fingerprints="[f9f3a2b40b1bb1c2d9d67422c64d0a9f4787178bcfa52db4339c98c459e1baa3]"

time="2024-05-11T11:26:25-05:00" level=info msg="Firewall rule added" firewallRule="map[caName: caSha: direction:outgoing endPort:0 groups:[] host:any ip: localIp: proto:0 startPort:0]"

time="2024-05-11T11:26:25-05:00" level=info msg="Firewall rule added" firewallRule="map[caName: caSha: direction:incoming endPort:0 groups:[] host:any ip: localIp: proto:0 startPort:0]"

time="2024-05-11T11:26:25-05:00" level=info msg="Firewall started" firewallHashes="SHA:498215dec4e5687a2353f51c10838c113bd1af35ef72b8e8c9f536986ada5417,FNV:2782948616"

2024/05/11 11:26:25 Using existing driver 0.14

2024/05/11 11:26:25 Creating adapter

2024/05/11 11:26:25 Failed to set adapter name ""

time="2024-05-11T11:26:25-05:00" level=debug msg="Failed to create wintun device, retrying" error="Error creating interface: The parameter is incorrect."

2024/05/11 11:26:25 Using existing driver 0.14

2024/05/11 11:26:25 Creating adapter

2024/05/11 11:26:25 Failed to set adapter name ""

time="2024-05-11T11:26:25-05:00" level=error msg="Failed to get a tun/tap device" error="create Wintun interface failed, create TUN device failed: Error creating interface: The parameter is incorrect."

 

Config-lighthouse.yar 

lighthouse:

  am_lighthouse: true

  interval: 60

  hosts: []

 

listen:

  host: 0.0.0.0

  port: 4242

  interface: Ethernet

 

punchy:

  punch: true

 

static_host_map:

  # No static mapping needed for lighthouse

 

pki:

  ca: C:\Nebula\ca.crt

  cert: C:\Nebula\server-usa.crt

  key: C:\Nebula\server-usa.key

 

firewall:

  inbound:

    - port: any

      proto: any

      host: any

  outbound:

    - port: any

      proto: any

      host: any

 

logging:

  level: debug

  format: text  # or 'json' if you prefer structured logs

**Comment by hmoffatt** [comment]
Your config doesn't have a [tun] section and dev: setting ?

**Comment by johnmaguire** [comment]
We'll continue discussion of @coccigelus's issue over here: https://github.com/slackhq/nebula/issues/1145
