### ISSUE TITLE
Relay feature not working

### ISSUE THREAD

**Issue by chirayu-patel** [slackhq/nebula#707]
My setup :

1. device with public ip(Made this as a relay server)
2. 2 devices behind NAT which are not reachable directly.

Both the devices are able to reach the relay server.

The 2 devices are not attempting to reach each other via the relay server.

I am not able to see any logs that says its trying to relay via the relay server

**Comment by IanVS** [comment]
Hi, thanks for the report.  Can you please share your relay config for all three devices?

**Comment by gjedeer** [comment]
@chirayu-patel I'm just testing this and it works good for me. Do the devices behind NAT have a section like:

```
relay:
  relays:
    - 192.168.1.1
    - 192.168.1.2
```

where the IP addresses are VPN-internal?

**Comment by gjedeer** [comment]
In my tests - all devices that you're connecting via relay need to be on 1.6+

I've had some devices on 1.5 and some on 1.6 and the relay feature worked only if the 3 devices (endpoint1, endpoint2, relay) are on 1.6. Other devices don't matter.

**Comment by brad-defined** [comment]
@chirayu-patel Please do share the relay config sections of each host. They should look something like this (ip's included just for identification, not part of any Relay config):
```mermaid
graph LR
    A[Device 1<br>ip:192.168.0.2<br>relay.am_relay:false<br>relay.use_relays:true<br>relay.relays: 192.168.0.1] --> B(Relay Host<br>ip:192.168.0.1<br>relay.am_relay:true<br>relay.use_relays:ignored<br>relay.relays:ignored)
    B --> C[Device 2<br>ip:192.168.0.3<br>relay.am_relay:false<br>relay.use_relays:true<br>relay.relays:192.168.0.1]
```

Like @gjedeer mentioned, you'll need to have the hosts identify the Relay that can be used to access them, so be sure to include `relay.relays` in the config, specifying the Nebula VPN IP of the Relay host.

Only those hosts involved in the Relay setup need to be 1.6+. Other versions of Nebula will continue to work fine on the network, but will not involve themselves in any Relay connections.

**Comment by chirayu-patel** [comment]
Yes, I created a complete new network of all 1.6 devices and tested different permutations and combinations multiple times. turning relay ON/OFF and its working as per expectation. The devices are able to auto-detect and route through the relay server if direct connectivity is not there.

Could be some other issue with the old network that we can ignore as of now. 

Thankyou everyone for the help. !!
