### ISSUE TITLE
Does nebula support the deployment of lighthouse server on server with ipv6 addess only?

### ISSUE THREAD

**Issue by yanggis** [slackhq/nebula#713]
Does nebula support the deployment of lighthouse servers on a server with ipv6 addess only?
I've tried to the set a lighthouse server listening on an ipv6 address, but it cannot regonize the address.

**Comment by brad-defined** [comment]
The lighthouse can listen on only IPv6 addresses, but the practice is discouraged.

Peers without IPv6 connectivity will not be able to connect to the lighthouse.

For IPv4-only peers to be able to connect to other IPv4 peers with NAT traversal, all peers must connect to the lighthouse over IPv4 (for NAT IP/port discovery.)

That being said, to configure the lighthouse to listen only on its IPv6 address, configure `listen.host: "<IPv6-address>"` (or `listen.host:""` to bind to all local addresses). Then, configure each peer's `static_host_map` to `"<Lighthouse-Nebula-IP>":"[<Lighthouse-IPv6-address>]:4242"`, assuming you're still using the default Nebula port 4242. (Note the square brackets are needed around the IPv6 address when including the port number - everything between and including the less-than and greater-than should be replaced with your actual IPv6 address.)

**Comment by yanggis** [comment]
@brad-defined Got it. Thanks for the detailed explaination.
