### ISSUE TITLE
One Lighthouse, One Main Client- CGNAT, One Laptop and Relay

### ISSUE THREAD

**Issue by johnjces** [slackhq/nebula#714]
Please forgive me as I have myself so confused over NAT and Relays. I have researched and read too much about Clients not seeing each other and have read the several posts herein on relays that I am assuming are supposed to allow another client/peer/nebula device/laptop etc, to see the client behind NAT that cannot have a UDP port forward assigned in one's router. All nebula executables are on the 1.6.0 release.

My simple setup #1, which by the way works amazingly well, is one lighthouse on a public IP, with 4242 UDP forwarded to my rPi lighthouse with unsafe_route for its LAN IP range. 
Next I have one client also available on a public dynamic IP, (more persistent) with DDNS. I have again port forwarded 4242 to the rPi nebula Client and unsafe_routes for the LAN the nebula is on. Again works well and this would be my experimental setup. With proper routing in my firewall router, any device on any LAN can see any device on any LAN. The rPi Nebulas are about 200 miles apart. 
Lighthouse Nebula IP 192.168.98.1 - LAN IP 192.168.0.15 
Nebula Client IP 192.168.98.3 - LAN IP 192.168.1.30

Adding a second client, i.e. a laptop (with port forwarding enabled on the Main client), the laptop can see any machine on either LAN/location. No issues. Turn port forwarding off, then of course you lose the client. So a relay?

My simple setup #2 , which also works amazingly well is identical to #1, EXCEPT the rPi Nebula Client sits on a LAN serviced by StarLink satellite internet. Some kind of CGNAT, triple NATed.. who knows.  No port forwarding available at all for the client node. But it works great and any device on any LAN can see any device on any LAN. The problem here is a third client, such as a mobile laptop, would never be able to 'see' the StarLink LAN since it is impossible to port forward anything. Again, hoping a relay might do the trick.
Lighthouse Nebula IP 192.168.98.1 - LAN IP 192.168.15.30
Nebula Client IP 192.168.98.2 - LAN IP 192.168.10.30

I have not tried to set up relays (experimental) as the config.yml has me confused as to how to set this up for my circumstance. And reading other posts here on github has just confused me. I was hoping to turn off the port forwarding to the client in setup #1 to test a relay. The only thing I can use as a relay is the lighthouse in either setup.

It seems simple enough but.. I am messed up. The lighthouse would have to relay the packets to a laptop that could be on any network anywhere. 

My question, after all this is, how do I set up the config.yml to give Relay a try? I know it should be simple as I've made it this far pretty well. Somehow stumped.  AND, is this what relay was designed to overcome? Or am I missing the boat?

Thanks so much!

John

**Comment by johnjces** [comment]
It's a new day...  not so overwhelmed.

For such an environment, is a good start:

Lighthouse:
am_relay: true
use_relays: true

Client(s) 
am_relay: false
use_relays: true

Thanks for any advice.

**Comment by johnjces** [comment]
One more:

Do we remove the hashtag # remark in front of #relays:  

relay:
  # Relays are a list of Nebula IP's that peers can use to relay packets to me.
  # IPs in this list must have am_relay set to true in their configs, otherwise
  # they will reject relay requests.
  #relays:
    - 192.168.98.1
OR
relay:
  # Relays are a list of Nebula IP's that peers can use to relay packets to me.
  # IPs in this list must have am_relay set to true in their configs, otherwise
  # they will reject relay requests.
  relays:
    - 192.168.98.1

**Comment by brad-defined** [comment]
hi! Nebula has NAT traversal techniques that work in many situations, so you don't need to turn on port forwarding on all hosts to make the peers accessible. The NAT traversal techniques don't work in all cases, though, and that's where Relays come in.

All Nebula peers will first attempt to connect to the lighthouse. So, the lighthouse must be available on the internet and have a network setup that permits unsolicited inbound traffic (port forwarding, firewall rules, etc.) Then, when a Nebula peer wants to connect to another peer, it'll query the lighthouse to find out where on the internet that peer is. The lighthouse will also notify the peer that someone is trying to connect to it. Both peers then attempt outbound connections to each other (assuming configured to do so - take a look at your `punchy` config settings!)

The outbound handshake/punchy packets on each host create NAT and Firewall state, permitting the inbound traffic to proceed.

In some cases, though, the NAT traversal doesn't work. In those cases, you can Relay your nebula traffic through a common host that both peers can access. The lighthouse is an ideal choice as a Relay for most home users.

You'll need to configure the lighthouse to act as a relay, so in your lighthouse nebula config:
```
# hash tags are used for comments. Config lines in effect don't start with a hash tag.
relay:
  am_relay: true
```

And, the hosts are configured to identify which relay can be used to access them - so in your peer Nebula config:
```
relay:
  relays:
    # Your lighthouse Nebula IP
    - 192.168.98.1
```

**Comment by johnjces** [comment]
@ brad-defined

Thank -you so much for the detailed info.

I have checked 'punchy' in my config. It was:
punchy: true
punch_back: true

It is now:
punchy:
  punch: true
  respond: true
  delay: 1s

Both 'styles' were on the client and lighthouse and both styles of punchy worked with port forwarding enabled. If I close the port forwarding rule on the client, my 3rd client, android, just will not see the main client no matter which flavor of punchy

I must now admit, which I didn't think was pertinent, I am using the Android Nebula CLient on my Samsung tablet. I will try all of this by hooking up my tablet to a mobile hotspot through the Verizon network. With port forwarding enabled on my main client the android tablet client can see the main client and its associated network without issue, If I close the port, no joy. Just interesting.

The Android client has absolutely no way to edit the config but I am not certain that's an issue. Its punch setting are:
punchy:
  punch: true
  respond: false
  delay: 1s

After a firewall change, do I need to restart both, doesn't matter or just one of the nebulas? Of course after changing the config a restart of Nebula is needed.

Again, with port forwarding disabled on my main client, I can see my networks from either end perfectly. Just not from the Android client. So, we will see what relay does.

Thanks for the help and any further information and learning opportunities.

John

**Comment by guanzi008** [comment]
![image](https://user-images.githubusercontent.com/20619190/181866172-d66c3f6a-e051-4828-9c0a-f38820d49032.png)

**Comment by johnjces** [comment]
My apologies as I should have responded prior... as the post by guanzi008 above reminded me. AND it's nice to see a working log example.

I have it working GREAT! Just had a typo that I kept reading/seeing as correct. Once I spelled it right miracles happened!

Thanks!

**Comment by guanzi008** [comment]
@johnjces ，你好。
我的机器，
中转没有成功
一个Server
2个client
您能给个您的配置文件看看吗，

谢谢您。
