### ISSUE TITLE
When using a domain name as a lighthouse, if the domain's IP changed, nebula cannot uppdate its corresponding IP accordingly

### ISSUE THREAD

**Issue by yanggis** [slackhq/nebula#717]
Hi,
Im using a domain name as a lighthouse. However, I noted that, if the domain's IP is changed, nebula cannot uppdate the its corresponding IP accordingly. It still tried to connect to the old IP, but ended with handshake failed.

For the condition, nebula should frequently check the domain name's corresponding IP and update it timely, right? Why it doest?

**Comment by gvlx** [comment]
Should the section `static_host_map` be renamed to `lighthouse_host_map` ?

Suggestion:
- create key `dynamic_host_map_revalidation` : (positive integers only)
  - 0 means "no revalidation" -
  - \>0 is the time in seconds for each revalidation
- when `lighthouse_host_map` values are not canonical IP, values should be verified according to `dynamic_host_map_revalidation`

**Comment by JohnMaguire** [comment]
@gvlx While `static_host_map` is certainly typically used only to identify Lighthouses' positions on the underlay network, it _can_ also be used similarly to a `hosts` file in that if you have a very small network comprised only of hosts with static IP addresses it may be possible to run without a Lighthouse at all (as an example.)

**Comment by aluo-x** [comment]
Purely out of curiosity (debating headscale vs nebula), is this issue currently resolved? Do domain name lighthouses work?

**Comment by nbrownus** [comment]
Closed by #796, v1.7.1 will re-query dns on a cadence.
