### ISSUE TITLE
Can't connect to Nebula host when a second one is behind the same public IP address

### ISSUE THREAD

**Issue by matmat94** [slackhq/nebula#731]
I tried a basic configuration where I have two Raspberry Pis at my home using Nebula as hosts, connecting to an Azure VM running as a lighthouse.
I have an additional Windows laptop that also connects to the same lighthouse.
Every device uses Nebula 1.6.0 with punch: true and respond: true.

<img width="800" alt="IP" src="https://user-images.githubusercontent.com/6900842/183806618-2e4154a0-22e2-4cb9-bce4-37762f8fae40.png">

If only one Raspberry is online the handshake from Windows PC to the Raspberry works and I'm directly connected to the host.
If both are online and I try to connect to one of the Raspberry Pis, the handshakes always fail and the hosts can't communicate, unless the lighthouse is set up as a relay and configured in the Windows host.

If I try to connect to 192.167.1.1, the error message says `wrong host tried to reply to handshake: 192.167.1.2` then `blocking addresses ["80.2.4.10"] for handshakes`, and vice versa for 192.167.1.2.

It seems obvious what is happening but is it wanted?
Is there a workaround if I want to have many hosts in the same subnet behind the same public IP using Nebula, besides using relays?

**Comment by tanja84dk** [comment]
Not that I know it for sure because I'm also only a user and not a dev but my first thought were could it be because  both rasberry pi's are set to listen on the same port?

Not that I know that could be the issue but my thought were when you say it works with one and fails with two with the handshake issue that it could sound like they are using the same port and just forwarding the second to the first connected.

and its down in this here that my thought is about

```
# Port Nebula will be listening on. The default here is 4242. For a lighthouse node, the port should be defined,
# however using port 0 will dynamically assign a port and is recommended for roaming nodes.
listen:
  # To listen on both any ipv4 and ipv6 use "[::]"
  host: "[::]"
  port: 4242
```

**Comment by matmat94** [comment]
Yes I think you're right. I forgot that I used one of the Raspberry Pis as a lighthouse before and I kept the port 4242 open on the public IP (forwarding 80.2.4.10 port 4242 to Raspberry Pi B at 192.168.1.115).
What's weird is I tried both and in either case the other Raspberry also responded to the handshake, even the one not being forwarded by the router.

I will retry the same tests without forwarding ports and update the issue after that.

**Comment by tanja84dk** [comment]
Just as a side note
Tbh just noticed that I actually copied from my local nebula lighthouse.
At least for me I have had good experience with having the port set to 0 on clients so they chose a random port to listen on.
But I do also have to say I'm not that often connecting home over nebula but specially where there is nat on both end ( as there is in your drawing )

**Comment by matmat94** [comment]
I tried again from scratch while disabling any port forwarding (except the one to the Azure VM) and now it works great.
I did not change any ports in the configuration file, left the two Raspberrys at 4242 but it did not cause any issues.
