### ISSUE TITLE
🐛 BUG: Nebula crash if CA cert out of date 

### ISSUE THREAD

**Issue by gendalf** [slackhq/nebula#732]
### What version of `nebula` are you using?

1.6.0

### What operating system are you using?

Linux

### Describe the Bug

Some devices (like IoT boards) without onboard RTC, boot with zero date. They sync time after established internet connection

In this case Nebula daemon detect expired CA cert and make loop crash (in daemon mode)... and when system date is synced and CA cert can be validated - Nebula totaly excess the restart retries 

_suggestions:
if system date less than CA start, soft retry initialisation without immediately crush_

### Logs from affected hosts

```
... warning msg="expired certificate present in CA pool" cert="NebulaCertificat ...
```
```
... Failed to load ca from config" error="no valid CA certificates present ..
```

**Comment by caguiclajmg** [comment]
> In this case Nebula daemon detect expired CA cert and make loop crash (in daemon mode)... and when system date is synced and CA cert can be validated - Nebula totaly excess the restart retries
> 
> _suggestions: if system date less than CA start, soft retry initialisation without immediately crush_

This is your init system/service manager's responsibility, if it's exceeding some sort of restart limit then maybe you should configure some delays (e.g. `StartLimitIntervalSec` on systemd)

Or better yet, configure the nebula service's dependency chain properly (start nebula only once your NTP/time sync script has run).

Allowing nebula to start with an expired CA does not make sense. If a CA certificate is expired then what good will waiting and retrying do; as far as I remember nebula isn't capable of time travel *(yet)*.

**Comment by fabspro** [comment]
_Nebula totaly excess the restart retries_

Try putting a delay in before each retry, and removing/increasing the limit. But to do this properly, you definitely want to start nebula after ntp has synchronised the system time, as @caguiclajmg has stated above.

**Comment by JohnMaguire** [comment]
Thanks for the assist @caguiclajmg - indeed, this should be solved by your system startup service. Closing this out as solved / inactivity.
