### ISSUE TITLE
Documentation Request: Usage example with CSRs

### ISSUE THREAD

**Issue by jeffb4** [slackhq/nebula#76]
The current README documentation involves generating keys and certificates on the CA host, then shipping the key+cert+config to the new client node. Generally speaking a better pattern would be to generate a key and certificate signing request on the client node, then ship the CSR to the CA host and sign a cert, then ship cert/config back to the client node.

If Nebula is capable of handling that pattern, could the README example be updated for it?

**Comment by rawdigits** [comment]
It is capable and better docs are coming. quick version:

`nebula-cert keygen -out-pub pub.key -out-key private.key` will generate a private and public key.
you then ship the public key to the ca host and run
`nebula-cert sign -name blah -ip 192.168.100.0/24 -in-pub pub.key`

**Comment by apmarshall** [comment]
Picking up on this: is there an API to handle signing requests or do they have to be signed manually? 

Alternatively (and maybe this is a question for another thread): can Nebula be used with another CA or does it require certs be signed by its own CA?

**Comment by jasikpark** [comment]
Fixed by https://github.com/DefinedNet/nebula-docs/pull/81 thanks to @JohnMaguire!
