### ISSUE TITLE
Connectivity when all UDP traffic is blocked.

### ISSUE THREAD

**Issue by spacehitchhiker42** [slackhq/nebula#760]
I took my laptop to a place where it appears that their firewall blocks all UDP outbound UDP traffic, except for port 80 and 443.  TCP ports, however, appear to be unaffected.

I tried setting up my lighthouse, and the node on my router as a relay, to listen to port 443. I seemed to be able to consistently ping the lighthouse and the router node, but when I tried to ping a node on my home network,  only 2 pings went through, and I was unable to get any further traffic.

Would it be possible to fall back to TCP if UDP is blocked?

**Comment by JohnMaguire** [comment]
Hi @spacehitchhiker42 - Nebula is based on the UDP protocol and there are currently no plans to implement support for Nebula over TCP. Sorry!
