### ISSUE TITLE
Very slow when sharing a file with smb

### ISSUE THREAD

**Issue by hkhk366** [slackhq/nebula#773]
### What version of `nebula` are you using?

1.6.1

### What operating system are you using?

windows

### Describe the Bug

Hello, I notice that it is very slow to share a file with smb.
The config yamls are in the attachment. It has two yaml (512M.yaml and 8700k1080ti32g.yaml)

[nebula-windows-amd64.zip](https://github.com/slackhq/nebula/files/9996403/nebula-windows-amd64.zip)

Server:
Ubuntu 18.04 with 512M.yaml

Multi-Clients:
Windows 10 with 8700k1080ti32g.yaml

After I share the disk with smb amount multi-windows 10 clients, it is very slow to send a file (The speed is 300KB to 500KB per second). Another thing is, even two windows client in the same local network, ping each other take 10ms. I think this is abnormal. I have already turned off the relay. Is this a bug? I don't know why, would you like to check it? Thank you.

The following are ping result of two client in the same local network but has 10 ms delay. Very weird.
hkhk@main:/mnt/c/Users/HKHK$ ping 10.0.0.3
PING 10.0.0.3 (10.0.0.3) 56(84) bytes of data.
64 bytes from 10.0.0.3: icmp_seq=1 ttl=63 time=10.5 ms
64 bytes from 10.0.0.3: icmp_seq=2 ttl=63 time=10.5 ms
64 bytes from 10.0.0.3: icmp_seq=3 ttl=63 time=10.8 ms
64 bytes from 10.0.0.3: icmp_seq=4 ttl=63 time=11.0 ms
64 bytes from 10.0.0.3: icmp_seq=5 ttl=63 time=10.8 ms
64 bytes from 10.0.0.3: icmp_seq=6 ttl=63 time=10.6 ms

**Comment by oligaameiz** [comment]
The reason is nebula slow on windows, not smb.
