### ISSUE TITLE
🐛 BUG: DNS Case Sensitivity

### ISSUE THREAD

**Issue by robdplatt** [slackhq/nebula#776]
### What version of `nebula` are you using?

1.6.1

### What operating system are you using?

Lighthouse:Linux, Nodes: Windows

### Describe the Bug

Node certificates were generated in the format NODENAME.nebula (unintentionally)

Upon doing an nslookup from a windows client:

> nslookup NODENAME.nebula lighthouseip

returns the IP

> nslookup nodename.nebula lighthouseip

returns *** No internal type for both IPv4 and IPv6 Addresses (A+AAAA) records available for nodename.nebula

We will likely correct the certificate name generation to just use lowercase as that is typically the case for our domains. I just found this behavior strange. Was wondering what others thought about it. If it is indeed a bug, can it be fixed?

**Comment by JohnMaguire** [comment]
Per RFC 4343, I believe DNS resolutions should be case insensitive (validating this bug report): https://www.rfc-editor.org/rfc/rfc4343
