### ISSUE TITLE
Default cipher inconsistent with value implied in example config

### ISSUE THREAD

**Issue by NiceGuyIT** [slackhq/nebula#777]
### What version of `nebula` are you using?

v1.6.1

### What operating system are you using?

Linux

### Describe the Bug

The [example configuration][1] has `cipher: chachapoly` commented out. This normally implies the default value is what's commented out (`chachapoly`). Also notice the config doesn't state which value is the default. The [code][2] uses `aes` as the default. It makes sense the docs should be updated to reflect the default used by the code.

```conf
# Cipher allows you to choose between the available ciphers for your network. Options are chachapoly or aes
# IMPORTANT: this value must be identical on ALL NODES/LIGHTHOUSES. We do not/will not support use of different ciphers simultaneously!
#cipher: chachapoly
```

[1]: https://github.com/slackhq/nebula/blob/master/examples/config.yml#L134
[2]: https://github.com/slackhq/nebula/blob/c2259f14a7d230464613c46e36cbe82116fa2de8/main.go#L267

### Logs from affected hosts

N/A

### Config files from affected hosts

N/A

**Comment by wadey** [comment]
I agree we should fix this :+1:
