### ISSUE TITLE
Feature request: make clean

### ISSUE THREAD

**Issue by virtadpt** [slackhq/nebula#781]
Is there any chance you could add a `make clean` directive to the Makefile?  It's a pretty standard thing to implement in a Makefile even though `rm -rf build/*` is a straightforward thing to do.

**Comment by JohnMaguire** [comment]
Hi @virtadpt - would you mind sharing your use case?

**Comment by virtadpt** [comment]
@JohnMaguire I periodically do a `git pull` on my clone of the Nebula repo, rebuild for all supported platforms, and deploy the resulting nebula binaries (appropriate to the hardware platform) to hosts on my network for use.

**Comment by JohnMaguire** [comment]
@virtadpt Thanks for the context! We define all the build targets as a dependency of `.FORCE` which is a `.PHONY` target. Basically, we will _always_ try to rebuild the binaries if you run `make all` or `make bin` so it shouldn't be necessary to run `make clean`.

Does that work for you, or is there a bit of context I'm missing?

**Comment by virtadpt** [comment]
The context is just "standard pattern for Makefiles."  However, a global rebuild by default is fine, and the explanation makes sense for why.

**Comment by JohnMaguire** [comment]
@virtadpt Yeah, I'm familiar with the `make clean` target in Makefiles. I think where I'm a little stuck here is that there are many build targets: `bin`, which builds for the current system at the project root, `all` which builds into the build/ directory, and a few special targets like `bin-window` which build into the build/ directory, but are then copied to the project root. Also, there are a couple `.pb.go` files which are generated via protobuf, but subsequently checked in.

My concern with a `clean` target is that I'm not sure which of these files should be deleted. Removing the build/ directory seems to make sense, but I'm not sure if we should remove the binary files that are built / copied to the project root. Are there any common patterns for this type of scenario?

**Comment by kittydoor** [comment]
I would argue as a start, it should be equivalent to a `git clean -xdf` after a `make all` (as a reference), by listing build dirs, generated files by path/*.<ext>, and explicit list of arbitrary files. Only if there is a clear reason to preserve a file that was generated by make, it should be removed from the clean target.

**Comment by johnmaguire** [comment]
Ultimately we don't have a use case for this. Our build and release process doesn't have a need for `make clean`. Without a use case in mind, I'm not sure what a proper Makefile job would look like. Closing this out until there's a need.
