### ISSUE TITLE
Feature Request: Matrix bridge

### ISSUE THREAD

**Issue by IngwiePhoenix** [slackhq/nebula#786]
### What version of `nebula` are you using?

1.6.1

### What operating system are you using?

Linux

### Describe the Bug

I apologize for utilizing the Bug template for this in advance but I could not find the option to just file an empty issue ticket, so this would have to do. Plus, I saw other "Feature Request" tickets here as well.

Simply put, I would love to see a Matrix bridge for the support channel on Slack.

Benefits:
- More than one way to reach support.
- Not needing to bind users to an app they might only end up using specifically for this one single purpose.
- Giving the users another, potentially easier, opportunity to partake in discussions.

Since this setup requires administrative previleges (as described [in the official docs](https://github.com/matrix-org/matrix-appservice-slack)) this is sadly not something I could just set up myself and offer to the community for public use, sorry.

Thank you for your time, and again apologies for the mis-use of the bug template! :)

**Comment by JohnMaguire** [comment]
Hi @IngwiePhoenix -

While we understand that not everyone prefers Slack for OSS projects, we unfortunately don't have the resources to research and maintain a Matrix bridge (or Matrix homeserver) and therefore have no plans to support one at this time. In addition to Slack, we are happy to help out users via Github Discussions or Issues.

All the best.
