### ISSUE TITLE
🐛 BUG: nebula frequently crashed on ubuntu 20.04

### ISSUE THREAD

**Issue by yanggis** [slackhq/nebula#801]
### What version of `nebula` are you using?

1.6.1

### What operating system are you using?

Ubuntu 20.04

### Describe the Bug

nebula frequently crashed with below log info:
```
Jan  2 21:35:25 home-server nebula[3996]: panic: runtime error: index out of range [3] with length 3
Jan  2 21:35:25 home-server nebula[3996]: goroutine 55 [running, locked to thread]:
Jan  2 21:35:25 home-server nebula[3996]: github.com/slackhq/nebula.(*TimerWheel).Add(0xc00020c600, {0xc0a8c80a, xc0a8c896, 0xe32a, 0x2093, 0x6, 0x0}, 0x45d964b800)
Jan  2 21:35:25 home-server nebula[3996]: #011github.com/slackhq/nebula/timeout.go:97 +0x1fe
Jan  2 21:35:25 home-server nebula[3996]: github.com/slackhq/nebula.(*Firewall).addConn(0xc00021b860, {0xc000016f00, 0x3c, 0x2329}, {0xc0a8c80a, 0xc0a8c896, 0xe32a, 0x2093, 0x6, 0x0}, ...)
Jan  2 21:35:25 home-server nebula[3996]: #011github.com/slackhq/nebula/firewall.go:513 +0x155
Jan  2 21:35:25 home-server nebula[3996]: github.com/slackhq/nebula.(*Firewall).Drop(0xc00021b860, {0xc000016f00, 0x3c, 0x2329}, {0xc0a8c80a, 0xc0a8c896, 0xe32a, 0x2093, 0x6, 0x0}, ...)
Jan  2 21:35:25 home-server nebula[3996]: #011github.com/slackhq/nebula/firewall.go:386 +0x32e
Jan  2 21:35:25 home-server nebula[3996]: github.com/slackhq/nebula.(*Interface).consumeInsidePacket(0xc0003167e0, {0xc000016f00, 0x3c, 0x2329}, 0xc0000357e0, {0xc0000357f0, 0xc, 0xc}, {0xc000019400, 0x2329, ...}, ...)
Jan  2 21:35:25 home-server nebula[3996]: #011github.com/slackhq/nebula/inside.go:71 +0x2e5
Jan  2 21:35:25 home-server nebula[3996]: github.com/slackhq/nebula.(*Interface).listenIn(0xc0003167e0, {0x7f44fb9741e8, 0xc000308000}, 0x0?)
Jan  2 21:35:25 home-server nebula[3996]: #011github.com/slackhq/nebula/interface.go:265 +0x14d
Jan  2 21:35:25 home-server nebula[3996]: created by github.com/slackhq/nebula.(*Interface).run
Jan  2 21:35:25 home-server nebula[3996]: #011github.com/slackhq/nebula/interface.go:223 +0x9a
Jan  2 21:35:25 home-server systemd-networkd[713]: tun0: Link DOWN
Jan  2 21:35:25 home-server systemd-networkd[713]: tun0: Lost carrier
Jan  2 21:35:25 home-server systemd[1]: nebula.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan  2 21:35:25 home-server systemd[1]: nebula.service: Failed with result 'exit-code'.
```

**Comment by wadey** [comment]
What settings do you have in your config for the the firewall conntrack timeouts? It seems like you found a setting that is causing a calculation error.

let us know the settings and switching back to the defaults should work as a workaround.

**Comment by yanggis** [comment]
Hi wadey. Thanks for the response. Here is the cofig file. In fact, the same config file worked well on Ubuntu 18.04.
Recently, I upgraded the OS to Ubuntu 20.04, the issue happened after the upgradation.
-------------------------------------------config.yml-----------------------------
pki:
  # The CAs that are accepted by this node. Must contain one or more certificates created by 'nebula-cert ca'
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/client.crt
  key: /etc/nebula/client.key

static_host_map:
  "192.168.200.3": ["xx.42.xx.236:4242"]
  "192.168.200.2": ["xx.164.xx.211:4242"]
  "192.168.200.237": ["xx.52.xx.33:42420"]

lighthouse:
  am_lighthouse: false
  interval: 90
  hosts:
    - "192.168.200.3"
    - "192.168.200.2"
    - "192.168.200.237"

listen:
  # To listen on both any ipv4 and ipv6 use "[::]"
  host: "[::]"
  port: 0

punchy:
  # Continues to punch inbound/outbound at a regular interval to avoid expiration of firewall nat mappings
  punch: true

relay:
  relays:
    - 192.168.200.2
    - 192.168.200.3
  am_relay: false
  use_relays: true

# Cipher allows you to choose between the available ciphers for your network. Options are chachapoly or aes
cipher: chachapoly

# Configure logging level
logging:
  # panic, fatal, error, warning, info, or debug. Default is info
  level: info
  # json or text formats currently available. Default is text
  format: text

# Nebula security group configuration
firewall:
  conntrack:
    tcp_timeout: 5m
    udp_timeout: 2m
    default_timeout: 5m

  outbound:
    # Allow all outbound traffic from this node
    - port: any
      proto: any
      host: any

  inbound:
    # Allow icmp between any nebula hosts
    - port: any
      proto: any
      host: any
-------------------------------------end----------------------------

Can you please check what is wrong with the config file?

**Comment by nbrownus** [comment]
Thanks for the report! We will have this fixed in the next release.

You can get the errors to stop in the mean time by raising your `tcp_timeout` and `default_timeout` values to `6m` or remove the `firewall.conntrack` configuration and use the defaults.
```
firewall:
  conntrack:
    tcp_timeout: 6m
    udp_timeout: 2m
    default_timeout: 6m
```
