### ISSUE TITLE
Request to support lighthouse to use the domain name as the entry

### ISSUE THREAD

**Issue by aa51513** [slackhq/nebula#816]
What is the latest status of the issue #273 ?

I really want to know that domain names have not been supported as the entry point of lighthouse, and what concerns do developers have for ignoring such issues?

If you are worried that the dns resolution result contains multiple IP addresses, you can directly select the first one, which is better than doing nothing, isn't it?

**Comment by nbrownus** [comment]
Issue #273, PR #796, and discussion #809 has the information you are looking for.
