### ISSUE TITLE
Comment about sshd is truncated in the sample config.yaml file

### ISSUE THREAD

**Issue by SamSirry** [slackhq/nebula#822]
https://github.com/slackhq/nebula/blob/2ea360e5e25d77b969b5b4f5e6a5c1a2affec843/examples/config.yml#L145

The truncated comment makes it unclear what is the purpose of the following setting.

Could some one elaborate, please?

**Comment by jasikpark** [comment]
see https://nebula.defined.net/docs/config/sshd/
