### ISSUE TITLE
Handshake time out error windows client

### ISSUE THREAD

**Issue by velguru1988** [slackhq/nebula#834]
We are getting handshake timeout error when connecting nebula light house node from windows, we could not ping the light house ip

**Comment by SamSirry** [comment]
Perhaps you should discuss this on reddit (e.g.: https://www.reddit.com/r/NebulaVPN/)

**Comment by JohnMaguire** [comment]
Hi @velguru1988 - I'm closing this issue out as it's lacking necessary info to debug the problem. If you'd like it reopened please provide full Nebula logs and config files from both sides and tag me directly. Thanks!
