### ISSUE TITLE
🐛 BUG: Lighthouse DNS should return NXDOMAIN for names it doesn't know about

### ISSUE THREAD

**Issue by nodakai** [slackhq/nebula#841]
### What version of `nebula` are you using?

dnclient 0.1.9

### What operating system are you using?

Linux

### Describe the Bug

`dig @100.88.0.1 gmail.com`  should result in NXDOMAIN but with DNClient 0.1.9, it returns NOERROR with an empty list. The problem is the OS stub resolver `systemd-resolved` interprets that as a valid name which happened not to have A record.

When I have multiple DNS servers for `systemd-resolved` to query, sometimes the lighthouse replies the quickest among them, but without NXDOMAIN. Then `systemd-resolved` believes `gmail.com` doesn't have any A records, at which point `getaddrinfo()` returns an error without waiting for my home router's DNS or 8.8.8.8/1.1.1.1. If the lighthouse returned NXDOMAIN, then `systemd-resovled` would have waited for my home router to resolve `gmail.com`.

I'm using Network Manager whose CLI is more user friendly than `systemd-networkd` especially for WiFi connectivity. Maybe people using `systemd-networkd` can specifically say "hey whenever you [networkd] *see* an interface named `defined1`, use `100.88.0.1` as a DNS server associated with it" but as far as I know, NetworkManager isn't capable enough to say anything to interfaces it isn't managing. So I'm stuck with having the lighthouse as yet another DNS server for the system, to which queries for `gmail.com` and so on can be sent.

**Comment by nodakai** [comment]
Similar bug ticket filed for Apache Mesos project https://github.com/mesosphere/mesos-dns/issues/57

**Comment by cp-samantha** [comment]
I know it's not ideal, but one of the ways I've solved the issue of split DNS resolution is to avoid using the stub resolver of systemd-resolved at all on machines I want to utilize the nebula network's DNS server. The behavior of the stub resolver seems to be that it prefers a single DNS entry and once that DNS server gets locked in, it doesn't really want to change.

My two current work arounds for this:

1. Disable the stub resolver in systemd-resolved (symlink the non stub resolv.conf into /etc). This will place each individual server in priority order in /etc/resolv.conf. When resolv.conf has more than one resolver, the behavior appears correct to prefer the top NS server and then rotate through other options if nothing is returned by the first server. This will disable all the fancy features that the stub resolver provides though.

2. Split DNS resolution in systemd-resolved. Set a unique TLD or some other domain and use the NS search option for your domains, bind this domain/tld to the nebula interface in systemd resolved and set the resolver for this interface to the nebula lighthouse.

**Comment by cp-samantha** [comment]
Sorry for my late response here. Busy busy.

Confusingly, I don't think you configure the interface specific DNS in systemd-resolved, it's rather configured in systemd-networkd:

https://superuser.com/a/1342172

Again, I haven't gone down testing this route, but something like this:

```
[Match]
Name=tun0 # or neb0 -- whatever your network iface is called

[Network]
DNS=10.128.9.1 # your lighthouse ip
Domains=tld # the tld/domain you want to search on
```

The stack exchange article has other answers, one of them leading to this blog post: https://blog.simos.info/how-to-use-lxd-container-hostnames-on-the-host-in-ubuntu-18-04/

That post seems to indicate that the network config may not work (not sure why, sounds like a bug. Maybe fixed since that article was written for a 5 year old LTS OS), but the blog post has a script which can be started via systemd on  boot to do the "manual" steps

**Comment by cp-richard** [comment]
For those who might have been relying on the 'bug' to be able to setup a DNS order flow that would try the lighthouse DNS first, then fall back to other systems without having to setup a proxy dns system (dnsmasq, etc.), well that ship has sailed and you will need a proxy dns setup to direct some traffic to Lighthouse DNS and some to recursive DNS servers.

If for some reason you don't have an infra setup that allows for a nice patterned 'only and always in nebula dns entries' the typical setups will not help you out.   The solution I wanted to share that worked for us was using coredns and the following config:

```
. {
    bind 127.0.0.1
    # Try Nebula DNS
    forward . 10.123.123.1 {
        policy sequential
        next NXDOMAIN     # if it says NXDOMAIN, try the next block
    }

    # Failover to alternatives
    forward . 1.1.1.1 8.8.8.8 {
        policy sequential
    }

    # (optional) cache answers locally for 30 s
    cache 30
    log
}
```
..on every system that needed it or a central available DNS server (change the bind)

It will try the Lighthouse DNS first (10.123.123.1 in the sample) and on NXDOMAIN response, chain down.
