### ISSUE TITLE
🐛 BUG: lost connectivity after some period of time

### ISSUE THREAD

**Issue by x1ddos** [slackhq/nebula#846]
### What version of `nebula` are you using?

1.6.1-master-44-g3cb4e0e

### What operating system are you using?

linux kernel v6.1.14

### Describe the Bug

after some time, a client loses connection to a lighthouse and tunnels no longer possible. restarting the client immediately restores everything: works normal again for a limited time.

### Logs from affected hosts

once the connection is broken, pinging lighthouses shows that it (the lighthouse) actually sees incoming ICMP and even responds to them:

```
# lighthouse logs
2023-04-14T11:21:38.04879 daemon.notice: lighthouse: level=debug msg="Disabled tun responded to ICMP Echo Request" raw="45 00 00 ..."
2023-04-14T11:21:38.04881 daemon.notice: lighthouse: level=debug msg="Write payload" raw="45 00 00 
2023-04-14T11:27:51.07947 daemon.notice: lighthouse: level=debug msg="Tunnel status" certName=client localIndex=2364262489 remoteIndex=3787007227 tunnelCheck="map[method:passive state:alive]" vpnIp=240.0.0.3
```

but ping from the client says 100% packets loss: 

```
# client
$ ping -c2 240.0.0.1
PING 240.0.0.1 (240.0.0.1) 56(84) bytes of data.

--- 240.0.0.1 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1000ms

# same client, tcpdump during ping 
# tcpdump -i nebula1
listening on nebula1, link-type RAW (Raw IP), snapshot length 262144 bytes
11:21:34.969488 IP 240.0.0.3 > 240.0.0.1: ICMP echo request, id 60729, seq 1, length 64
11:21:35.990648 IP 240.0.0.3 > 240.0.0.1: ICMP echo request, id 60729, seq 2, length 64
```

nebula's sshd on the client shows lighthouse present in the map:

```
# ssh -p 2222 user@127.0.0.1 
user@nebula > list-hostmap
240.0.0.1: [1.2.3.4:4242]
user@nebula > list-lighthouse-addrmap
240.0.0.1: {"240.0.0.1":{"learned":[{"ip":"1.2.3.4","port":4242}],"relay":[]},"240.0.0.3":{"reported":[{"ip":"1.2.3.4","port":4242}],"relay":[]}}
```

### lighthouse config

```yaml
pki:
  ca: /home/nebula/ca1.crt
  cert: /home/nebula/lighthouse1.crt
  key: /home/nebula/lighthouse1.key
  disconnect_invalid: true

static_host_map:
  "240.0.0.1": ["1.2.3.4:4242"]

lighthouse:
  am_lighthouse: true

listen:
  host: "::"
  port: 4242
  send_recv_error: always

cipher: chachapoly

relay:
  am_relay: true

tun:
  disabled: true

firewall:
  outbound_action: reject
  inbound_action: reject

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: icmp
      host: any
```

### client config

```yaml
pki:
  ca: /etc/nebula/ca1.crt
  cert: /etc/nebula/client.crt
  key: /etc/nebula/client.key
  disconnect_invalid: true

static_host_map:
  "240.0.0.1": ["1.2.3.4:4242"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "240.0.0.1"
  local_allow_list:
    "0.0.0.0/0": true
    "::/0": false

listen:
  host: "0.0.0.0"
  port: 0
  send_recv_error: always

punchy:
  punch: true
  respond: true

cipher: chachapoly

preferred_ranges:
  - "192.168.178.0/24"

relay:
  relays:
    - 240.0.0.1
  use_relays: true

tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300

firewall:
  outbound_action: reject
  inbound_action: reject

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: icmp
      host: any
    - port: 22
      proto: tcp
      group: somegroup
```

**Comment by nbrownus** [comment]
Thanks for the report!

A few questions:
- Is the client also running `1.6.1-master-44-g3cb4e0e`?
- Is the client moving between physical networks at any point?
- Have you tried to reproduce using the latest official release, `v1.6.0`?

**Comment by x1ddos** [comment]
right, the client runs the same version and it's stationary, always connected to the same network.

this is very interesting: i've swapped the binaries to the latest release `v1.6.1` on both client+lighthouse and it's been running without issues for about 10 hours. i guess i'll stick to the latest release at this point but would be nice to know what the problem is with `1.6.1-master-44-g3cb4e0e`.

possibly a regression somewhere between 1.6.1 and a recent master? i could maybe try and bisect.

**Comment by nbrownus** [comment]
v1.7 will have some changes related to connection tracking and part of that work is already merged into master. If you don't mind running bleeding edge, #838 is what we are currently testing on.

**Comment by x1ddos** [comment]
> v1.7 will have some changes related to connection tracking and part of that work is already merged into master. If you don't mind running bleeding edge, #838 is what we are currently testing on.

nice. i'll try it today.

**Comment by x1ddos** [comment]
> nice. i'll try it today.

after some time running #838 version on both lighthouse and the client, i start seeing similar issues: the client somehow looses the connection with the lighthouse. ping packets seem to reach the lighthouse from client but the lighthouse logs show:

```
2023-04-18T11:22:38.27713 daemon.notice: lighthouse: level=debug msg="Recv error sent" index=2996565785 udpAddr="1.2.3.4:35937"
```

where `1.2.3.4` is client's ip addr. the client is of course still running:

```
$ ss -ulpn | grep nebula
UNCONN 0      0      [::ffff:0.0.0.0]:35937            *:*    users:(("nebula-v5eb55e5",pid=877,fd=7))
```

also, client's overlay ip addr is no longer in the `list-hostmap` on the lighthouse.

**Comment by nbrownus** [comment]
Mind sending debug logs from the both the lighthouse and the client that includes from the handshake to when the tunnel is declared dead? Email or Slack would be great :)

**Comment by x1ddos** [comment]
turns out this is not a bug. the problem was actually at the lighthouse side, not the client.

it seems like my lighthouse is behind a NAT-like system which would close the channel between lighthouse and the client after some time due to inactivity. the client pings do reach the lighthouse, which it responds to, but the ping replies never reach back to the client.

current workaround for a version at current master or https://github.com/slackhq/nebula/pull/838 is to enable punchy on the **lighthouse**:

```yaml
punchy:
  punch: true
```

this keeps lighthouse-outgoing traffic alive and allows to keep the channel open.

but for the next release, i believe there will be something better than this workaround.

@nbrownus thanks for debugging this!
