### ISSUE TITLE
Would you consider OpenBSD support?

### ISSUE THREAD

**Issue by JohnMaguire** [slackhq/nebula#850]
### Discussed in https://github.com/slackhq/nebula/discussions/806

<div type='discussions-op-text'>

<sup>Originally posted by **ablackcatstail** January 14, 2023</sup>
I am a huge fan of OpenBSD having learned Unix-like operating systems on it. Given that OpenBSD has good support for the Go compiler, would there be any interest in creating binaries for it? I am certainly no programmer by any means but I would willingly assist in testing and I would supply a public VM for such purposes. Given OpenBSD's emphasis on security, firewalling, and routing (also having a kernel implementation of WireGuard), I think it would make a great addition to the Nebula family. Please let me know if there is interest. Thank you in advance.</div>

**Comment by jpds** [comment]
PR at #812

**Comment by JohnMaguire** [comment]
#812 merged.
