### ISSUE TITLE
address family not supported by protocol

### ISSUE THREAD

**Issue by mrkariimi** [slackhq/nebula#853]
### What version of `nebula` are you using?

1.6.1

### What operating system are you using?

linux

### Describe the Bug

i have large network
in some host .it can  not Handshake and i recieve this message :

### Logs from affected hosts

Apr 28 00:01:57 O1 nebula[719880]: time="2023-04-28T00:01:57Z" level=error msg="Failed to send handshake message" error="sendto: address family not supported by protocol" handshake="map[stage:1 style:ix_psk0]" initiatorIndex=2768384177 udpAddr="my public ip :57016" vpnIp=192.168.100.22

**Comment by ablackcatstail** [comment]
The same thing seems to happen to me. I see it when I try to contact my lighthouse and I am on an IPv4/6 dual stack network. I am happy to assist anyone that needs more information. For now I am stumped.

**Comment by nbrownus** [comment]
Without logs or configuration from the affected hosts the best guess I have is that both non lighthouse hosts are behind a NAT that can not be punched through effectively. It may be helpful to set `relay.use_relays: true` and `relay.relays: [$YourLighthouseVpnIp]` on both peers and `relay.am_relay: true` on your lighthouse.

**Comment by JohnMaguire** [comment]
@ablackcatstail @mrkariimi Please provide logs and configuration of the affected hosts at your convenience. Thanks!

**Comment by JohnMaguire** [comment]
Closing this issue as we're lacking necessary information to debug.
