### ISSUE TITLE
✨ FEATURE: Lighthouse CLI to list existing host IPs

### ISSUE THREAD

**Issue by anthonyra** [slackhq/nebula#894]
# Motivation
I'm trying to create a means to dynamically add hosts to Nebula. The intentions are to use the pubkey of a host to create the associated cert. I'd like to give the responsibility of determining the hosts IP and groups to the lighthouse instance. The latter for the time being could be static (only these hosts groups can be dynamically added for example) but the IP is more important.

# Suggestions
A) The `sign` function of `nebula-cert` could default to the next available IP address if the `-ip` flag was omitted when the `-in-pub` flag is used.
B) Provide a new CLI command for `nebula` that will print all existing hosts IP addresses known to the lighthouse

The first option would be the ideal approach for me but I'm not sure how realistic it is.

To implement the above, the DNS feature could be leveraged. Maybe the database/store used for DNS could be populated by default. Just the DNS server would need to be enabled to function. Then nebula-cert could leverage that database/store for this feature/command.

**Comment by nbrownus** [comment]
Nebula has an `ssh` interface that will give you part of this today. `list-lighthouse-addrmap` will give you information about what the lighthouse knows. This is information learned or provided by clients to a node with `lighthouse.am_lighthouse: true` or information learned or provided to clients from a configured lighthouse.

https://github.com/slackhq/nebula/blob/master/examples/config.yml#L161-L175

For the signing part, nebula can't participate in a mesh without a certificate to start with. You will need to find a way to sign certs before you can get a client connected to a lighthouse.

In general this sounds a bit like a "provisional" mesh, where less-than-secret ca keys are used to give access to a certificate authority where a client can then provide more information about itself to get the certificate authority to sign a real certificate. The primary point of which is to keep the signing infrastructure off the internet as much as possible.

**Comment by anthonyra** [comment]
The intention is to create the certs via https://nebula.defined.net/docs/guides/sign-certificates-with-public-keys/ where the host wanting to join will use a public (Auth 2.0 enabled) RPC call with their pubkey to the lighthouse. The lighthouse will than use a similar command;

```
nebula-cert sign -in-pub [pubkey] -name [hostname] -ip [private_ip_for_network] -groups [groups]
```

Where the lighthouse will generate the cert using the provided pubkey. This cert will be returned to the host to then join the network. In doing so I want the lighthouse to assign the next available IP address for the host. I'll take a look into the `ssh` interface and see if that'll work for me. Can that `list-lighthouse-addrmap` be called locally or only via that interface?

Right now I'm intending on using `rabbitmq` to create this RPC call but a built in version would be even better! But I'm sure that's easier said then done...

**Comment by JohnMaguire** [comment]
> Can that list-lighthouse-addrmap be called locally or only via that interface?

Only via the ssh interface

>  B) Provide a new CLI command for nebula that will print all existing hosts IP addresses known to the lighthouse

Keep in mind that the Lighthouse has no persistent storage of nodes it talks to. The Lighthouse also has no inherent ties to CA key material. Typically, CA key material is not stored on Lighthouse hosts (ideally it is stored somewhere encrypted, like Ansible Vault or using an HSM, or AWS KMS, etc.) Therefore, the Lighthouse only knows about hosts with which it has handshaked with since its last boot. It is highly likely that such a system would reuse IP addresses for multiple hosts, causing connectivity issues.

It sounds like you want a signing oracle which authenticates requests via OAuth 2.0 and invokes `nebula-sign` on the caller's behalf using the CA key material. It seems that this service could also track IP addresses it assigns, e.g. in a SQLite or MySQL database.

**Comment by anthonyra** [comment]
> Keep in mind that the Lighthouse has no persistent storage of nodes it talks to.

Huh, I didn't know this. I figured it would have some sort of persistent storage..

> The Lighthouse also has no inherent ties to CA key material.

Appears that I've been doing this wrong. I've had my lighthouse hold the networks ca.crt and ca.key for signing purposes.

> It sounds like you want a signing oracle which authenticates requests via OAuth 2.0 and invokes `nebula-sign` on the caller's behalf using the CA key material. It seems that this service could also track IP addresses it assigns, e.g. in a SQLite or MySQL database.

This pretty well sums up what is needed. I'm currently trying to build it out myself and was hoping that there would be a way to leverage the lighthouse in ensuring already handed out IP's would be captured. The other thought is if Lighthouse would have this feature baked into it, it could also blocklist certs easier if a host needs to be replaced or removed.

**Comment by JohnMaguire** [comment]
> This pretty well sums up what is needed. I'm currently trying to build it out myself and was hoping that there would be a way to leverage the lighthouse in ensuring already handed out IP's would be captured. The other thought is if Lighthouse would have this feature baked into it, it could also blocklist certs easier if a host needs to be replaced or removed.

We don't have plans to include a signing oracle as a feature of Nebula OSS. Our goal is on keeping the Nebula project related to the actual mesh networking protocol, while allowing the community or users to build their own provisioning story around it.

There are other challenges with trying to repurpose a Lighthouse for this task at all: some nodes may not have connectivity to all Lighthouses (of which there can be many), and therefore a Lighthouse may not know about all nodes on the network. Or, a keypair may be generated but unused for a long period of time before finally coming online - during this time the Lighthouse is unaware of the keypair's existence and may re-assign its IP address.

You may want to take a look [Defined Networking](https://defined.net) [full disclosure: I am en employee] for a hosted offering that handles key management and authentication for you. Alternatively, [unreality/nebula-mesh-admin](https://github.com/unreality/nebula-mesh-admin) and [b177y/starship](https://github.com/b177y/starship) are open-source projects in this vein.
