### ISSUE TITLE
Feature request: Option to avoid adding routes to the tunnel interface

### ISSUE THREAD

**Issue by noseshimself** [slackhq/nebula#895]
### What version of `nebula` are you using?

1.7.2

### What operating system are you using?

FreeBSD

### Requested feature

Like any good VPN software Nebula is bringing the ability to update the system's routing table with it. I would like to add nebula to a (FreeBSD, but that's besides it) router as a "bolt-on interface" but leaving routing setup to the router (and the packet filtering to the packet filter). To make this easier (and avoid "something changed my routing table" messages) but still be able to use unsafe routes (as this is the goal of this entire project) it would be helpful if unsafe_routes would not add routing table entries.

(PS: Does not work on OPNSense as of today; even after renaming tun0 to nebula0 OPNsense is treating the new interface as Ethernet, not point-to-point and happily removes the IP address to find out it can't change it but as long as all I do is bringing up the nebula and just use the interface it is working.)

**Comment by JohnMaguire** [comment]
Hi @noseshimself 

> To make this easier (and avoid "something changed my routing table" messages) but still be able to use unsafe routes (as this is the goal of this entire project) it would be helpful if unsafe_routes would not add routing table entries.

Just to make sure I'm fully grokking your request, can you help me understand how it is different from #897? Thanks!

**Comment by noseshimself** [comment]
It's a bit more complicated than I thought...

As soon as Nebula is bringing up the (point-to-point) interface on FreeBSD it is adding a network route for the entire mesh pointing to the interface.

The interface itself is already looking a bit strange to me
```
ap@router:~ % ifconfig nebula0
nebula0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> metric 0 mtu 1300
        options=80000<LINKSTATE>
        inet 172.31.255.3 --> 172.31.255.3 netmask 0xffffff00
```
as I'm not used to see  something with a POINTTOPOINT flag having a netmask that is not /32 (I'm from the ancient past where it had to be exactly like that and you added a network route next) but on plain FreeBSD this is working well enough.

OPNSense does not necessarily like it; I found it to be more stable if I got the interface as PtP with mask /32 without any routing attached and add the routes using OPNSense. The changes that enable me to treat unsafe routes that way would be quite helpful.

**Comment by JohnMaguire** [comment]
@noseshimself The `ifconfig` output looks correct. The netmask is that of your Nebula network, and has no bearing on routing. Please use the `route show` command to list your system routes.

By default, Nebula adds a route for the VPN IP CIDR to the routing table to ensure that packets to other Nebula IPs flow through the Nebula adapter. It also adds routes for unsafe_routes defined under `tun.unsafe_routes` by default.

You previously filed #897 and then closed it after reading recent release notes. In your unsafe_routes config, did you try adding `install: false` to each route? When install is false, Nebula will not add routes to the routing table on your behalf. Does this achieve what you're looking for?

Thanks!

**Comment by noseshimself** [comment]
> @noseshimself The `ifconfig` output looks correct. `ifconfig` shows adapter properties, not routes.

This being *BSD, not Linux there is a close relationship to it. The purist in me screams "the netmask on a PtP link should reflect the fact".

> The netmask is that of your Nebula network which the IP belongs to, and has no bearing on routing. Please use the `route show` command to list your system routes.

```
ap@router:~ % netstat -nrf inet
Routing tables

Internet:
Destination        Gateway            Flags     Netif Expire
default            192.168.11.254     UGS     vlan011
8.8.4.4            192.168.10.254     UGHS    vlan010
8.8.8.8            192.168.11.254     UGHS    vlan011
9.9.9.9            192.168.11.254     UGHS    vlan011
127.0.0.1          link#2             UH          lo0
172.31.246.0/23    link#18            US      nebula0
172.31.248.0/24    link#18            US      nebula0
172.31.254.0/24    link#18            US      nebula0
172.31.255.0/24    link#18            US      nebula0
172.31.255.3       link#18            UH      nebula0
```
[...]

> By default, Nebula adds a route for the VPN IP CIDR to the routing table to ensure that packets to other Nebula IPs flow through the Nebula adapter. It also adds routes for unsafe_routes defined under `tun.unsafe_routes` by default.

It's not exactly how most people expect these things.

172.31.255.0/24 is the direct connection to the mesh it belongs to; the others are unsafe_routes. For those I would rather expect something involving a gateway entry  looking like

172.31.246.0/23    172.31.255.254           UGS      nebula0

instead of an interface route but in the current incarnation of the IP subsystem that does not matter. It is costing me certain filter options in pf (the FreeBSD packet filter used in OPNSense for the purpose of classic packet filtering) (e. g. there is no good solution for policy based routing if I would like another gateway to handle things if a link goes down) but I could live with this. It might lead to information being broadcast on the link on HA systems but in that case I would recommend using a separate router as "mesh endpoint".

> You previously filed #897 and then closed it after reading recent release notes. In your unsafe_routes config, did you try adding `install: false` to each route? When install is false, Nebula will not add routes to the routing table on your behalf. Does this achieve what you're looking for?

Yes; I'm using that option to avoid automatically adding "zero maintenance" routes by nebula and being able to add them myself the way I would like them (including a gateway). This way I can check the availability of the link and have the routes taken down automatically if something happens to the nebula connection the router does not have real control over (I avoided doing the full integration into OPNSense infrastructure; for now the mesh is just a network with an interface into it and unsafe_routes are routes across a know gateway).

So all that is really needed to get things working well is adding BSD-related interface renaming and integrating Nebula into OPNsense (or just running it on a plain FreeBSD system) will be quite easy.

**Comment by JohnMaguire** [comment]
@noseshimself Hi, thanks for the response!

>> The ifconfig output looks correct. ifconfig shows adapter properties, not routes.
> This being *BSD, not Linux there is a close relationship to it. The purist in me screams "the netmask on a PtP link should reflect the fact".

I apologize for being dense, but should reflect what fact? I'm a little confused on what you're asking for here. In the original comment, my understanding was that you wanted this to show `/32`, even though your `routes` output shows a `/24` is configured, just like the netmask in the output.

The netmask in the `ifconfig` output is a property of the address on the network, so this all looks correct to me. Note that your certificate contains a `/24`. Can you provide literature explaining why you think this should be different? In my research I don't see anything suggesting this should be a `/32`.

> instead of an interface route but in the current incarnation of the IP subsystem that does not matter. It is costing me certain filter options in pf (the FreeBSD packet filter used in OPNSense for the purpose of classic packet filtering) (e. g. there is no good solution for policy based routing if I would like another gateway to handle things if a link goes down) but I could live with this. It might lead to information being broadcast on the link on HA systems but in that case I would recommend using a separate router as "mesh endpoint".

Can you provide any resources or links on this? Are you looking to be able to set a metric for the Nebula-added route, or something different?

> So all that is really needed to get things working well is adding BSD-related interface renaming and integrating Nebula into OPNsense (or just running it on a plain FreeBSD system) will be quite easy.

Noted in #908, this is completed and awaiting release.  Is there something I'm missing?

> Yes; I'm using that option to avoid automatically adding "zero maintenance" routes by nebula and being able to add them myself the way I would like them (including a gateway).

Thanks - does this satisfy the request of the ticket? I'm not sure what you're looking for here, please advise.

**Comment by JohnMaguire** [comment]
P.S. I found [this link](https://stackoverflow.com/a/37327065) which talks about the POINTTOPOINT flag and how it's used for two different things: (1) point-to-point protocol, which I think you're used to seeing with a smaller mask, (2) tun devices, which is what Nebula does.

I still believe the netmask is appropriate on the device in ifconfig.

**Comment by noseshimself** [comment]
> > The purist in me screams "the netmask on a PtP link should reflect the fact".
> 
> I apologize for being dense, but should reflect what fact? I'm a little confused on what you're asking for here. In the original comment, my understanding was that you wanted this to show `/32`, even though your `routes` output shows a `/24` is configured, just like the netmask in the output.

Yes. That mask used to be an indicator for "expensive" links (by not leaving room for broadcast addresses in the network) that should be treated accordingly. I just checked everything I remember to rely on it; it's gone.

So the only part of the original request still open are the unsafe_routes. Yes, the nebula process is taking care of them on its own. It makes the entire thing "work on its own" as nebula is sorting out what the next hop should be and enables you to change these parameters on its own in a future version. It just feels strange to take that out of the hands of a designated router (but they certainly are not the core targets Nebula is intended for) (I would even love to see the opposite happening -- reduce the configuration file to your authentication material and the location of a config server (maybe part of the lighthouse) and everything else that is in the current config file will be pushed to the node).

> Noted in #908, this is completed and awaiting release. Is there something I'm missing?

No; as soon as this is released I'll at least try to add the minimal plumbing for the OPNsense infrastructure and try finding someone helping me to turn it into a plugin.

> Thanks - does this satisfy the request of the ticket? I'm not sure what you're looking for here, please advise.

Yes; OPNSense is now accepting network routes to POINTTOPOINT devices (instead of requiring gateways) that was my original motivation so  the interfaces and routing table entries created by Nebula are usable for all filtering purposes (you just have to be creative if you really need to make decision based on the next hop which makes policy based routing a bit different). But I tried it; you can't get rid of the POINTTOPOINT flag.

**Comment by JohnMaguire** [comment]
@noseshimself You can find a [nightly build here](https://github.com/NebulaOSS/nebula-nightly/releases) if you'd like to give it a shot before we cut a new release. You clearly have some expertise and it'd be great to get it some testing if you're able.

**Comment by noseshimself** [comment]
> You can find a [nightly build here](https://github.com/NebulaOSS/nebula-nightly/releases) if you'd like to give it a shot before we cut a new release. You clearly have some expertise and it'd be great to get it some testing if you're able.

Release v1.7.3-nightly20230803 is working without any problems for me with my 1.7.2 setup on the other nodes.

Config change:

```
tun:
  dev: nebula1234
  drop_local_broadcast: true
```

Unexpected: Terminating the nebula process is leaving an interface "nebula0" behind. But starting again is working and resulting in nebula0 existing and nebula1234 coming up as expected so you can deal with it.

kill -9 is leaving nebula1234 behind, too (doh). Restarting is working as expected.

Using nebula0 as interface name is opening nebula0 and using it even though it already existed. Great.

Using "nebula" as  interface name is not what you would expect if you thought it was a "normal" interface template (i. e. "nebula<x>" with x being the lowest free number). 

Whatever I tried (killing the process in every imaginable way) did not leave anything but an inactive nebula0 (and sometimes nebula1234) behind.

As far as I can judge it it seems to be doing what you would expect.


PS: What does 

```
WARN[0000] route MTU is not supported in freebsd         route="{1400 100 172.31.254.0/24 172.31.255.254 true}"
```
try to tell me? I never thought about it because the way I would have handled that was my own application layer ("packet too long -- let's get the scalpel out and cut a bit off").  I'm pretty sure BSD will provide you whatever you need to be done by the OS.
