### ISSUE TITLE
Feature request: remove FreeBSD tunnel interface naming restriction

### ISSUE THREAD

**Issue by noseshimself** [slackhq/nebula#896]
### What version of `nebula` are you using?

1.7.2

### What operating system are you using?

FreeBSD

### Requested change

overlay/tun_freebsd.go:

`var deviceNameRE = regexp.MustCompile(`^tun[0-9]+$`)`

is a bit harsh; I would like to call my interface whatever I like it to be called  according to my local naming scheme without having to write a daemon watching for it to appear. FreeBSD is offering "ifconfig interface-name name new-name" so  while you are doing everything in tun_freebsd.go using sub shells running ifconfig you could just as well add it by doing ifconfig create tun (and wait for the device number to be returned) and subsequently rename it to the desired name. Using fixed "tunx" names is not that good an idea.

Warning: Renaming an interface is cosmetic. If you go that route you should assume that the nebula binary crashed at some point in the past.

1. Try finding the interface (`ifconfig <name>`) first. `ifconfig destroy` it if it does.
2. The original name still exists as long as the renamed interface does. So if you did not use `ifconfig tun create` but `ifconfig tun1 create` the name tun1 will still be occupied, especially after nebula terminated without destroying the interface.
3. Certain BSD software still expects interface names to end in a number (because without a number it refers to the driver it is split off from; deep in the history of BSD there were commands to configure the driver using ifconfig. Maybe a warning about that would be a good idea.

**Comment by JohnMaguire** [comment]
Consolidating under #309.
