### ISSUE TITLE
Fatal Error: TAP driver

### ISSUE THREAD

**Issue by voldemortensen** [slackhq/nebula#9]
```Activate failed: Failed to find the tap device in registry with specified ComponentId 'tap0901', TAP driver may be not installed```

The docs don't mention the need for a TAP driver. Which driver is recommended?

**Comment by rawdigits** [comment]
Doh! Are you on Windows, by chance? If so, installing OpenVPN will add a tuntap driver we can use. I'll keep this issue open and update the docs. We also need a better solution for installation on windows.

**Comment by voldemortensen** [comment]
Yes, this particular machine is a Windows machine (I meant to mention that). Thanks!

**Comment by voldemortensen** [comment]
Circling back to confirm that installing OpenVPN did indeed solve the issue.

**Comment by lixin9311** [comment]
you can find a standalone TUN/TAP driver for Windows here. (bottom of the page)

https://build.openvpn.net/downloads/releases/

good for guys don't want to install extra software

**Comment by rawdigits** [comment]
Thanks to the pointer to a standalone driver! We'll use this in the documentation.

**Comment by erayd** [comment]
The latest version of the OpenVPN (2.5.0) driver did not work out of the box for me on Windows 10 x64.

Changing the registry value `HKLM\SYSTEM\CurrentControlSet\Control\Class\{4d36e972-e325-11ce-bfc1-08002be10318}\0016\ComponentId` from `root\tap0901` to `tap0901` resolved the issue.

**Comment by MKRhere** [comment]
Thanks @erayd; this helped.
I previously had tinc installed. So terminating tincd, modifying the registry value and running nebula worked fine.

**Comment by stealthmode404** [comment]
> The latest version of the OpenVPN (2.5.0) driver did not work out of the box for me on Windows 10 x64.
> 
> Changing the registry value `HKLM\SYSTEM\CurrentControlSet\Control\Class\{4d36e972-e325-11ce-bfc1-08002be10318}\0016\ComponentId` from `root\tap0901` to `tap0901` resolved the issue.

It appears that the registry is not always at 0016. In mine, it was 0010. Basically, it's easier to identify it with the description. It was mentioned as "TAP-Windows Adapter V9" in the ProductName and this helped in identifying.

I changed the `ComponentId` from `tap_ovpnconnect` to `tap0901`
![Screenshot 2021-06-20 at 9 54 03 PM](https://user-images.githubusercontent.com/1282847/122681577-88206200-d212-11eb-80d6-8239c0665b98.png)

**Comment by mxalbert1996** [comment]
As the latest versions of tap driver no longer provide exe, here's how to install.
First, download the `zip` package (e.g. https://build.openvpn.net/downloads/releases/tap-windows-9.24.6.zip) and extract `amd64` dir.
Then open a console as admin, cd into the dir and run `tapinstall install OemVista.inf tap0901` and you are good to go! As you are specifying the `tap0901` manually there's no need to rename it in registry.

**Comment by nbrownus** [comment]
We've moved to the wintun driver, this should no longer be an issue.

**Comment by LookoutHill** [comment]
On a new install of v1.6.1, I'm having this same issue:

Activate failed: Failed to find the tap device in registry with specified ComponentId 'tap0901', TAP driver may be not installed

I've placed the wintun.dll from the amd64 folder packaged in nebula-windows-amd64.zip with nebula.exe as per README.md. Any help would be appreciated since I'm not really sure where to go from here since there are no registry entries and I don't see a process for registering wintun.dll.

**Comment by LookoutHill** [comment]
Yep, that fixed my issue.
