### ISSUE TITLE
Ip conflict

### ISSUE THREAD

**Issue by vellurk** [slackhq/nebula#904]
### What version of `nebula` are you using?

1.6.1

### What operating system are you using?

Windows

### Describe the Bug

We have nebula light house and three windows nodes a, b, c; c is a server is in azure vm. a and b are user laptop. if we use same private key and private certificate, both machines getting same ip 192.168.2.3. so if we connect azure vm from these two laptops b,c one machine is getting connected. seems ip conflict, is there a way to have different ip with same private key and private certificate?

### Logs from affected hosts

ipconflict

### Config files from affected hosts

ok

**Comment by JohnMaguire** [comment]
Hi @vellurk -

A Nebula host certificate/private keypair is comprised of a _public_ certificate (which contains a public key as well as other information about the host, such as its name and **IP address**), and a _private_ key used for signing operations in handshakes.

Because the certificate contains both the IP address and host public key, it's not possible to have two hosts share a keypair with separate IP addresses.

While this is not supported, I am curious what your use case is?

**Comment by JohnMaguire** [comment]
> We want to use same private key and private certificate in 6 machines, but with different ip, like dhcp lease, is this possible? Get Outlook for iOS<[aka.ms/o0ukef](https://aka.ms/o0ukef)>

@vellurk Please read my original reply. There is no private certificate, only a public certificate. It's not possible to use different IP addresses with the same keypair. You need to issue a keypair for host. Sorry!

**Comment by vellurk** [comment]
Okay thanks for the update, so if a user have 6 desktop pc means we have to create seperate key pair for him right?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vellurk** [comment]
I mean seperate key pair for each desktop

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vellurk** [comment]
Can you please provide update

**Comment by JohnMaguire** [comment]
@vellurk Yes, each device needs its own cert/keypair.

**Comment by vellurk** [comment]
Thanks for the update is there any way to assign different nebula ip for the five desktops with same key pair for the user

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JohnMaguire** [comment]
No.
