### ISSUE TITLE
How to check ipconflict in nebula network?

### ISSUE THREAD

**Issue by String-syncfusion** [slackhq/nebula#906]
We have nebula light house and three windows nodes A, B, C.  C is a server is in azure. 

A and B are user laptop, if we use same node certificate and key in both laptop means we are getting same IP 192.168.2.3. 
And then we have tested to connect C (azure vm) from these two laptops (A and B) one machine is getting connected and other machine is getting an error, looks like a ip conflict.

is there any way to find ip conflict in lighthouse if we apply same node certificate and key in different servers?

**Comment by JohnMaguire** [comment]
> A and B are user laptop, if we use same node certificate and key in both laptop means we are getting same IP 192.168.2.3.

@String-syncfusion As I mentioned in #904, this is expected. You need to issue different certificates and keys for each user. The certificate contains the IP address. Each device needs to have a unique certificate and private key.
