### ISSUE TITLE
Nebula on host throws x25519 error on setup

### ISSUE THREAD

**Issue by josh-ho** [slackhq/nebula#92]
I am trying to setup Nebula on a linux machine (nebula-linux-amd64.tar.gz), followed the instructions up to step 7 but once I get to step 7 and try to run Nebula on my host I get a response of:
```FATA[0000] error while unmarshaling ...bytes did not contain a proper nebula X25519 private key banner```

I have tried to create my key with openssl, but so far no luck.  

Any help is appreciated.

**Comment by rawdigits** [comment]
Hi @josh-ho. OpenSSL does not support creation of Nebula certificates. You will need to use the bundled nebula-cert tool to generate Nebula certificates.

Closing for now, thanks!

**Comment by josh-ho** [comment]
@rawdigits I've tried to generate a cert with `./nebula-cert ...` but I am still getting the same error

**Comment by nbrownus** [comment]
My guess would be your config references a `pki.key` file that exists but is corrupt or empty. We'd need to see your config and key file if they look correct to you.
