### ISSUE TITLE
Performance on large scale networks

### ISSUE THREAD

**Issue by yilunzhang** [slackhq/nebula#93]
First of all, thanks for your good work and make it open source!

We might be able to use nebula on our large scale network with around 20k+ nodes but I'm not sure if it fits into the scale. I saw in the medium post that you are running nebula on thousands of servers in Slack and I was wondering if they are in the same nebula network? Also what is the largest network size you have ever tried? Did you faced any issues (e.g. routing inefficiency) at scale? 

Thanks!

**Comment by rawdigits** [comment]
You'll be fine with 20k+ nodes on a single network. You'd probably be fine with some multiple of that as well. We have direct involvement on networks even larger operating without issue. The lighthouses are going to be the limiting factor, but ours handle at least that many hosts on rather modest hardware and have no issue.

Closing for now, but if you have further questions or want to let us know how it goes, we'd be happy to hear.

**Comment by yilunzhang** [comment]
Thanks for the info. When you say the limiting factor is lighthouse, do you mean it's the limiting factor when network is set up, or constantly when the network is up and running? On the other words, does lighthouse need to be both powerful and robust when network is running? Thanks!

**Comment by rawdigits** [comment]
Every node has a tunnel to the lighthouse, so it needs to be able to maintain n-1 nodes worth of tunnels. In practice each tunnel is a small amount of memory, and while I don't have numbers in front of me, a host with 8 gig of memory could probably host many more nodes than you have today.

The cpu use is modest, because these are mostly lookup boxes and the protocol is UDP.

**Comment by rawdigits** [comment]
Also of note: depending on your env, you should stand up multiple lighthouses in parallel and have every host talk to every lighthouse. It provides redundancy. Lighthouses should not be configured to talk to each other, and you should treat them as entirely separate entities.
