### ISSUE TITLE
🐛 BUG: Windows service disappears 

### ISSUE THREAD

**Issue by Derkades** [slackhq/nebula#937]
### What version of `nebula` are you using?

1.6.1 (due to defender false positive in the latest version)

### What operating system are you using?

Windows 11 22H2

### Describe the Bug

I have installed Nebula on a friend's PC using the -service option to create Windows service. However, after a while the VPN no longer starts at boot because the service has disappeared.

I don't know when it happens, perhaps Windows Update? I install it, reboot to test, and everything seems fine. But a few days later my friend reports it's broken again.

Is this something you seen before? Any hints as to where to start troubleshooting? Thanks.

**Comment by JohnMaguire** [comment]
Hi @Derkades -

Thanks for reporting the issue. Nebula doesn't remove its service unless you run the `nebula service uninstall` command. If that didn't happen, I'm not sure where the service went! This sounds like some kind of built-in Windows behavior biting you. You could try searching the Event Viewer to find something relevant? Otherwise, I'm not really sure how to help with this ticket.

**Comment by ikto-art** [comment]
Hi,

I had this problem but it was linked to the fact that Windows 11 still recognizes the latest nebula.exe release as a Trojan and removes it. The only workaround I found to is to temporarily disable the real-time Windows Defender feature, then download and extract nebula.exe to its final destination, then add the executable that you extracted to the Windows Defender exclusions (as a file, with the entire path).
Then reactivate the real-time Defender feature and reinstall/rerun the service.

PS: I personally use a script to automatically install and run Nebula as a task at startup and at installation, using the following files in the folder C:\SSH\Nebula:

_nebula.bat_
```
nebula.exe -config config.yml > nebula.log 2>&1
```

_create_and_run_task.bat_
```
@echo off
schtasks /create /xml C:\SSH\Nebula\nebula.xml /tn "\Nebula\Nebula"
schtasks /run /tn "\Nebula\Nebula"
echo Nebula installed and running.
pause
```

_nebula.xml_
```
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2023-06-22T06:25:38.3733629</Date>
    <Author>SYSTEM</Author>
    <URI>\Nebula\Nebula</URI>
  </RegistrationInfo>
  <Triggers>
    <BootTrigger>
      <Enabled>true</Enabled>
    </BootTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-18</UserId>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>
    <UseUnifiedSchedulingEngine>true</UseUnifiedSchedulingEngine>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
    <RestartOnFailure>
      <Interval>PT1M</Interval>
      <Count>3</Count>
    </RestartOnFailure>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>C:\SSH\Nebula\nebula.bat</Command>
      <WorkingDirectory>C:\SSH\Nebula\</WorkingDirectory>
    </Exec>
  </Actions>
</Task>
```

Finally I created a shortcut to C:\SSH\Nebula\create_and_run_task.bat with "Run as administrator" option so I can just double-click it and it will either install the task and run it or just run it if already installed, or do nothing if Nebula is already running.

**Comment by Derkades** [comment]
Thanks for the input, you are saying it is Windows defender even for the old 1.6.1 version? The actual nebula executable is not removed, just the service added using `.\nebula.exe -service install`. There are no related entries in the Windows defender history.

**Comment by ikto-art** [comment]
> Thanks for the input, you are saying it is Windows defender even for the old 1.6.1 version? The actual nebula executable is not removed, just the service added using `.\nebula.exe -service install`. There are no related entries in the Windows defender history.

I didn't pick up on the fact that you were using an older version, I don't remember having issues with the 1.6.1 version and if the executable is not removed nor blocked by Windows then it is probably not related to Windows Defender.
I never used the 'service' option personally, maybe you can look at the logs from the Event Viewer or other software that might uninstall the service for other reasons?
