### ISSUE TITLE
🐛 BUG: virustotal.com - 25 security vendors and no sandboxes flagged this file as malicious. Trojan.Kryptik, Malware

### ISSUE THREAD

**Issue by aarzhanov** [slackhq/nebula#942]
### What version of `nebula` are you using?

1.7.2

### What operating system are you using?

Mac, Windows

### Describe the Bug

The problem is that different anti-virus programs detect the nebula's executable file as containing a Trojan/Malware/etc.

This is a [link](https://www.virustotal.com/gui/file/e65b7de82a4d99b8c6657ffaf4c0437a4c576ab3e3ceca022fbdf45fae438b03/detection) with scan results for release v1.7.2 - nebula-windows-amd64.zip

This is a [link](https://www.virustotal.com/gui/file/e4e349f23ff7137c5e749c8a3b32631956aff2d88cef09254b02bbdd100e7b9c) with scan results for release v1.7.2 - nebula-darwin.zip

If you build the executable file yourself, this does not solve the problem. Antiviruses such as McAfee still identify the file as containing a Trojan.

Starting with version 1.5.0, the file is identified as containing a Trojan on virustotal.com.

It seems to me that the seriousness of this problem is underestimated. This leads to quite serious problems if we imagine a situation where the nebula is used on a large number of Windows machines and access to the RDP is provided through a mesh network. If the antivirus is triggered, we lose access to the machine if it was provided only through the mesh network.

### Logs from affected hosts

none

### Config files from affected hosts

none

**Comment by IanVS** [comment]
Merging with https://github.com/slackhq/nebula/issues/902
