### ISSUE TITLE
Unclear error message

### ISSUE THREAD

**Issue by j2ghz** [slackhq/nebula#95]
When trying to start nebula I got this error message:
```
time="2019-12-13T15:42:14Z" level=debug msg="Trusted CA fingerprints" fingerprints="[...]"
time="2019-12-13T15:42:14Z" level=debug msg="Client nebula certificate" cert="..."
time="2019-12-13T15:42:14Z" level=info msg="Firewall rule added" firewallRule="..."
time="2019-12-13T15:42:14Z" level=info msg="Firewall rule added" firewallRule="..."
time="2019-12-13T15:42:14Z" level=info msg="Firewall rule added" firewallRule="..."
time="2019-12-13T15:42:14Z" level=info msg="Firewall started" firewallHash=...
time="2019-12-13T15:42:14Z" level=fatal msg="no such file or directory"
```
I suggest adding the path of the file that was not found. Or at least when it happened: When loading configuration? When creating the network device? When reading the certificates?

**Comment by rawdigits** [comment]
It is worth trying the version in the master branch. We made a number of improvements to error messages over the past few weeks. The milestone for 1.1 release only has a few things left to complete, so precompiled binaries should be available soon.

**Comment by rawdigits** [comment]
I think this is corrected in the latest builds, and since this has been open for 2 weeks, going to close for now. Feel free to reengage here if the issue persists past 1.1
