### ISSUE TITLE
Feature Request: Support for Split Horizon DNS

### ISSUE THREAD

**Issue by benyanke** [slackhq/nebula#960]
### What version of `nebula` are you using?

1.7.2

### What operating system are you using?

ios, linux

### Describe the Bug

I would love to see some sort of support for split-horizon DNS with nebula.

In short, this would allow administrators to host public services, but to also expose those same services on a nebula network, and for clients seamlessly to resolve the DNS record for the nebula service when connected to the nebula network.

Note that I'm not proposing tweaks to the built-in lighthouse DNS server, but rather, adding functionality to the client that would change the end-user's resolving nameserver (or something similar) when it comes online.

**Comment by benyanke** [comment]
I'm seeing something else for #9 - is that the one you meant to link?

**Comment by JohnMaguire** [comment]
Hi @benyanke - can you describe how #971 more closely describes the desired behavior than #9?

You stated:

> Note that I'm not proposing tweaks to the built-in lighthouse DNS server, but rather, adding functionality to the client that would change the end-user's resolving nameserver (or something similar) when it comes online.

My understanding is that you are asking for Nebula to re-configure the system-wide DNS resolver when Nebula connects.

**Comment by JohnMaguire** [comment]
Ugh, thanks. #318 is what I meant to link.

**Comment by benyanke** [comment]
Thanks, John. Yes, that's an accurate dupe, I'll move any discussions over there.
