### ISSUE TITLE
Can I set up mutliple lighthouse servers for redundancy?

### ISSUE THREAD

**Issue by egg1234** [slackhq/nebula#962]
If the answer is yes, I expect to use the following configuration.

static_host_map:
  "192.168.100.1": ["www.yourdomain.com:4242"]
  "192.168.100.2": ["1.2.3.4:4242"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - '192.168.100.1'
    - '192.168.100.2'

**Comment by brad-defined** [comment]
yes you can, and just like you posted, you need to map the Nebula IP of your lighthouses to their real IP's, and specify each lighthouse in the lighthouse.hosts list.
