### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by Magesh07subramanian** [slackhq/nebula#970]
### What version of `nebula` are you using?

0.3.1

### What operating system are you using?

Android

### Describe the Bug

Hi, this is Magesh. I would like to inform you that we are using the Nebula mobile application on our end. Could you please update which Android version is not supported for the Nebula mobile app?

### Logs from affected hosts

this device is not compatible of this app

**Comment by JohnMaguire** [comment]
Hi @Magesh07subramanian -

This tracker is used for the Nebula software run on servers and desktops/laptops. For mobile, please file a ticket over at https://github.com/DefinedNet/mobile_nebula

Additionally, I'm afraid I don't understand your request. Are you saying that the app doesn't support your version of Android? If so, please include which version of Android that happens to be when filing your ticket.

Thanks!

**Comment by Magesh07subramanian** [comment]
HI @JohnMaguire 

My requirement is the Nebula mobile application; which Android version is supported? We are using Android 6 and Android 7 mobiles for my testing purposes, but I was not able to download the Nebula application for Android 6 or 7. Is the Nebula mobile application suitable for Android versions 6 and 7?

So there are issues we are facing on my end. Could you share the details?

**Comment by JohnMaguire** [comment]
@Magesh07subramanian I'm afraid only Android 8+ are supported. We have no plans to add support for older versions of Android.
