### ISSUE TITLE
Feature request: Firewall to reject connections instead of dropping them

### ISSUE THREAD

**Issue by 1player** [slackhq/nebula#993]
By default if a connection is not explicitly allowed in the Firewall settings, it will be silently dropped. A DROP action makes sense on the outer internet where there's a lot of malicious actors, in a local network I control (ie Nebula) I'd rather connections be rejected so I immediately know what's going on by getting *connection refused* errors, rather that having connections hang or time out.

Please add a configurable toggle to **reject** unallowed connections in the firewall instead of silently dropping them.

**Comment by JohnMaguire** [comment]
Hi @1player - since v1.7.0 Nebula this [can be configured.](https://github.com/slackhq/nebula/blob/master/examples/config.yml#L296-L305)

Does this look like what you want?

**Comment by 1player** [comment]
That's perfect. I don't see it in the official Nebula docs at https://nebula.defined.net/docs/config/firewall/, has this version been released yet? If so, feel free to close the issue.

**Comment by 1player** [comment]
Nevermind, I'm blind. Thanks for the quick update. I'll close the issue.
